### ISSUE TITLE
now,i canot run it in kub1.5.3

### ISSUE THREAD

**Issue by PANLEI361** [kubernetes/node-problem-detector#107]
`Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath				Type		Reason			Message
  ---------	--------	-----	----			-------------				--------	------			-------
  28m		28m		1	{kubelet 10.8.65.157}						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "kubernetes.io/host-path/5203c2d8-1b73-11e7-8754-46c88707ea0b-log" (spec.Name: "log") pod "5203c2d8-1b73-11e7-8754-46c88707ea0b" (UID: "5203c2d8-1b73-11e7-8754-46c88707ea0b").
  28m		28m		1	{kubelet 10.8.65.157}						Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "kubernetes.io/host-path/5203c2d8-1b73-11e7-8754-46c88707ea0b-localtime" (spec.Name: "localtime") pod "5203c2d8-1b73-11e7-8754-46c88707ea0b" (UID: "5203c2d8-1b73-11e7-8754-46c88707ea0b").
  28m		28m		1	{kubelet 10.8.65.157}	spec.containers{node-problem-detector}	Normal		Created			Created container with docker id e65759efc680; Security:[seccomp=unconfined]
  28m		28m		1	{kubelet 10.8.65.157}	spec.containers{node-problem-detector}	Normal		Started			Started container with docker id e65759efc680
  28m		28m		1	{kubelet 10.8.65.157}	spec.containers{node-problem-detector}	Normal		Created			Created container with docker id a7e78dfbe63a; Security:[seccomp=unconfined]
  28m		28m		1	{kubelet 10.8.65.157}	spec.containers{node-problem-detector}	Normal		Started			Started container with docker id a7e78dfbe63a
  27m		27m		2	{kubelet 10.8.65.157}						Warning		FailedSync		Error syncing pod, skipping: failed to "StartContainer" for "node-problem-detector" with CrashLoopBackOff: "Back-off 10s restarting failed container=node-problem-detector pod=node-problem-detector-gfx8q_default(5203c2d8-1b73-11e7-8754-46c88707ea0b)"

  27m	27m	1	{kubelet 10.8.65.157}	spec.containers{node-problem-detector}	Normal	Created		Created container with docker id 6d3ac4da1b6e; Security:[seccomp=unconfined]
  27m	27m	1	{kubelet 10.8.65.157}	spec.containers{node-problem-detector}	Normal	Started		Started container with docker id 6d3ac4da1b6e
  27m	27m	2	{kubelet 10.8.65.157}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "node-problem-detector" with CrashLoopBackOff: "Back-off 20s restarting failed container=node-problem-detector pod=node-problem-detector-gfx8q_default(5203c2d8-1b73-11e7-8754-46c88707ea0b)"

`

**Comment by Random-Liu** [comment]
@PANLEI361 It seems that NPD exited after you started it. You should be able to see some error message in NPD log.

Could you use `kubectl logs` to get the log and paste here?

**Comment by PANLEI361** [comment]
`I0413 10:42:35.146371       1 kernel_monitor.go:83] Finish parsing log file: {WatcherConfig:{KernelLogPath:/log/kern.log StartPattern:Initializing cgroup subsys cpuset Lookback:10m} BufferSize:10 Source:kernel-monitor DefaultConditions:[{Type:KernelDeadlock Status:false Transition:0001-01-01 00:00:00 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock}] Rules:[{Type:temporary Condition: Reason:OOMKilling Pattern:Kill process \d+ (.+) score \d+ or sacrifice child\nKilled process \d+ (.+) total-vm:\d+kB, anon-rss:\d+kB, file-rss:\d+kB} {Type:temporary Condition: Reason:TaskHung Pattern:task \S+:\w+ blocked for more than \w+ seconds\.} {Type:temporary Condition: Reason:KernelPanic Pattern:BUG: unable to handle kernel NULL pointer dereference at .*} {Type:temporary Condition: Reason:KernelPanic Pattern:divide error: 0000 \[#\d+\] SMP} {Type:permanent Condition:KernelDeadlock Reason:AUFSUmountHung Pattern:task umount\.aufs:\w+ blocked for more than \w+ seconds\.} {Type:permanent Condition:KernelDeadlock Reason:DockerHung Pattern:task docker:\w+ blocked for more than \w+ seconds\.} {Type:permanent Condition:KernelDeadlock Reason:UnregisterNetDeviceIssue Pattern:unregister_netdevice: waiting for \w+ to become free. Usage count = \d+}]}
panic: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
goroutine 1 [running]:
panic(0x114e4e0, 0xc420011170)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/node-problem-detector/pkg/problemclient.NewClientOrDie(0xc420532380, 0xc420486360)
	/usr/local/google/home/lantaol/workspace/src/k8s.io/node-problem-detector/pkg/problemclient/problem_client.go:56 +0x3c5
k8s.io/node-problem-detector/pkg/problemdetector.NewProblemDetector(0x199a2a0, 0xc4201d92b0, 0x199a2a0, 0xc4201d92b0)
	/usr/local/google/home/lantaol/workspace/src/k8s.io/node-problem-detector/pkg/problemdetector/problem_detector.go:45 +0x26
main.main()
	/usr/local/google/home/lantaol/workspace/src/k8s.io/node-problem-detector/node_problem_detector.go:33 +0x56
`

**Comment by PANLEI361** [comment]
I0413 10:42:35.146371       1 kernel_monitor.go:83] Finish parsing log file: {WatcherConfig:{KernelLogPath:/log/kern.log StartPattern:Initializing cgroup subsys cpuset Lookback:10m} BufferSize:10 Source:kernel-monitor DefaultConditions:[{Type:KernelDeadlock Status:false Transition:0001-01-01 00:00:00 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock}] Rules:[{Type:temporary Condition: Reason:OOMKilling Pattern:Kill process \d+ (.+) score \d+ or sacrifice child\nKilled process \d+ (.+) total-vm:\d+kB, anon-rss:\d+kB, file-rss:\d+kB} {Type:temporary Condition: Reason:TaskHung Pattern:task \S+:\w+ blocked for more than \w+ seconds\.} {Type:temporary Condition: Reason:KernelPanic Pattern:BUG: unable to handle kernel NULL pointer dereference at .*} {Type:temporary Condition: Reason:KernelPanic Pattern:divide error: 0000 \[#\d+\] SMP} {Type:permanent Condition:KernelDeadlock Reason:AUFSUmountHung Pattern:task umount\.aufs:\w+ blocked for more than \w+ seconds\.} {Type:permanent Condition:KernelDeadlock Reason:DockerHung Pattern:task docker:\w+ blocked for more than \w+ seconds\.} {Type:permanent Condition:KernelDeadlock Reason:UnregisterNetDeviceIssue Pattern:unregister_netdevice: waiting for \w+ to become free. Usage count = \d+}]}
panic: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
goroutine 1 [running]:
panic(0x114e4e0, 0xc420011170)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/node-problem-detector/pkg/problemclient.NewClientOrDie(0xc420532380, 0xc420486360)
	/usr/local/google/home/lantaol/workspace/src/k8s.io/node-problem-detector/pkg/problemclient/problem_client.go:56 +0x3c5
k8s.io/node-problem-detector/pkg/problemdetector.NewProblemDetector(0x199a2a0, 0xc4201d92b0, 0x199a2a0, 0xc4201d92b0)
	/usr/local/google/home/lantaol/workspace/src/k8s.io/node-problem-detector/pkg/problemdetector/problem_detector.go:45 +0x26
main.main()
	/usr/local/google/home/lantaol/workspace/src/k8s.io/node-problem-detector/node_problem_detector.go:33 +0x56

**Comment by PANLEI361** [comment]
`I0413 10:42:35.146371       1 kernel_monitor.go:83] Finish parsing log file: {WatcherConfig:{KernelLogPath:/log/kern.log StartPattern:Initializing cgroup subsys cpuset Lookback:10m} BufferSize:10 Source:kernel-monitor DefaultConditions:[{Type:KernelDeadlock Status:false Transition:0001-01-01 00:00:00 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock}] Rules:[{Type:temporary Condition: Reason:OOMKilling Pattern:Kill process \d+ (.+) score \d+ or sacrifice child\nKilled process \d+ (.+) total-vm:\d+kB, anon-rss:\d+kB, file-rss:\d+kB} {Type:temporary Condition: Reason:TaskHung Pattern:task \S+:\w+ blocked for more than \w+ seconds\.} {Type:temporary Condition: Reason:KernelPanic Pattern:BUG: unable to handle kernel NULL pointer dereference at .*} {Type:temporary Condition: Reason:KernelPanic Pattern:divide error: 0000 \[#\d+\] SMP} {Type:permanent Condition:KernelDeadlock Reason:AUFSUmountHung Pattern:task umount\.aufs:\w+ blocked for more than \w+ seconds\.} {Type:permanent Condition:KernelDeadlock Reason:DockerHung Pattern:task docker:\w+ blocked for more than \w+ seconds\.} {Type:permanent Condition:KernelDeadlock Reason:UnregisterNetDeviceIssue Pattern:unregister_netdevice: waiting for \w+ to become free. Usage count = \d+}]}
panic: open **/var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
goroutine 1 [running]:**
panic(0x114e4e0, 0xc420011170)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/node-problem-detector/pkg/problemclient.NewClientOrDie(0xc420532380, 0xc420486360)
	/usr/local/google/home/lantaol/workspace/src/k8s.io/node-problem-detector/pkg/problemclient/problem_client.go:56 +0x3c5
k8s.io/node-problem-detector/pkg/problemdetector.NewProblemDetector(0x199a2a0, 0xc4201d92b0, 0x199a2a0, 0xc4201d92b0)
	/usr/local/google/home/lantaol/workspace/src/k8s.io/node-problem-detector/pkg/problemdetector/problem_detector.go:45 +0x26
main.main()
	/usr/local/google/home/lantaol/workspace/src/k8s.io/node-problem-detector/node_problem_detector.go:33 +0x56
`

**Comment by PANLEI361** [comment]
[root@node-156 kubernetes.io~glusterfs]# kubectl logs node-problem-detector-2xgrq
I0413 10:42:35.146371       1 kernel_monitor.go:83] Finish parsing log file: {WatcherConfig:{KernelLogPath:/log/kern.log StartPattern:Initializing cgroup subsys cpuset Lookback:10m} BufferSize:10 Source:kernel-monitor DefaultConditions:[{Type:KernelDeadlock Status:false Transition:0001-01-01 00:00:00 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock}] Rules:[{Type:temporary Condition: Reason:OOMKilling Pattern:Kill process \d+ (.+) score \d+ or sacrifice child\nKilled process \d+ (.+) total-vm:\d+kB, anon-rss:\d+kB, file-rss:\d+kB} {Type:temporary Condition: Reason:TaskHung Pattern:task \S+:\w+ blocked for more than \w+ seconds\.} {Type:temporary Condition: Reason:KernelPanic Pattern:BUG: unable to handle kernel NULL pointer dereference at .*} {Type:temporary Condition: Reason:KernelPanic Pattern:divide error: 0000 \[#\d+\] SMP} {Type:permanent Condition:KernelDeadlock Reason:AUFSUmountHung Pattern:task umount\.aufs:\w+ blocked for more than \w+ seconds\.} {Type:permanent Condition:KernelDeadlock Reason:DockerHung Pattern:task docker:\w+ blocked for more than \w+ seconds\.} {Type:permanent Condition:KernelDeadlock Reason:UnregisterNetDeviceIssue Pattern:unregister_netdevice: waiting for \w+ to become free. Usage count = \d+}]}
panic: **open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
goroutine 1 [running]:**
panic(0x114e4e0, 0xc420011170)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/node-problem-detector/pkg/problemclient.NewClientOrDie(0xc420532380, 0xc420486360)
	/usr/local/google/home/lantaol/workspace/src/k8s.io/node-problem-detector/pkg/problemclient/problem_client.go:56 +0x3c5
k8s.io/node-problem-detector/pkg/problemdetector.NewProblemDetector(0x199a2a0, 0xc4201d92b0, 0x199a2a0, 0xc4201d92b0)
	/usr/local/google/home/lantaol/workspace/src/k8s.io/node-problem-detector/pkg/problemdetector/problem_detector.go:45 +0x26
main.main()
	/usr/local/google/home/lantaol/workspace/src/k8s.io/node-problem-detector/node_problem_detector.go:33 +0x56

**Comment by Random-Liu** [comment]
Yeah, I think that is the problem.

It seems that you didn't enable [`ServiceAccount`](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/) in your cluster.

If you don't want to use `ServiceAccount`, you could configure the `apiserver-override` flag to tell NPD how to connect apiserver, e.g.:
```
http://APISERVER_IP:APISERVER_PORT?inClusterConfig=false
```

The flag follows the same format with heapster `source` config: https://github.com/kubernetes/heapster/blob/master/docs/source-configuration.md#kubernetes.
