### ISSUE TITLE
NPD sending too many node-status updates in scale tests

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/node-problem-detector#124]
We ran 4k-node scalability test and observed that fluentd gets oom-killed frequently.
However, npd seems to send too many patch node-status requests (~3k qps out of ~11k total qps) due to it.
Ref: https://github.com/kubernetes/kubernetes/issues/47344#issuecomment-311018976 https://github.com/kubernetes/kubernetes/issues/47865#issuecomment-310861405

Why is it reporting oom events when kubelet seems to do that?
Can we make npd report ooms for just system processes and let kubelet alone take care of k8s containers (by modifying npd's 'OOMKilling' rule)?

cc @Random-Liu @gmarek @kubernetes/sig-node-bugs

**Comment by shyamjvs** [comment]
We should at least limit qps for npd.

**Comment by Random-Liu** [comment]
> However, npd seems to send too many patch node-status requests (~3k qps out of ~11k total qps) due to it.

NPD only send event when OOM happens, it doesn't patch node status.

> Why is it reporting oom events when kubelet seems to do that?
> Can we make npd report ooms for just system processes and let kubelet alone take care of k8s containers (by modifying npd's 'OOMKilling' rule)?

Yeah, we should consolidate this, either remove the OOM event from kubelet. Or let kubelet take care of pods, and NPD only monitor system services.

**Comment by gmarek** [comment]
+1 for NPD caring only about system services (i.e. not-pods).

**Comment by shyamjvs** [comment]
@Random-Liu I just verified from the apiserver logs (from run 10 of gce-enormous-cluster test) and indeed the majority of the requests are PATCH node status.

```
$ grep " 09:50:47" kube-apiserver-gce-enormous-run10.log | grep " 429 " | grep "\[\[node-problem" | wc -l
2802
$ grep " 09:50:47" kube-apiserver-gce-enormous-run10.log | grep " 429 " | grep "\[\[node-problem" | grep "/status:" | grep "PATCH" | wc -l
2701
$ grep " 09:50:47" kube-apiserver-gce-enormous-run10.log | grep " 429 " | grep "\[\[node-problem" | grep "/events" | grep "PATCH" | wc -l
33
$ grep " 09:50:47" kube-apiserver-gce-enormous-run10.log | grep " 429 " | grep "\[\[node-problem" | grep "/events" | grep "POST" | wc -l
68
```

**Comment by Random-Liu** [comment]
@shyamjvs If so, this seems to be client-go that retries patching. NPD won't do that so frequently.

Client-go should probably be error code aware, retry immediately for conflict, but wait longer for 429.

**Comment by yujuhong** [comment]
The REST client has its own retry loop: https://github.com/kubernetes/kubernetes/blob/v1.8.0-alpha.1/staging/src/k8s.io/client-go/rest/request.go#L858
kubelet (or any other system component) using the client will retry in the same manner. The client has a [backoff manager](https://github.com/kubernetes/kubernetes/blob/v1.8.0-alpha.1/staging/src/k8s.io/client-go/rest/request.go#L814), but I doubt it's set by default since kubelet was also generating a lot of retries after seeing 429.

**Comment by shyamjvs** [comment]
> Client-go should probably be error code aware, retry immediately for conflict, but wait longer for 429.

Makes sense. Filed an issue for it. We should have the backoff manager at least for the case of 429s imo.

**Comment by shyamjvs** [comment]
@Random-Liu @yujuhong Thanks a lot for looking into it :)

**Comment by shyamjvs** [comment]
Linking issue https://github.com/kubernetes/kubernetes/issues/47344
