### ISSUE TITLE
OOMKilling not triggering with recent kernels

### ISSUE THREAD

**Issue by therc** [kubernetes/node-problem-detector#125]
With Linux 4.9, and perhaps earlier versions, there's a trailing

`, shmem-rss:\\d+kB`

Should it be optional in the built-in regex, are admins expect to edit their configuration, or something else?

**Comment by Random-Liu** [comment]
> Should it be optional in the built-in regex, are admins expect to edit their configuration, or something else?

Yeah, admins should edit their configuration for their environment for most cases. But for this one, I think it should be optional in the built-in regex.

Do you mind sending a PR for this? :) If not, I could do that later.
