### ISSUE TITLE
ARM version

### ISSUE THREAD

**Issue by nlamirault** [kubernetes/node-problem-detector#135]
Is a multi-architecture version (ARM) possible?

**Comment by nvtkaszpir** [comment]
Reopening due to the fact that more and more hardware is used nowadays and maybe it is a good time to reconsider it.

**Comment by nvtkaszpir** [comment]
/assign @Random-Liu
Maybe it is worth to add multi-arch builds?
Should it be then converted to new issue?

**Comment by cerebrate** [comment]
/remove-lifecycle stale

I have several ARM-based clusters that could use this.

**Comment by cerebrate** [comment]
/remove-lifecycle stale

Still relevant.

**Comment by invidian** [comment]
Lokomotive would be also interested in ARM version (https://github.com/kinvolk/lokomotive/pull/1384).

**Comment by vteratipally** [comment]
NPD started releasing arm versions from v0.8.8

**Comment by nvtkaszpir** [comment]
@vteratipally on release page of v0.8.8 (as of page of writing) there are only linux-amd64 and windows builds.
So where is ARM version?

**Comment by vteratipally** [comment]
I apologize for the confusion, the NPD arm binaries would be released from the next version.

**Comment by vteratipally** [comment]
https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.9

**Comment by nvtkaszpir** [comment]
thx, very nice!

**Comment by cerebrate** [comment]
Thanks, working great for me!
