### ISSUE TITLE
port 10256 conflicts with kube-proxy

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/node-problem-detector#138]
it seems that a healthcheck/debug port was added [here](https://github.com/kubernetes/node-problem-detector/pull/83); however, it conflicts with the [kube-proxy healthz port](https://github.com/kubernetes/kubernetes/blob/01e961b380eea90d111156b8e99cc9621c5cdb5f/pkg/apis/componentconfig/v1alpha1/types.go#L110). They should be different.

**Comment by andyxning** [comment]
@jhorwit2 The kube-proxy healthz port is added in [this commit](https://github.com/kubernetes/kubernetes/commit/ca59d909cf1f1effad62830b1beeb3ea8a9d2125) which is later than npd healthz.

It is absolutely ok to change NPD healthz port through command line `port`. 

I do not think we need to change the default healthz port for NPD as it may still conflict with other daemons on that node whatever port we choose just like kube-proxy. :)

**Comment by jhorwit2** [comment]
If im not mistaken i thought there was a doc with port allocations to avoid conflicts.

**Comment by andyxning** [comment]
@jhorwit2 Yes, there is a [ports pkg](https://github.com/kubernetes/kubernetes/blob/master/pkg/master/ports/ports.go). It is recommended to register all used ports in that package however it is not forced. :( 
Therefore Kubernetes and satellites may conflicts. 

Actually, when @Random-Liu added healthz port to NPD, we have [grep `10256` in Kubernetes and some satellites](https://github.com/kubernetes/node-problem-detector/pull/83#issuecomment-277190993). Actually, [we first want to use `10254`](https://github.com/kubernetes/node-problem-detector/pull/83#issuecomment-277179884).

**Comment by andyxning** [comment]
@jhorwit2 Just found that this has been fix in master via #128 by changing `10256` to `20256`.

**Comment by jhorwit2** [comment]
Whoops I must have missed the `2` at the beginning when I checked master. Thanks @andyxning
