### ISSUE TITLE
KernelMonitor: Add journald support

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/node-problem-detector#14]
Add journald support.

Consider reusing [the code in cadvisor](https://github.com/google/cadvisor/blob/master/utils/oomparser/oomparser.go#L168), and maybe replace hpcloud/tail with the simpler implementation in cadvisor https://github.com/kubernetes/node-problem-detector/issues/3

**Comment by AdoHe** [comment]
@Random-Liu should we consider priority between journaled and kernel log file?

**Comment by Random-Liu** [comment]
@AdoHe Sorry, I didn't get your question. We only parse kernel log now, even using journald we also only care about kernel log inside. :)

**Comment by AdoHe** [comment]
@Random-Liu sorry about not explain very clearly, I mean whether we should consider the priority, just like cadvisor, first will try systemd, and then some log files.

**Comment by Random-Liu** [comment]
@AdoHe Yeah, I think so. If there is journald, we should use it first. :)

**Comment by derekwaynecarr** [comment]
@dchen1107 @Random-Liu @AdoHe -- is adding journald support on either of your roadmap for Kubernetes 1.5?  For example, would this be needed if/when you look to upgrade GCE node images?

/cc @hodovska

**Comment by Random-Liu** [comment]
@derekwaynecarr @dchen1107 I think we've to support journald if we are switching to GCI.

**Comment by AdoHe** [comment]
@Random-Liu I think I have did some research and want to give a retry. Will open a PR asap.

**Comment by Random-Liu** [comment]
@AdoHe Cool! It's very appreciate!
Just curious, how are you going to do that? Use go-systemd or mount journalctl binary or something? :)

**Comment by AdoHe** [comment]
@Random-Liu I was using go-systemd, I have researched its code.

**Comment by Random-Liu** [comment]
@AdoHe Hm, that's great! This will be quite useful!

Not only in node problem detector, we also have this problem in cadvisor (https://github.com/google/cadvisor/blob/381f24b4f22badecade6a51ed7539f11a926175e/utils/oomparser/oomparser.go#L168-L178). It is using `journalctl` binary directly, which IIUC doesn't actually work inside container given the cadvisor docker run command:
```
sudo docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest
```

**Comment by AdoHe** [comment]
Thanks @Random-Liu I will give a retry after finish this one. :)

**Comment by zihaoyu** [comment]
@AdoHe @Random-Liu Any update on this one? I'm running Kubernetes on CoreOS, which uses journald. I'm running a Docker image I built from master, but it looks like it is not watching journald logs.

**Comment by Random-Liu** [comment]
> @AdoHe @Random-Liu Any update on this one? I'm running Kubernetes on CoreOS, which uses journald. I'm running a Docker image I built from master, but it looks like it is not watching journald logs.

This is not completely done yet. I'm working on a PR recently, and may send the PR this week.

**Comment by zihaoyu** [comment]
@Random-Liu Thanks. Let me know if/how I can help. I'm going to test it in our staging cluster once it's ready.

**Comment by AdoHe** [comment]
@zihaoyu could you please provide your kernel monitor config file? For some personal stuff, this is not completely done.

**Comment by zihaoyu** [comment]
@AdoHe I'm just using the [provided](https://github.com/kubernetes/node-problem-detector/blob/master/config/kernel-monitor.json) config file. And apparently the `logPath` value does not work because logs are in journald.

**Comment by Random-Liu** [comment]
@AdoHe Thanks for your help!! It is almost done. I'll finish it soon. :)

**Comment by AdoHe** [comment]
@zihaoyu currently the implementation is if you specify `logPath` in config file, we will still use the file based watcher, you can see [here](https://github.com/kubernetes/node-problem-detector/blob/master/pkg/kernelmonitor/kernel_log_watcher.go#L170)

**Comment by Random-Liu** [comment]
@AdoHe In fact , a default path is always set in the code, so journald will never be used. In fact there are some other issues as well.
