### ISSUE TITLE
Include cmd/options in makefile test to run go tests

### ISSUE THREAD

**Issue by gkGaneshR** [kubernetes/node-problem-detector#163]
Is this a BUG REPORT or FEATURE REQUEST?:

Uncomment only one, leave it on its own line:
/kind feature

What happened:
Makefile's test must include cmd/options package for unit testing.

What you expected to happen:
Unit testing for node-problem-detector/cmd/options is yet to be done and the corresponding package path needs to be included in makefile test.

How to reproduce it (as minimally and precisely as possible):
Run the go test : "make test"

Anything else we need to know?:
The test needs to run with admin privileges since it mocks by changing hostname

Environment:

Kubernetes version (use kubectl version):
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release): Ubuntu:16.04
Kernel (e.g. uname -a): x86_64 GNU/Linux
Install tools: go
Others:

@kubernetes/sig-testing

**Comment by andyxning** [comment]
@gkGaneshR Does this have been addressed by https://github.com/kubernetes/node-problem-detector/pull/162.

**Comment by gkGaneshR** [comment]
Yes, I'll close the issue. Thanks
