### ISSUE TITLE
Wrong parm --kernel-monitor in NPD 0.4.1 sample yaml

### ISSUE THREAD

**Issue by calvinyv** [kubernetes/node-problem-detector#172]
I update the image to NPD 0.4.1 in sample yaml file deployment/node-problem-detector.yaml, I'm using  k8s 1.10.2, when apply this file, I got below error:  

The DaemonSet "node-problem-detector" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"node-problem-detector"}: `selector` does not match template `labels`  

Then I edit that yaml, and make below change:  
    metadata:  
      labels:  
        name: node-problem-detector  

Then I apply this file successfully and container fail to create because of below error:  

  Warning  FailedMount            37s               kubelet, i-362pv0q9  Unable to mount volumes for pod "node-problem-detector-fgn8l_default(b4ee45bd-53f6-11e8-8cf6-5254ad805bab)": timeout expired waiting for volumes to attach or mount for pod "default"/"node-problem-detector-fgn8l". list of unmounted volumes=[config]. list of unattached volumes=[log kmsg localtime config default-token-vxprc]
  Warning  FailedMount            29s (x9 over 2m)  kubelet, i-362pv0q9  MountVolume.SetUp failed for volume "config" : configmaps "node-problem-detector-config" not found

so what should the content of node-problem-detector-config be?

**Comment by MoShitrit** [comment]
@calvinyv you need to create the configmap based on the contents of `config` directory.
`kubectl create configmap node-problem-detector-config --from-file=config/`

**Comment by calvinyv** [comment]
@MoShitrit thanks for your response, after creating npd configmap, I could deploy npd ds, but the pods actually start with failure, and by checking its log, I could see:  
```
root@i-o5pmakm7:/opt/node-problem-detector/deployment# kubectl logs node-problem-detector-5dgzj
unknown flag: --kernel-monitor
Usage of /node-problem-detector:
      --address="127.0.0.1": The address to bind the node problem detector server.
      --alsologtostderr[=false]: log to standard error as well as files
      --apiserver-override="": Custom URI used to connect to Kubernetes ApiServer
      --hostname-override="": Custom node name used to override hostname
      --log_backtrace_at=:0: when logging hits line file:N, emit a stack trace
      --log_dir="": If non-empty, write log files in this directory
      --logtostderr[=false]: log to standard error instead of files
      --port=10256: The port to bind the node problem detector server. Use 0 to disable.
      --stderrthreshold=2: logs at or above this threshold go to stderr
      --system-log-monitors=[]: List of paths to system log monitor config files, comma separated.
      --v=0: log level for V logs
      --version[=false]: Print version information and quit
      --vmodule=: comma-separated list of pattern=N settings for file-filtered logging   
```
I search the code and do not find any command parm named kernel-monitor, so is it a bug in yaml file?

**Comment by MoShitrit** [comment]
@calvinyv Yeah I had the same error with version `0.4`.
Seems like they changed the set of args expected without updating the documentation.
Eventually I dropped to version `0.2` and it started working. I'm guessing that you can also remove this argument from the deployment YAML which would solve that error, but not sure about the impact it will have, since I didn't try that myself yet.
