### ISSUE TITLE
Is there an option to read `journald` without a file? (basically tail `journalctl` output)

### ISSUE THREAD

**Issue by MoShitrit** [kubernetes/node-problem-detector#174]
We would like to start using `npd` in our environment. However, the way our logging architecture is designed- we're not storing any logs locally. We have a `syslog-ng` client that tails `journalctl` output and forwards it to our `syslog` server without storing any local copies. Hence it seems like `npd` can't really read all these events. I tried to go through the documentation but didn't find anything that could be relevant to our scenario. Did I miss something? Is there a way to accomplish what I'm looking to get?
Thanks!

**Comment by andyxning** [comment]
@MoShitrit Sorry for the delay. 

Yes. npd has support for reading directly from journald. Actualy npd support both read kernel log from a file or journald. Please take a look at this the files under [config](../tree/master/config). Especially https://github.com/kubernetes/node-problem-detector/blob/master/config/kernel-monitor.json

**Comment by MoShitrit** [comment]
Thanks @andyxning !
I see indeed that kernel messages are flowing in to the kube-apiserver, however I was more curious regarding other logs such as Docker log and so on. We don't maintain any local log file such as `/var/log/messages` or `/var/log/docker/docker.log` and so on, they are all part of `journalctl` and are being forwarded directly to our `syslog` server. Does `npd` support tailing `journalctl` output for these logs as well?

**Comment by andyxning** [comment]
> Does npd support tailing journalctl output for these logs as well?

I am afraid not. NPD uses `github.com/coreos/go-systemd/sdjournal` package to read from journald. `http://www.freedesktop.org/software/systemd/man/sd-journal.html` seems to read local disk journal files to parse according to the [sd-journal.html](https://www.freedesktop.org/software/systemd/man/sd-journal.html).

**Comment by MoShitrit** [comment]
I see, thanks for your response!
