### ISSUE TITLE
Can an owner generate a release please 

### ISSUE THREAD

**Issue by ahakanbaba** [kubernetes/node-problem-detector#178]
We would like to start using node-problem-detector. 
If you could cut a release, using this would be much simpler.

**Comment by mohitsoni** [comment]
👍

**Comment by Random-Liu** [comment]
Done.

**Comment by mohitsoni** [comment]
Thanks @Random-Liu!

**Comment by andyxning** [comment]
Close this since a new release has been done.
/close
