### ISSUE TITLE
invalid user agent set when accessing kube-apiserver

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/node-problem-detector#181]
When start node-problem-detector with --v=10.
We can see such logs:
```
curl -k -v -XPATCH  -H "Accept: application/json, */*" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: node-problem-detector/v1.4.0 (linux/amd64) kubernetes/$Format" http://172.16.29.130:8080/api/v1/nodes/node2/status
```

The user agent is set to node-problem-detector/v1.4.0 (linux/amd64) kubernetes/$Format

The $Format seems should be replaced with the `git rev-parse HEAD`

**Comment by andyxning** [comment]
Thanks for reporting this. I have also encounter this in kube-state-metrics with `--v=10`. Will dig deeper to find the root reason. 

BTW, this should have no influence on the normal functionality of node-problem-detector nor kube-state-metrics.

**Comment by andyxning** [comment]
@CaoShuFeng It turns out that the `User-Agent: node-problem-detector/v1.4.0 (linux/amd64) kubernetes/$Format` is the output of client-go https://github.com/kubernetes/client-go/blob/2a94c229c06da7d798878d0bbef74e58c08d44be/rest/config.go#L253-L260
```golang
// SetKubernetesDefaults sets default values on the provided client config for accessing the
// Kubernetes API or returns an error if any of the defaults are impossible or invalid.
func SetKubernetesDefaults(config *Config) error {
	if len(config.UserAgent) == 0 {
		config.UserAgent = DefaultKubernetesUserAgent()
	}
	return nil
}
```

https://github.com/kubernetes/client-go/blob/master/rest/config.go#L299-L307

```golang
// DefaultKubernetesUserAgent returns a User-Agent string built from static global vars.
func DefaultKubernetesUserAgent() string {
	return buildUserAgent(
		adjustCommand(os.Args[0]),
		adjustVersion(version.Get().GitVersion),
		gruntime.GOOS,
		gruntime.GOARCH,
		adjustCommit(version.Get().GitCommit))
}
```
