### ISSUE TITLE
No events detected on vanilla EKS cluster (Amazon Linux)

### ISSUE THREAD

**Issue by jesseshieh** [kubernetes/node-problem-detector#184]
Hi, first of all thanks for this great project! I use npd on a k8s cluster on gce with no problems, but I recently decided to give aws eks a try and can't seem to get npd to report any events.  I'm sure I've just got it installed wrong somehow, but any help would be greatly appreciated! I also hope this helps anyone else trying to run npd on eks.

Here is what I did
1. follow the  [getting started guide](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html) to create a new eks cluster. note that the worker nodes are running Amazon Linux. [[1]](#snip-1)
2. install npd with `kubectl apply -f npd.yaml` [[2]](#snip-2)
3. exec into a pod and use a bunch of memory to generate an OOMKilled event. note that the journal shows the event correctly [[3]](#snip-3)
4. note that there is nothing in the node-problem-detector.log except for periodic status checks [[4]](#snip-4)

Things I checked
1. the journal files are indeed in `/var/log/journal` and the `Kill process` messages are indeed in there.
2. i scanned the rule regex by hand and it seems to match except for the leading `Memory cgroup out of memory: ` but I assume that's ok
3. `/var/log` is mounted into the npd pod.

I've run out of ideas short of forking npd and doing some debug logging, which I'm hoping to avoid.

<a name="snip-1">[1]</a>
```
[ec2-user@ip-192-168-227-171 etc]$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2 (2017.12)"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2 (2017.12) LTS Release Candidate"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

```

<a name="snip-2">[2]</a>
```
$ cat npd.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-problem-detector
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: npd-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-problem-detector
subjects:
- kind: ServiceAccount
  name: node-problem-detector
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: npd-v0.4.1
  namespace: kube-system
  labels:
    k8s-app: node-problem-detector
    version: v0.4.1
spec:
  template:
    metadata:
      labels:
        k8s-app: node-problem-detector
        version: v0.4.1
    spec:
      containers:
      - name: node-problem-detector
        image: k8s.gcr.io/node-problem-detector:v0.4.1
        command:
        - "/bin/sh"
        - "-c"
        # Pass both config to support both journald and syslog.
        - "exec /node-problem-detector --v=99 --logtostderr --system-log-monitors=/config/kernel-monitor.json,/config/docker-monitor.json >>/var/log/node-problem-detector.log 2>&1"
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "200m"
            memory: "100Mi"
          requests:
            cpu: "20m"
            memory: "20Mi"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log
          mountPath: /var/log
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: log
        hostPath:
          path: /var/log/
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: "FileOrCreate"
      serviceAccountName: node-problem-detector
      tolerations:
      - operator: "Exists"
        effect: "NoExecute"
      - key: "CriticalAddonsOnly"
 ```

<a name="snip-3">[3]</a>
```
[ec2-user@ip-192-168-227-171 ~]$ journalctl -f
Jun 25 03:34:05 ip-192-168-227-171.ec2.internal kernel: Memory cgroup out of memory: Kill process 14200 (beam.smp) score 1847 or sacrifice child
Jun 25 03:34:05 ip-192-168-227-171.ec2.internal kernel: Killed process 14200 (beam.smp) total-vm:4711536kB, anon-rss:447836kB, file-rss:3460kB, shmem-rss:0kB
Jun 25 03:34:05 ip-192-168-227-171.ec2.internal kernel: oom_reaper: reaped process 14200 (beam.smp), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

<a name="snip-4">[4]</a>
```
[ec2-user@ip-192-168-227-171 ~]$ tail -f /var/log/node-problem-detector.log
...
I0625 03:32:36.102456       1 round_trippers.go:318] PATCH https://10.100.0.1:443/api/v1/nodes/ip-192-168-227-171.ec2.internal/status 200 OK in 15 milliseconds
...
```

**Comment by iamzhout** [comment]
I guess there is some compatibility issue of *journaldWatcher* for Amazon Linux, do you see any other log in  *node-problem-detector.log* file?

**Comment by jesseshieh** [comment]
@iamzhout I don't see anything else interesting in node-problem-detector.log. Is there some troubleshooting or debugging steps I can take to try and narrow down the problem? I increased the log level and it doesn't seem like there is a problem reading the journal.

**Comment by andyxning** [comment]
I guess it is related with the log output format. @jesseshieh

**Comment by andyxning** [comment]
> Is there some troubleshooting or debugging steps I can take to try and narrow down the problem? 

Sorry. The answer is no. But it would be appreciated that you can contribute one by this digging this problem.

I am afraid the next steps for you are:
* read the related code 
* output the log read from journal when an oom kill is invoked
* output the match result of whether the oomkill pattern really match the output log.

Problems like this can mainly be resolved by users themselves as we, as the developers, can not easily get a scene to debug with. But we would like to offer some clues.

**Comment by jheidbrink** [comment]
Possibly this is not a EKS-specific problem, but a general problem with newer Kernels. "Newer" means containing [commit eca56ff9](https://github.com/torvalds/linux/commit/eca56ff906bdd0239485e8b47154a6e73dd9a2f3#diff-c14acc69885a24f354bc607686800e23) from 01/2016. It added a column for shared memory to the `Killed process` message, so the regex defined in `kernel-monitor.json` does not match anymore.

**Comment by max-rocket-internet** [comment]
@jesseshieh can you confirm this is resolved since the PR from @jheidbrink ?

**Comment by yrsurya** [comment]
We are planning to run these on EKS with amazonlinux AM wordker nodes , any issues we need to be taken care before we initialize?
