### ISSUE TITLE
gcr Image Tag v0.5.0 is missing bash and other binaries

### ISSUE THREAD

**Issue by chadswen** [kubernetes/node-problem-detector#185]
With the latest release it looks like the base image may have changed and some binaries are no longer packaged. Most custom plugin scripts depend on bash, and as a result those are no longer working for me.

[Image tag v0.5.0 details on gcr](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/node-problem-detector@sha256:ba9daf428e462bfb0e7078819193ec7d30e2d1fb38aa0cf8ba1187f9bba217dd/details?tab=info)

Refs #160

**Comment by andyxning** [comment]
@chadswen I have downloaded the v0.5.0 image from gcr.io and run `docker run -it --entrypoint=sh gcr.io/google-containers/node-problem-detector:v0.5.0`. The output of `cat /etc/os-release` is:
> PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

So, it seems that the base image has not been changed.

What is the indeed problem for you? @chadswen

**Comment by andyxning** [comment]
@chadswen I have prepared a PR to add bash to the debian-base image in https://github.com/kubernetes/kubernetes/pull/65949

**Comment by chadswen** [comment]
@andyxning Thanks!
