### ISSUE TITLE
Node Problem Detector should retry after failing to connect apiserver.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/node-problem-detector#19]
Failure happens.

Node Problem Detector should not just panic when fails to connect apiserver.

**Comment by andyxning** [comment]
apiserver may be **temporarily** unavailable or down.  An error log and make health check endpoint being 500 may be  more suitable when NPD can not connect apiserver. After apiserver come up to serve requests again, NPD should success and make health check endpoint being 200 again.

**Comment by Random-Liu** [comment]
> Apiserver may be temporarily unavailable or down. An error log and make health check endpoint being 500 may be more suitable when NPD can not connect apiserver. After apiserver come up to serve requests again, NPD should success to update status and make health check endpoint being 200 again. WDYT.

The health check endpoint should not return 500 when apiserver is down. For DaemonSet, it may be fine. But for standalone mode, the health check endpoint will be used to monitor NPD health and restart if not. (See how we deal with kubelet and docker https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/health-monitor.sh)

I don't think we want to keep restarting NPD when apiserver is down.

@andyxning I think we can let the health check endpoint always return 200 for now. In the future, we can add some health check based on the internal state of NPD.

**Comment by andyxning** [comment]
@Random-Liu 

> The health check endpoint should not return 500 when apiserver is down. For DaemonSet, it may be fine. But for standalone mode, the health check endpoint will be used to monitor NPD health and restart if not. (See how we deal with kubelet and docker https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/health-monitor.sh)
> I don't think we want to keep restarting NPD when apiserver is down.

If health check endpoint is used to validate and restart npd if it returns with non 200 response code, npd should not response with 500 for an unreachable apiserver.

I agree that health check endpoint should only return non 200 response code when some unrecovered condition happened inside npd which makes it can not work properly.
