### ISSUE TITLE
Measure the resource overhead of NodeProblemDetector

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/node-problem-detector#2]
To roll out the NodeProblemDetector and run it as an addon pods of Kubernetes, we need to understand its overhead, at least including cpu and memory overhead.

/cc @kubernetes/sig-node

**Comment by Random-Liu** [comment]
I've done some measurement. Here is the result:
![image](https://cloud.githubusercontent.com/assets/5821883/15386617/b111a3a0-1d5d-11e6-949e-2fe3a83ca871.png)
In the table above:
* Type is the problem type corresponding to the inserted log.
* Frequency is lines of log inserted every second.
* CPU is the stable cpu usage of the NodeProblemDetector.
* Memory is the stable memory usage of the NodeProblemDetector.

**Comment by Random-Liu** [comment]
According to the result above https://github.com/kubernetes/node-problem-detector/issues/2#issuecomment-220255629, the following configuration should be enough for now:
```
limits:
  cpu: 100m
  memory: 50Mi
requests:
  cpu: 100m
  memory: 50Mi
```
Because:
* 100 permanent/temporary problems/s should be rare, even the most frequent problem till now https://github.com/docker/docker/issues/5618 only produces one line in several seconds.
* Even the problem produces 100 lines of logs per second, the resource limit should also be enough.

**Comment by vishh** [comment]
nit: Requests need not be specified if this job is expected to be
`Guaranteed`.

**Comment by Random-Liu** [comment]
@vishh ACK. Thank you very much~ :)

**Comment by Random-Liu** [comment]
Close this since this is done.
