### ISSUE TITLE
Condition message doesn't update when the status is same

### ISSUE THREAD

**Issue by aga20** [kubernetes/node-problem-detector#200]
Hello,

we want to use the node problem detector  with custom plugins in our env where we have an internally developed alarm handling solution. We will implement a layer between kubernetes an our alarm handling solution which can raise alarm based on conditions and events. 
First we should check the free spaces on the nodes' partitions but we have a lot of node types with another volumes and partions (storage, etc...) so we can't able cover all node with one config (the npd run as a daemon set so the per node config is a little bit hard). We try to figure out a general solution and our final idea is next: we use only one general config and run one script which check the partitions/volume on the nodes. If one partition is full it exit with code 1 and print out the useful information for example /mnt/part 1 full on the node. This is ok when condition's status is change between True/False. But we want to update the condition message if an another partition for example part2 is full but the contdition status didn't change back to false yet (so the part1 is still full). As I see until the status is same you don't update the message [here](https://github.com/kubernetes/node-problem-detector/blob/master/pkg/custompluginmonitor/custom_plugin_monitor.go#L129).
I want to know this is the expected behaviour and what is the reason or we can change this behaviour? For us it can help a lot. 

Thanks!

**Comment by aga20** [comment]
@andyxning Could you comment it? Thanks!

**Comment by andyxning** [comment]
@aga20 
> But we want to update the condition message if an another partition for example part2 is full but the contdition status didn't change back to false yet (so the part1 is still full). As I see until the status is same you don't update the message 

This is mainly used to decrease the updates that needs to be done in between NPD and apiserver.

**Comment by andyxning** [comment]
IIUC, you mean that you need to recognize which partition to check and which partition is run out of space. You need to make the condition message structured in order to parse it easily and correctly.


Actually you can change the behavior. But what you should note is that this may make some pressure on your apiserver.

**Comment by aga20** [comment]
Hello,

yes we need a structured message of course but we want to use the message field to keep update our alarms. For example during a condition's status is "true" we should know if another partion is full. So ok, during a run I see 2 partition is full, I print out in a structured message. The sysadmin recognise the alarm and start to investigate the problem. The condition still in "true" state and the script run again and see another 3rd partition is full, print out the new message but the npd doesn't update the condition's message and we missed the new information. After a little the original 2 pratition is ok because someone made some free space but the condition is still "true" and the message stay same (what represent the two partition not the 3rd) because as the script report the 3rd partition is still full. 
This is why we need an updated message field if this is possible. 
I think we can live with a little bit more pressure on the api server but we can open a pull request or you don't want to change this in the node-problem-detector? 

Thanks!

**Comment by andyxning** [comment]
Since the error situation is seldom, it should be ok to do so. :)
A PR is welcomed. Feel free to ping me when the PR is fired.
@aga20

**Comment by aga20** [comment]
Hello,

sorry. I think this is ok,

**Comment by andyxning** [comment]
@aga20 Can you try the latest master branch, i.e., 0.6.1 release. Seems that NPD will not change the message when the status is the same. 

According to https://github.com/kubernetes/node-problem-detector/pull/228, we have remove this logic to avoid spam.

**Comment by aga20** [comment]
@andyxning Yes the message won't update if the status stay same. Could you fix this again? This is important for us as I mentioned earlier. 
Or if you want to avoid the spam and you can add a switch what control the status update we will happy (for example by default the npd doesn't resend the message but if someone want to do this we can turn this on). We can live a solution like this but I don't this can be possible in the current implementation. I just try to figure out a possible solution :)

**Comment by aga20** [comment]
Hello,
@andyxning seems ok. Thanks! When do you plan to release a new version?
