### ISSUE TITLE
Submitting a helm chart

### ISSUE THREAD

**Issue by max-rocket-internet** [kubernetes/node-problem-detector#206]
I just made a PR to helm charts repo:
https://github.com/helm/charts/pull/7795

Any feedback? I've largely just copied the config from the addons repo.

I also noticed the files in [here](https://github.com/kubernetes/node-problem-detector/tree/master/deployment) are out of date. Should I make a PR to update those too?

**Comment by andyxning** [comment]
Will take a look at this later. @max-rocket-internet Thanks.

**Comment by max-rocket-internet** [comment]
Finally merged. So hopefully this will bring more uses for npd and hopefully more useful problem detection. I will close this 🙂
