### ISSUE TITLE
Restore node condition

### ISSUE THREAD

**Issue by Lynzabo** [kubernetes/node-problem-detector#211]
Now I use NPD to add a few conditions for each node.

eg:

```shell
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------    -----------------                 ------------------                ------                       -------
  NTPProblem       Unknown   Fri, 12 Oct 2018 14:48:55 +0800   Fri, 12 Oct 2018 14:34:48 +0800   NTPIsDown                    Error in running plugin. Please check the error log
  KernelDeadlock   False     Fri, 12 Oct 2018 14:53:36 +0800   Fri, 12 Oct 2018 14:49:32 +0800   KernelHasNoDeadlock          kernel has no deadlock
  OutOfDisk        False     Fri, 12 Oct 2018 14:54:21 +0800   Mon, 27 Aug 2018 10:03:23 +0800   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False     Fri, 12 Oct 2018 14:54:21 +0800   Mon, 27 Aug 2018 10:03:23 +0800   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False     Fri, 12 Oct 2018 14:54:21 +0800   Mon, 27 Aug 2018 10:03:23 +0800   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False     Fri, 12 Oct 2018 14:54:21 +0800   Mon, 20 Aug 2018 19:05:38 +0800   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True      Fri, 12 Oct 2018 14:54:21 +0800   Mon, 27 Aug 2018 10:03:33 +0800   KubeletReady                 kubelet is posting ready status. AppArmor enabled
```
But how do I undo these conditions for all Nodes?

**Comment by andyxning** [comment]
@Lynzabo For now, i have no good idea about delete the NPD conditions from node conditions. You could patch the node with the deleted/cleaned node condition, IMHO. This is also what kubelet does when updating the node condition.

But you need first stop all NPD instances.

**Comment by Lynzabo** [comment]
@andyxning 
"You could patch the node with the deleted/cleaned node condition, IMHO. This is also what kubelet does when updating the node condition."

**Comment by Lynzabo** [comment]
@andyxning I didn't understand what you mean, how should I clean up the conditions? Thanks~

**Comment by wangzhen127** [comment]
@Lynzabo, node conditions are part of node status, you can just patch the node with the conditions you want to keep. See https://kubernetes.io/docs/reference/kubectl/cheatsheet/#patching-resources for examples.

/close

**Comment by sphr2k** [comment]
Just in case someone else comes here looking for a way to clear orphaned conditions created by node-problem-detector. As far as I understand, it's not possible to patch these using kubectl. I used a plugin called [kubectl-edit-status](https://github.com/ulucinar/kubectl-edit-status) that allows editing of editing of `/status` subresources.
