### ISSUE TITLE
Journald plugin not resetting condition after condition clears

### ISSUE THREAD

**Issue by byxorna** [kubernetes/node-problem-detector#215]
It is unclear to me (by docs, and spelunking through the code) how to use a non-custom plugin (i.e. `journald`) to set permanent Conditions on a node. For example, with the following configuration, once a pattern triggers the condition to go to `reason=KubenetIPAllocationFailure`, there is no way to "timeout" or reset to healthy after N seconds.

It seems like this plugin has no notion of a "clear state", where the condition can be no longer true. Is this by design?

```
{
  "plugin": "journald",
  "pluginConfig": {
    "source": "kubelet"
  },
  "logPath": "/run/log/journal",
  "lookback": "5m",
  "bufferSize": 10,
  "source": "kubelet-monitor",
  "conditions": [
    {
      "type": "KubeletNetworking",
      "reason": "Healthy",
      "message": "kubelet is functioning properly"
    }
  ],
  "rules": [
    {
      "type": "permanent",
      "condition": "KubeletNetworking",
      "reason": "KubenetIPAllocationFailure",
      "pattern": ".*NetworkPlugin kubenet failed to set up pod .*no IP addresses available in range.*"
    }
  ]
}
```

## Expected Behavior

Condition goes back to Healthy after a user-specified period of no triggering events.

## Actual Behavior

Condition stays in KubenetIPAllocationFailure forever.

**Comment by byxorna** [comment]
Hi @andyxning, do you have thoughts on this issue?

**Comment by byxorna** [comment]
@andyxning so, patching node manually is a non-starter for us. Any manual action taken in a system explicitly designed to remove operational burden and toil from infrastructure isnt a great solution.

Is it possible to add a "timeout" field for these events, such that the `node-problem-detector` keeps track of the frequency of these events, and will expire the condition after the timeout, if no more occurrences are seen?

i.e.
```
  "rules": [
    {
      "type": "permanent",
      "condition": "KubeletNetworking",
      "reason": "KubenetIPAllocationFailure",
      "pattern": ".*NetworkPlugin kubenet failed to set up pod .*no IP addresses available in range.*",
      "resolveAfter": "1h", // resolve back to KubeletNetworking = Healthy when no events seen within this window
    }
  ]
```

**Comment by byxorna** [comment]
@andyxning by node controller, do you mean the node controller in k8s core?

**Comment by andyxning** [comment]
@byxorna Yes, something like that. You can take a look at the [Draino](https://github.com/kubernetes/node-problem-detector#remedy-systems)

**Comment by Atoms** [comment]
We have added kernel monitor, and now i want to test it out, i add some problem as KernelDeadLock, node reports condition as True, so let's say i fixed that problem and i want that condition to reset, so i created script which patches node condition to False, but already 1hour it comes back as True, i also added lot of dummy lines in kernel log, but it still keeps setting it to True, as i see some lack of documentation (i readed code), i understand that 
bufferSize: 10 - will check last 10 lines of kernel log?
lookback: 5m - will check last 5 min of logs ?
if so, then why still after 1 hour that log is picked up and node condition is changed?

**Comment by negz** [comment]
I thought the idea behind a permanent node condition was that they were _permanent_. Put otherwise, if a condition could clear up at some future time I would not expect NPD to set a node condition in the first place but rather to emit a node event indicating a _temporary_ problem.

Draino, for example, assumes that once a node condition is set by NPD there are no possible remediations other than terminating and replacing the node.

**Comment by byxorna** [comment]
/remove-lifecycle stale

I have a similar experience to @Atoms.

The current behavior creates issues for people maintaining their own physical deployments of Kubernetes, where kubelet reprovisions are less frequent than bring up/down VMs in a cloud provider. The physical hardware lifecycle is not identical to cloud VM lifecycles, in that managed physical host may be brought down and back up for arbitrary maintenances (ToR maintenance, hardware upgrades, firmware patches, in-place kernel updates, etc). It is useful to allow an operator or automation to signal that a node is in a "maintenance" condition for hours/days, and then to remove that condition.

**Comment by grosser** [comment]
/reopen

also ran into this 😞

**Comment by grosser** [comment]
basically need a reoccurrenceTimeout so if it does not happen again within X min then clear it
