### ISSUE TITLE
NPD should detect when static pods are rejected by admission controller

### ISSUE THREAD

**Issue by mml** [kubernetes/node-problem-detector#216]
This is related to kubernetes#70499.

This is a class of bootstrapping problem that NPD should be able to report.

**Comment by andyxning** [comment]
@mml As of now, you can write a custom check plugin to do this job. As for now, node-problem-detector can support custom check plugin mechanism and end users can extend this to do whatever they want to check. Node-problem-detector has no example about checking whether static pods are rejected by admission controller. If it is possible for you, PR is welcomed. :)

As this is not a problem with NPD, closing this. @mml Feel free to reopen this once you still have some problems.
