### ISSUE TITLE
Getting log counter to work

### ISSUE THREAD

**Issue by ganeshvasudevan** [kubernetes/node-problem-detector#220]
Hi,

I am trying to use the log counter to work with default config file. With the default configuration files I don't see the log counter working as well as any logs about the initialisation or any extra logs that I added.

Is there some extra steps that need to be done to get the log counter to work? 
Could some one share working config as well as the plugin used?

_Ganesh

**Comment by wangzhen127** [comment]
Currently all log counter configurations should work ([kernel-monitor-counter.json](https://github.com/kubernetes/node-problem-detector/blob/master/config/kernel-monitor-counter.json), [systemd-monitor-counter.json](https://github.com/kubernetes/node-problem-detector/blob/master/config/systemd-monitor-counter.json), [docker-monitor-counter.json](https://github.com/kubernetes/node-problem-detector/blob/master/config/docker-monitor-counter.json)). 

You can take a look at https://github.com/kubernetes/kubernetes/pull/71522 (to be merged) to see how NPD is configured. To test, the READ file contains instructions on how to inject fake logs.

**Comment by wangzhen127** [comment]
/close
Closing this since log counter is working. Reopen if you still see problems.
