### ISSUE TITLE
plugin “filelog” :unable to parse line: "time=\xxxxxxxx\"

### ISSUE THREAD

**Issue by chen-joe1015** [kubernetes/node-problem-detector#226]
ERROR:
![image](https://user-images.githubusercontent.com/31652157/48963646-02909300-efd2-11e8-81b2-cf2da40d31c2.png)
CONFIG:
![image](https://user-images.githubusercontent.com/31652157/48963650-1fc56180-efd2-11e8-8a35-d5efe615f36e.png)
 thanks

**Comment by wangzhen127** [comment]
@chen-joe1015, I think you need to change your timestampFormat to `2006-01-02T15:04:05-07:00`.

**Comment by chen-joe1015** [comment]
Thanks! This information is just an alarm and does not affect the work of the main process.

**Comment by chen-joe1015** [comment]
Thanks! This information is just an alarm and does not affect the work of the main process.
