### ISSUE TITLE
v0.6.0 not available on k8s.gcr.io

### ISSUE THREAD

**Issue by Hashfyre** [kubernetes/node-problem-detector#230]
The newest release has not yet been published to k8s.gcr.io, is there an ETA to the process?
Was hoping to try out `docker-monitor-counter.json` for overlay2 corruption detection.

```
> docker pull k8s.gcr.io/node-problem-detector:v0.6.0
Error response from daemon: manifest for k8s.gcr.io/node-problem-detector:v0.6.0 not found
```

May I know was this missed or it's part of the release timeline that I have to wait for.

**Comment by Random-Liu** [comment]
It is pushed to staging-k8s.gcr.io/node-problem-detector:v0.6.0

A process is needed to graduate to `k8s.gcr.io`. I'll do that.

**Comment by Random-Liu** [comment]
The image `0.6.1` is ready now.

```
docker pull k8s.gcr.io/node-problem-detector:v0.6.1
v0.6.1: Pulling from node-problem-detector
Digest: sha256:cecdcebc9cf0a84ef92376c11ca6ba4af0413246529698e4cd868691a9398873
Status: Downloaded newer image for k8s.gcr.io/node-problem-detector:v0.6.1
```

**Comment by Hashfyre** [comment]
Thanks so much.
