### ISSUE TITLE
Journald plugin not working on 0.6.1

### ISSUE THREAD

**Issue by Atoms** [kubernetes/node-problem-detector#232]
Tried to deploy 0.6.1 version, and kernel-monitor with journald plugin fails with message:
```
E1129 09:42:51.150454       1 problem_detector.go:64] Failed to start log monitor "/config/kernel-monitor.json": failed to create journal client from path "/var/log/journal/": unable to open a handle to the library
```
downgraded to 0.5.0 and it works, cannot verify on 0.6.0 as image is not available.

**Comment by Random-Liu** [comment]
Hm, it is caused by this. https://github.com/kubernetes/kubernetes/commit/8906d1d8beb9335c438d3d093a064512b901e61c#diff-c3d7736ae9d9e127bf38b48bbd213144

**Comment by ixdy** [comment]
if you need systemd, add it back into the node-problem-detector image when you build it?

**Comment by Random-Liu** [comment]
@ixdy Did that in #233. Thanks!
