### ISSUE TITLE
NPD is lack of k8s cluster level e2e test coverage

### ISSUE THREAD

**Issue by wangzhen127** [kubernetes/node-problem-detector#236]
We should add k8s cluster level e2e test coverage for NPD, so that situations like #227 could be prevented. There were past effort #43 and #86, but those never got completed. It is time to revisit.

**Comment by andyxning** [comment]
Seems that presubmit e2e test needs to work with test-infra.

**Comment by wangzhen127** [comment]
Just for reference:
- Existing [NPD node e2e test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/node_problem_detector_linux.go) running on [sig-node-kubelet](https://k8s-testgrid.appspot.com/sig-node-kubelet#node-kubelet-features) and [sig-node-containerd](https://k8s-testgrid.appspot.com/sig-node-containerd#node-e2e-features) testgrid dashboards.
- Past attempt on adding NPD cluster e2e test: https://github.com/kubernetes/kubernetes/pull/42454

**Comment by wangzhen127** [comment]
NPD presubmit and CI jobs are now available:
- presubmit: https://k8s-testgrid.appspot.com/presubmits-node-problem-detector
- CI: https://k8s-testgrid.appspot.com/sig-node-node-problem-detector

Will cherry pick the following PRs into k8s 1.11, 1.12, and 1.13 branches:
- https://github.com/kubernetes/kubernetes/pull/73288
- https://github.com/kubernetes/kubernetes/pull/74922 (test fix)
- https://github.com/kubernetes/kubernetes/pull/75063 (test fix)

**Comment by wangzhen127** [comment]
https://github.com/kubernetes/kubernetes/pull/73288 will be available in Kubernetes v1.11.10+, v1.12.8+, and v1.13.6+.
