### ISSUE TITLE
Please add documentation for the possible fields in plugins

### ISSUE THREAD

**Issue by eatwithforks** [kubernetes/node-problem-detector#237]
i'm getting confused by the multiple timeouts and what exactly concurrency means.

**Comment by andyxning** [comment]
@eatwithforks IIUC, you mean about custom plugin configurations?

**Comment by andyxning** [comment]
@eatwithforks Could you explain what confused you mostly?

**Comment by andyxning** [comment]
One drawback of using json format configuration is comment less. We can not add any comment into the configuration easily and clearly.
