### ISSUE TITLE
Has this been tested on Azure Kubernetes Service

### ISSUE THREAD

**Issue by dazdaz** [kubernetes/node-problem-detector#241]
Hi,

Has this been tested on Microsoft's Azure Kubernetes Service, Kubernetes v1.11.5  and did all of the features work as expected ?

**Comment by andyxning** [comment]
@dazdaz 

> Has this been tested on Microsoft's Azure Kubernetes Service?
I can not tell the truth since not all use cases are feedback. If you have some interest to run NPD on AKS, we would be pleased to receive some feedback or problems. :)

> Kubernetes v1.11.5
The answer is unknow, either. We have not received any feedback upon Kubernetes 1.11.5

> did all of the features work as expected?
Absolutely yes.
