### ISSUE TITLE
helm install stable/node-problem-detector Error: 

### ISSUE THREAD

**Issue by oscarwest** [kubernetes/node-problem-detector#242]
Azure AKS

kubectl version
`
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
`

helm repo list
`
NAME         	URL
stable       	https://kubernetes-charts.storage.googleapis.com
local        	http://127.0.0.1:8879/charts
azure-samples	https://azure-samples.github.io/helm-charts/
`

helm version
`
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
`

helm install..
`
west@Oscars-MBP:~/scripts/azure|⇒  helm install stable/node-problem-detector
Error: release washing-bronco failed: DaemonSet.apps "washing-bronco-node-problem-detector" is invalid: spec.template.spec.containers[0].imagePullPolicy: Unsupported value: "<nil>": supported values: "Always", "IfNotPresent", "Never"
`

**Comment by Hashfyre** [comment]
You need:
```
image:
  repository: k8s.gcr.io/node-problem-detector
  tag: v0.6.1
  pullPolicy: IfNotPresent
```
in your `values .yml`

**Comment by andyxning** [comment]
Since this has been answered by @Hashfyre in https://github.com/kubernetes/node-problem-detector/issues/242#issuecomment-448977959. Close this.

/close
