### ISSUE TITLE
Crashloopbackoff on v.0.6.1 with *-counter.json

### ISSUE THREAD

**Issue by Hashfyre** [kubernetes/node-problem-detector#243]
Env:
 - AWS + Kops
 - Ubuntu-16.04 hosts
 - Deployed with
`helm upgrade --install node-problem-detector -f node-problem-detector/helm/values/dev/values.yaml --version '1.0' --namespace=kube-system stable/node-problem-detector`
 - values:
```
---
settings:
  log_monitors:
    - /config/abrt-adaptor.json
    - /config/docker-monitor.json
    - /config/docker-monitor-filelog.json
    - /config/docker-monitor-counter.json
    - /config/kernel-monitor.json
    - /config/kernel-monitor-filelog.json
    - /config/kernel-monitor-counter.json
    - /config/network-problem-monitor.json
    - /config/systemd-monitor-counter.json

image:
  repository: k8s.gcr.io/node-problem-detector
  tag: v0.6.1
  pullPolicy: IfNotPresent

nameOverride: "node-problem-detector"
fullnameOverride: "node-problem-detector"

rbac:
  create: true

resources: {}

annotations:
  sidecar.istio.io/inject: "false"

tolerations:
  - effect: NoSchedule
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "node-problem-detector"

affinity: {}

```
Logs:
```
I1221 12:13:10.771074       1 log_monitor.go:64] Finish parsing log monitor config file: {WatcherConfig:{Plugin:journald PluginConfig:map[source:abrt-notification] LogPath:/var/log/journal Lookback:5m Delay:} BufferSize:10 Source:abrt-adaptor DefaultConditions:[] Rules:[{Type:temporary Condition: Reason:CCPPCrash Pattern:Process \d+ \(\S+\) crashed in .*} {Type:temporary Condition: Reason:UncaughtException Pattern:Process \d+ \(\S+\) of user \d+ encountered an uncaught \S+ exception} {Type:temporary Condition: Reason:XorgCrash Pattern:Display server \S+ crash in \S+} {Type:temporary Condition: Reason:VMcore Pattern:System encountered a fatal error in \S+} {Type:temporary Condition: Reason:Kerneloops Pattern:System encountered a non-fatal error in \S+}]}
I1221 12:13:10.771124       1 log_watchers.go:40] Use log watcher of plugin "journald"
I1221 12:13:10.771202       1 log_monitor.go:64] Finish parsing log monitor config file: {WatcherConfig:{Plugin:journald PluginConfig:map[source:dockerd] LogPath:/var/log/journal Lookback:5m Delay:} BufferSize:10 Source:docker-monitor DefaultConditions:[] Rules:[{Type:temporary Condition: Reason:CorruptDockerImage Pattern:Error trying v2 registry: failed to register layer: rename /var/lib/docker/image/(.+) /var/lib/docker/image/(.+): directory not empty.*}]}
I1221 12:13:10.771215       1 log_watchers.go:40] Use log watcher of plugin "journald"
I1221 12:13:10.771281       1 log_monitor.go:64] Finish parsing log monitor config file: {WatcherConfig:{Plugin:filelog PluginConfig:map[message:msg="([^
]*)" timestampFormat:2006-01-02T15:04:05.999999999-07:00 timestamp:^time="(\S*)"] LogPath:/var/log/docker.log Lookback:5m Delay:} BufferSize:10 Source:docker-monitor DefaultConditions:[] Rules:[{Type:temporary Condition: Reason:CorruptDockerImage Pattern:Error trying v2 registry: failed to register layer: rename /var/lib/docker/image/(.+) /var/lib/docker/image/(.+): directory not empty.*}]}
I1221 12:13:10.771294       1 log_watchers.go:40] Use log watcher of plugin "filelog"
F1221 12:13:10.771364       1 log_monitor.go:56] Failed to unmarshal configuration file "/config/docker-monitor-counter.json": json: cannot unmarshal number into Go struct field MonitorConfig.pluginConfig of type string
```

**Comment by Hashfyre** [comment]
most monitors with `*-counter` suffix fails with the same unmarshalling error.
```
F1221 12:26:33.696942       1 log_monitor.go:56] Failed to unmarshal configuration file "/config/systemd-monitor-counter.json": json: cannot unmarshal number into Go struct field MonitorConfig.pluginConfig of type string
```
Leads me to suspect this has something to do with the stable helm chart not configuring something correctly.

**Comment by Hashfyre** [comment]
Could the issue be with non-quoted numerics in the said JSONs?
```
https://github.com/kubernetes/node-problem-detector/blob/master/config/systemd-monitor-counter.json#L6
```

**Comment by andyxning** [comment]
Actually all *-counter plugins are custom plugins. I suspect that you have configured wrongly.

**Comment by Hashfyre** [comment]
@andyxning I'm using the official helm-chart, I'll take your point into account and check my config.

**Comment by Hashfyre** [comment]
Tried running 
```
    - /config/docker-monitor-counter.json
```
with --custom-plugin-monitors flag. 
Fails with:
```
F0107 11:18:40.816070       1 custom_plugin_monitor.go:64] Failed to validate custom plugin config {Plugin:custom PluginGlobalConfig:{InvokeIntervalString:0xc0002933c0 TimeoutString:0xc0002933d0 InvokeInterval:5m0s Timeout:1m0s MaxOutputLength:0xc000133728 Concurrency:0xc000133738} Source:docker-monitor DefaultConditions:[{Type:CorruptDockerOverlay2 Status: Transition:0001-01-01 00:00:00 +0000 UTC Reason:NoCorruptDockerOverlay2 Message:docker overlay2 is functioning properly}] Rules:[0xc00038d2d0]}: rule path "/home/kubernetes/bin/log-counter" does not exist. Rule: &{Type:permanent Condition:CorruptDockerOverlay2 Reason:CorruptDockerOverlay2 Path:/home/kubernetes/bin/log-counter Args:[--journald-source=dockerd --log-path=/var/log/journal --lookback=5m --count=10 --pattern=returned error: readlink /var/lib/docker/overlay2.*: invalid argument.*] TimeoutString:0xc000293420 Timeout:1m0s}
```

**Comment by Hashfyre** [comment]
The type error persists:
```
Condition: Reason:KernelOops Pattern:BUG: unable to handle kernel NULL pointer dereference at .*} {Type:temporary Condition: Reason:KernelOops Pattern:divide error: 0000
```

**Comment by dashpole** [comment]
I don't think NPD has an official helm chart...  Do we know who owns it?

**Comment by andyxning** [comment]
> I don't think NPD has an official helm chart... Do we know who owns it?

Actually we do have an official helm chart in https://github.com/helm/charts/tree/master/stable/node-problem-detector. It is referenced in https://github.com/kubernetes/node-problem-detector/pull/217. It is owned by @max-rocket-internet

**Comment by andyxning** [comment]
@Hashfyre Has you resolved this Problem?

**Comment by max-rocket-internet** [comment]
Yes, I created the PR to get the chart added to the main charts repo. But if others from here want to be added to the approvers/reviewers then just make a PR 🙂

**Comment by Hashfyre** [comment]
@andyxning no, I'm still trying to understand the root-cause.

**Comment by Hashfyre** [comment]
As of now, the `*-counter.json` configs do not run with either:
`--system-log-monitors` or `--custom-plugin-monitor` flags, resulting in an Error and subsequent `CrashLoopBackoff`

**Comment by Hashfyre** [comment]
Hi, I'm happy to understand the problem and make a PR to fix this if someone's willing to guide me.

**Comment by clux** [comment]
It might be something missing in the image judging by logs, if you use the stable chart by setting:

```yaml
settings:
  custom_monitor_definitions:
    systemd-monitor-counter.json: |
      # full indented json here

  custom_plugin_monitors:
    - /custom-config/systemd-monitor-counter.json
```
([actual json for the file](https://github.com/kubernetes/node-problem-detector/blob/master/config/systemd-monitor-counter.json))

the containers crash in validation stage, not marshalling:


> F0320 15:30:04.093755       1 custom_plugin_monitor.go:64] Failed to validate custom plugin config {Plugin:custom PluginGlobalConfig:{InvokeIntervalString:0xc0002b7a90 TimeoutString:0xc0002b7aa0 InvokeInterval:5m0s Timeout:1m0s MaxOutputLength:0xc000296cb8 Concurrency:0xc000296cc8} Source:systemd-monitor DefaultConditions:[{Type:FrequentKubeletRestart Status: Transition:0001-01-01 00:00:00 +0000 UTC Reason:NoFrequentKubeletRestart Message:kubelet is functioning properly} {Type:FrequentDockerRestart Status: Transition:0001-01-01 00:00:00 +0000 UTC Reason:NoFrequentDockerRestart Message:docker is functioning properly} {Type:FrequentContainerdRestart Status: Transition:0001-01-01 00:00:00 +0000 UTC Reason:NoFrequentContainerdRestart Message:containerd is functioning properly}] Rules:[0xc00033ec40 0xc00033ed90 0xc00033ee00]}: rule path "/home/kubernetes/bin/log-counter" does not exist. Rule: &{Type:permanent Condition:FrequentKubeletRestart Reason:FrequentKubeletRestart Path:/home/kubernetes/bin/log-counter Args:[--journald-source=systemd --log-path=/var/log/journal --lookback=20m --delay=5m --count=5 --pattern=Started Kubernetes kubelet.] TimeoutString:0xc0002b7ae0 Timeout:1m0s}

`"/home/kubernetes/bin/log-counter" does not exist.`

**Comment by neoakris** [comment]
Hope this helps, It's working for me in v0.6.3: 
my node-problem-detector.values.yaml    helm chart override file uses image v0.6.3

When I had 
  log_monitors:
   - /config/kernel-monitor-counter.json
   - /config/docker-monitor-counter.json
  custom_plugin_monitors: []
I'd get crashloop backoff with pod log saying
Error: "Failed to unmarshal configuration file "/config/kernel-monitor-counter.json""
Error: "Failed to unmarshal configuration file "/config/docker-monitor-counter.json""

I switched it to:
 log_monitors: []
 custom_plugin_monitors: 
   - /config/kernel-monitor-counter.json
   - /config/docker-monitor-counter.json

and it worked as expected.
