### ISSUE TITLE
Should Ready condition change if other condition states are False?

### ISSUE THREAD

**Issue by gtorre** [kubernetes/node-problem-detector#252]
```
Conditions:
  Type                          Status  LastHeartbeatTime                 LastTransitionTime                Reason                          Message
  ----                          ------  -----------------                 ------------------                ------                          -------
  **IsChainsed                  True    Tue, 27 Mar 2018 14:09:31 -0400   Tue, 27 Mar 2018 14:09:30 -0400   Chainsed                        Node is chainsed
  KernelDeadlock                False   Thu, 24 Jan 2019 15:32:05 -0500   Tue, 04 Dec 2018 15:44:07 -0500   KernelHasNoDeadlock             kernel has no deadlock
  OutOfDisk                     False   Thu, 24 Jan 2019 17:25:54 -0500   Mon, 05 Mar 2018 18:07:06 -0500   KubeletHasSufficientDisk        kubelet has sufficient disk space available
  MemoryPressure                False   Thu, 24 Jan 2019 17:25:54 -0500   Fri, 06 Jul 2018 02:08:40 -0400   KubeletHasSufficientMemory      kubelet has sufficient memory available
  DiskPressure                  False   Thu, 24 Jan 2019 17:25:54 -0500   Fri, 06 Jul 2018 02:08:40 -0400   KubeletHasNoDiskPressure        kubelet has no disk pressure
  Ready                         True    Thu, 24 Jan 2019 17:25:54 -0500   Thu, 24 Jan 2019 17:23:11 -0500   KubeletReady                    kubelet is posting ready status
  FrequentUnregisterNetDevice   False   Thu, 24 Jan 2019 17:25:14 -0500   Thu, 24 Jan 2019 17:22:26 -0500   NoFrequentUnregisterNetDevice   node is functioning properly
  PIDPressure                   False   Thu, 24 Jan 2019 17:25:54 -0500   Tue, 16 Oct 2018 13:56:40 -0400   KubeletHasSufficientPID         kubelet has sufficient PID available
```

We wrote a custom plugin under the impression that if the plugin returned a 1 exit code, it would make the node unavailable for scheduling. However, since the Ready condition never updates to False, pods continue to be scheduled on the kubelet.

Is the expectation that any `permanent` problems would trigger the Ready state to become false? Or this assumption wrong?

**Comment by fabiand** [comment]
I actually wonder how one condition can impact the Ready condition.

My thought would have been to let NFD set a taint NoSchedule under certain
conditions.

**Comment by rrs45** [comment]
Conditions (type:permanent) set by NPD are not watched by controller-manager so no action is taken automatically. You may need custom controller to read and act when those conditions becomes true

**Comment by multi-io** [comment]
In that note, how would you even set a condition to false rather than true if an incident occurs? [It looks like](https://github.com/kubernetes/node-problem-detector/blob/ee103dd4acc612102766254629d570d2b4bdb28c/pkg/systemlogmonitor/log_monitor.go#L152) npd can only set it to true no matter what.

**Comment by wangzhen127** [comment]
> Is the expectation that any permanent problems would trigger the Ready state to become false?

No.

> On that note, how would you even set a condition to false rather than true if an incident occurs?

For built-in monitor, that is by design. For custom plugin, you have a way to set the condition back to false. You can see the discussions in https://github.com/kubernetes/node-problem-detector/issues/215.
