### ISSUE TITLE
Allow multiple rules to be combined into single condition

### ISSUE THREAD

**Issue by rrs45** [kubernetes/node-problem-detector#255]
Often times we have multiple checks which can be grouped together into one condition. And it would be ideal if that condition would reflect only those checks which failed.

Currently, if a 'permanent' rule type is defined in the config then it appears in the 'conditions' field when using 'kubectl describe node', forever. It shows up even when we no longer need that check and the conditions keep growing as we add/remove such rule types. This is very inflexible.

For example, we want to monitor sensu check failures and report them as a node condition. We only want to see which of those checks failed as a single condition.

For this, we need:
1.  A way to aggregate multiple rules into a group and create a single condition which becomes true when any of the rules( within the group ) gets triggered. And becomes false when none of them gets triggered
2. Dynamically update 'Message' field of the condition by combining results from only those rules   which get triggered.

**Comment by wangzhen127** [comment]
You probably need to use custom plugin to suit your needs.
