### ISSUE TITLE
Detect clock skew vs the master or some other central source

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/node-problem-detector#26]
The master depends on itself having a similar view of time as the Nodes, and the controller manager will not properly roll out deployments if the node and master clocks are skewed.  We should figure out a way of detecting this condition.

**Comment by janetkuo** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/29229

**Comment by Random-Liu** [comment]
The clock skew issue should have been handled in https://github.com/kubernetes/kubernetes/issues/6159.

It is really hard for the node problem detector to detect the clock skew. It has to do similar thing with what ntpd does. :)
