### ISSUE TITLE
shell script execution is too slow 

### ISSUE THREAD

**Issue by ringtail** [kubernetes/node-problem-detector#266]
I want to create a custom shell script as plugin. but `ls`,`wc`,`find` are too slow. so what's the best practice to create a shell plugin.

**Comment by wangzhen127** [comment]
Custom plugin allows executing arbitrary binary. If shell script cannot satisfy your needs, you can consider types of programming languages.

**Comment by iranzo** [comment]
@ringtail it depends a lot on what you're trying to implement, for example, I had to move several tests in another tool from 'awk' to grep and then to awk on the results because of 'grep' speed vs 'awk' for finding some regexps

**Comment by ringtail** [comment]
> @ringtail it depends a lot on what you're trying to implement, for example, I had to move several tests in another tool from 'awk' to grep and then to awk on the results because of 'grep' speed vs 'awk' for finding some regexps

Yes. I agree.

**Comment by iranzo** [comment]
Do you have any example of the issue? I've checked many script at https://github.com/citellusorg/citellus/ for doing issue detection and would see what you're trying to accomplish :-) thanks!
