### ISSUE TITLE
Allow reading a kubeconfig file for master / auth info

### ISSUE THREAD

**Issue by yuvipanda** [kubernetes/node-problem-detector#27]
This would allow it to be used with clusters that don't have service accounts enabled (they are disabled in our cluster because they do not play well with namespaced accounts yet)

**Comment by Random-Liu** [comment]
@yuvipanda Sorry for the delay.

We'll probably address this in https://github.com/kubernetes/node-problem-detector/pull/49.

**Comment by Random-Liu** [comment]
Close this one since #49 is merged. Please take look at the newly introduced `--apiserver-override` flag.
