### ISSUE TITLE
Does NPD have a ROADMAP?

### ISSUE THREAD

**Issue by allencloud** [kubernetes/node-problem-detector#273]
Hi, NPD community,

In k8s, npd could take over all the node monitoring, which is quite useful for cluster at large scale. We are trying to adopt npd in our production enviroment and contribute back to it. I am wondering if NPD project has a ROADMAP document to share the future work of it.

Thanks.

Allen Sun
Alibaba Cloud

**Comment by wangzhen127** [comment]
There is no formal roadmap doc. The recent planned big change is to enable NPD to export metrics. You can follow up the design here: https://docs.google.com/document/d/1SeaUz6kBavI283Dq8GBpoEUDrHA2a795xtw0OvjM568/.
