### ISSUE TITLE
NodeProblemDetector tests failing on AWS

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/node-problem-detector#28]
https://github.com/kubernetes/node-problem-detector/blob/9ab546a2e23613c51e51af7a109952a6079e0651/pkg/problemclient/problem_client.go#L61 assumes that the hostname is the same name as the cloud provider instance name. This is false on AWS. NPD needs to be going through `CurrentNodeName` to get the cloud provider agnostic hostname.

I'm disabling this test on AWS for now, but we're marching towards full support for AWS. Please treat this as if it had broken a build when it was checked in originally.

**Comment by zmerlynn** [comment]
cc @justinsb

**Comment by zmerlynn** [comment]
I'm not sure I agree that this is an `enhancement`, unless the original design was for GCE images/kernels only.

**Comment by Random-Liu** [comment]
@zmerlynn Ha, no other labels in this repo except bug. :)
The best way for now should be using the downward api https://github.com/kubernetes/kubernetes/pull/27880, which is mentioned in the issue https://github.com/kubernetes/node-problem-detector/issues/25.

I'll ask whether we can get https://github.com/kubernetes/kubernetes/pull/27880 in any time soon. If so, we can switch to using it quite soon, if not, I'll think some other ways.

**Comment by zmerlynn** [comment]
I forgot to reopen the bug, but the NPD tests never actually started passing on AWS. I'll look into it soon.

**Comment by Random-Liu** [comment]
This should be solved once https://github.com/kubernetes/kubernetes/pull/35740 is merged.

@dchen1107

**Comment by Random-Liu** [comment]
Close this issue because kubernetes/kubernetes#35740 has been merged. Feel free to reopen if the issue happens again.
