### ISSUE TITLE
Add e2e test for NPD metric-only mode

### ISSUE THREAD

**Issue by xueweiz** [kubernetes/node-problem-detector#296]
Today, NPD has two test pipelines: [CI](https://github.com/kubernetes/test-infra/blob/83ebd1d386d3c6c67c2b28bfd3f7ecf8292f2814/config/jobs/kubernetes/node-problem-detector/node-problem-detector-ci.yaml) and [presubmits](https://github.com/kubernetes/test-infra/blob/83ebd1d386d3c6c67c2b28bfd3f7ecf8292f2814/config/jobs/kubernetes/node-problem-detector/node-problem-detector-presubmits.yaml).

In both cases, they are essentially running unit tests (`make test`) and k8s e2e test (`kubernetes_e2e.py ... --ginkgo.focus=NodeProblemDetector`).

We should add more NPD-focused tests to ensure it does not regress. And many of them are best done from e2e tests, e.g.:

- Trigger/simulate failures (`kill -9 [docker]`, `echo c > /proc/sysrq-trigger`, `stress --vm 2 --vm-bytes 128M --timeout 120s`, `echo "OOM" > /dev/kmsg`, etc), and see if NPD can correctly behave under the situation.

- Performance test. e.g. write a busy program spamming "OOM" to `/dev/kmsg`, and see if NPD's CPU usage is capped. (We could use cgroup to limit NPD's usage to make the test pass)

- Soak test. e.g. Let NPD run for ~5 days, then see if it has an expanded memory footprint.

Obviously, these tests are best done in e2e tests, rather than unit test. Also, I think we should do the tests on standalone machines, rather than in a k8s cluster. Because the test should focus on node-level behavior, rather than cluster-level.

Action items:

- [ ] Add basic logistic e2e test to ensure NPD reports some expected Prometheus metrics and Stackdriver metrics: https://github.com/kubernetes/node-problem-detector/pull/323, https://github.com/kubernetes/node-problem-detector/pull/352
- [ ] Add performance e2e test to ensure NPD can handles medium/large log volume:
- [ ] Setup CI jobs in Prow to run NPD e2e tests on different distros (cos-73-lts, cos-77-lts, ubuntu-1804-lts): https://github.com/kubernetes/node-problem-detector/pull/349, #353, https://github.com/kubernetes/test-infra/pull/14372, https://github.com/kubernetes/test-infra/pull/14375, https://github.com/kubernetes/test-infra/pull/14376, https://github.com/kubernetes/test-infra/pull/14408
- [ ] Add presubmit jobs in Prow to run NPD e2e tests on cos-73-lts, cos-77-lts, ubuntu-1804-lts:

- [ ] Add soak test to ensure NPD's memory footprint stays stable after 1 day:
- [ ] Add a CI job in Prow to continuously run the soak test:

**Comment by xueweiz** [comment]
I was trying to find a library to help with SSHing and running commands in the VM.
I was experimenting with `k8s.io/kubernetes/test/e2e/framework/ssh`, but I cannot get it to work.

See the experiment code at https://github.com/xueweiz/node-problem-detector/blob/ssh-do-not-work/test/e2e_standalone/simple_test.go#L8

If you remove the `k8s.io/kubernetes/test/e2e/framework/ssh` import and usage, the test will run. But if we keep it, I will get an error:

```
xueweiz@xueweiz:~/.gvm/pkgsets/go1.11/global/src/k8s.io/node-problem-detector/test/e2e_standalone$ go test simple_test.go 
/tmp/go-build848136485/b001/books.test flag redefined: ginkgo.seed
panic: /tmp/go-build848136485/b001/books.test flag redefined: ginkgo.seed

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000521e0, 0x14b92a0, 0x20a8100, 0xc00060e000, 0xb, 0x1374521, 0x2a)
	/usr/local/google/home/xueweiz/.gvm/gos/go1.11/src/flag/flag.go:805 +0x529
flag.(*FlagSet).Int64Var(0xc0000521e0, 0x20a8100, 0xc00060e000, 0xb, 0x5d116df3, 0x1374521, 0x2a)
	/usr/local/google/home/xueweiz/.gvm/gos/go1.11/src/flag/flag.go:630 +0x71
k8s.io/node-problem-detector/vendor/github.com/onsi/ginkgo/config.Flags(0xc0000521e0, 0xc000463e78, 0x7, 0x1217801)
	/usr/local/google/home/xueweiz/.gvm/pkgsets/go1.11/global/src/k8s.io/node-problem-detector/vendor/github.com/onsi/ginkgo/config/config.go:68 +0x112
k8s.io/node-problem-detector/vendor/github.com/onsi/ginkgo.init.0()
	/usr/local/google/home/xueweiz/.gvm/pkgsets/go1.11/global/src/k8s.io/node-problem-detector/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:55 +0x59
FAIL	command-line-arguments	0.174s
```

I guess this is because the `k8s.io/kubernetes/test/e2e/framework/ssh` is not designed to be a generic library, and has a dependency with its vendored ginkgo. While my test is using my own vendored ginkgo. Probably the two ginkgo library are defining the .seed flag twice, and triggering this issue.

I think I'll stop trying to use the libraries from `k8s.io/kubernetes/test/e2e/framework`, as they should really be used in k8s-e2e test's context.

**Comment by wangzhen127** [comment]
"Standalone" is a used word already, meaning NPD is running as a native process instead of as a container. So consider use another word to cover the case where NPD runs without k8s API server. Maybe "metrics-only mode" (or something else)? After you decide, you can add that to README, so everyone knows.

**Comment by xueweiz** [comment]
SG. Let's call it "metrics-only" mode.

**Comment by xueweiz** [comment]
I just setup a CI job at https://github.com/kubernetes/test-infra/issues/14369. See test results at here:
https://k8s-testgrid.appspot.com/sig-node-node-problem-detector#ci-npd-e2e-test
https://prow.k8s.io/job-history/kubernetes-jenkins/logs/ci-npd-e2e-test

I see some flakes on the test:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-npd-e2e-test/1174205959015239684

There isn't any helpful error message. And I just figured out why:
So ginkgo defaults to set each `It()`/`BeforeEach()` with a 10 minutes timeout. And when we create a GCE VM, we retry to SSH to it with a 10 minutes timeout: https://github.com/kubernetes/node-problem-detector/blob/9828ab7f06709933538c91120cc13b73f18102c5/test/e2e/lib/gce/instance.go#L99-L102

Until the retry finish (either succeed or fail), the test code doesn't report the error. So eventually it results in that the 10 minute test timeout will come in first and kill the test without giving it a chance to report error.

I will make a PR to reduce the SSH retry timeout, and that should give us some error message next time the flake happens.

**Comment by xueweiz** [comment]
The test has been running good now :) Except for occasional timeout.

We can consider add them as part of presubmit now.
![image](https://user-images.githubusercontent.com/15825828/70655688-89300680-1c0d-11ea-9807-2e5926e1b85f.png)

This will help catch NPD regressions, and will ease the debugging of occasional timeout.
