### ISSUE TITLE
KernelMonitor: Reconsider whether to use hpcloud/tail

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/node-problem-detector#3]
For move fast as soon as possible, we used https://github.com/hpcloud/tail for the first version.
However, in fact it has been proved to have some bugs, such as https://github.com/hpcloud/tail/issues/21.

We should reconsider whether we should try to fix the bugs or implement a simple tail lib ourselves based on https://github.com/google/cadvisor/pull/1264.

**Comment by AdoHe** [comment]
@Random-Liu what do you think of this issue now? When I am adding journald support, I want to use log reader like cadvisor, but the tail library we use currently doesn't implement `io.Reader`, anything block use our simple tail lib?

**Comment by Random-Liu** [comment]
@AdoHe, as far as I know, we can just use the simple tail lib https://github.com/google/cadvisor/blob/master/utils/tail/tail.go.

**Comment by Random-Liu** [comment]
@AdoHe One thing is that, we run 2 functions when parsing kernel log:
* `getStartPoint`: This function was initially added to find the recent reboot line in the kernel log.
* `watchLoop`: After finding the reboot line, in side the `watchLoop`, `tail.Tail` is called with `start=head of the reboot line` to watch and parse the following log.

In this implementation, the tail lib needs to support watch from a specific point in the file, which is not supported in the simple tail library.

However, the logic was recently changed. We find start point based on timestamp ([`now-lookback`](https://github.com/kubernetes/node-problem-detector/blob/master/pkg/kernelmonitor/kernel_log_watcher.go#L166-L188)). In fact we can remove the function `getStartPoint` and combine the logic into watchLoop. When receiving a new log line:
* If it is older than `now-lookback`, discard it.
* If not, return translate and add the log line.

**Comment by AdoHe** [comment]
@Random-Liu Thanks very much.

**Comment by Random-Liu** [comment]
This should be closed after #39 got merged.
