### ISSUE TITLE
Host monitoring and self monitoring in NPD

### ISSUE THREAD

**Issue by xueweiz** [kubernetes/node-problem-detector#301]
Now that NPD can report metrics (#284 ), it's nice to report following useful information with the metrics reporting:

- NPD uptime and host uptime
- kernel version, host OS version
- NPD CPU/memory/net/filesystem usage

**Comment by wangzhen127** [comment]
Kernel version and host OS version seem to be metadata instead of metrics.

**Comment by xueweiz** [comment]
Correct, they will be reported as [OpenCensus metric tags](https://opencensus.io/tag/) (which will be shown as [Prometheus metric labels](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)).

In my current [prototype](https://github.com/xueweiz/node-problem-detector/blob/self/pkg/systemstatsmonitor/host_collector.go), they look like this:

```
$ curl http://localhost:20257/metrics
...
# HELP host_uptime The uptime of the operating system
# TYPE host_uptime gauge
host_uptime{kernel_version="4.19.37-2rodete1-amd64"} 687384

```
