### ISSUE TITLE
Node conditions status reset on problem detector restart.

### ISSUE THREAD

**Issue by eatwithforks** [kubernetes/node-problem-detector#304]
When node problem detector is restarted, all the node's conditions' status reset to False until the plugin's complete and resubmit the correct status. 

This means there is a gap where node conditions are all False when problem detector restarts, leading to false reports.

Is there a way to make problem detector not reset a node's conditions on restart?

**Comment by grosser** [comment]
`reset to False` -> `reset to their initial status`

**Comment by xueweiz** [comment]
One idea is to use the [`problemclient.Client.GetConditions()`](https://github.com/kubernetes/node-problem-detector/blob/146dfd70b25090203162b1e9eee305e76b688dff/pkg/exporters/k8sexporter/problemclient/problem_client.go#L81) function to retrieve condition's initial state upon NPD startup.

Basically each time when NPD starts up, it could call the `GetConditions()` function to determine what are the node conditions before NPD starts up. And use the result as the initial status for node conditions.

Would that work?

**Comment by eatwithforks** [comment]
sounds good, that would work.

**Comment by grosser** [comment]
only downside could be something like a log-status that then gets reset because the offending line is no longer in the log, but that's just a minor issue 🤷‍♂

**Comment by xueweiz** [comment]
/cc @andyxning 
Hi Andy, do you think the [idea above](https://github.com/kubernetes/node-problem-detector/issues/304#issuecomment-506883788) makes sense? If so, I'm happy to make a patch to implement it.

> only downside could be something like a log-status that then gets reset because the offending line is no longer in the log
True. But if that's the case (i.e. some problem daemon resets condition when it can no longer detect the permanent problem), then even if NPD is not restarted, it will still reset that condition eventually (when the log got deleted/rotated).
So, in my opinion, I think the reset behavior (feature-or-bug) is not in the scope of this issue. :P

Do you have any suggestions @grosser ?

**Comment by grosser** [comment]
Good enough if it does not resets it on restart 👍 
(also avoid the whole confusion with lastTransition getting updated when nothing actually happened)

**Comment by grosser** [comment]
@wangzhen127 got thoughts on this ? (since @andyxning seems to not be around)

**Comment by wangzhen127** [comment]
Are you referring to the log monitor? NPD resets the condition because in the config, it has the default condition. For example:
https://github.com/kubernetes/node-problem-detector/blob/master/config/kernel-monitor.json#L10
```
	"conditions": [
		{
			"type": "KernelDeadlock",
			"reason": "KernelHasNoDeadlock",
			"message": "kernel has no deadlock"
		},
		{
			"type": "ReadonlyFilesystem",
			"reason": "FilesystemIsNotReadOnly",
			"message": "Filesystem is not read-only"
		}
	],
```
The above line sets the default condition for `KernelDeadlock`.

In the code, this is done at:
https://github.com/kubernetes/node-problem-detector/blob/master/pkg/systemlogmonitor/log_monitor.go#L180
which reads and sets the default conditions.

I guess you can just remove the default conditions from the config for your use case.

**Comment by grosser** [comment]
That would mean the default condition will no longer appear when a new node comes up, right ?
We'd prefer the best of both: default is set when node is new, but does not override when updating ... especially does not override (bump lastTransitionAt) when it is already set to exactly that reason/status.

**Comment by wangzhen127** [comment]
That makes sense to me. Sounds good to me to make NPD check the conditions upon startup. @xueweiz and @grosser, I am happy to review your PR to fix this. :)

**Comment by grosser** [comment]
@xueweiz please make a PR if you can, if not I can try too but that might take a bit and be very clumsy :D

**Comment by xueweiz** [comment]
Hi @grosser , I'm happy to work on the PR :)
Sorry please let me submit #300 first. Because the initialization code of `system-log-monitor` is being changed a little bit in there. I'll wait for it to land, then work on this :)

**Comment by Random-Liu** [comment]
I think this is WAI initially for system log monitor.

If a node gets restarted, the problem is usually resolved. However, there is currently no way for system log monitor to set the condition back, so we always set the default condition when NPD comes up.

**Comment by grosser** [comment]
just to clarify: this is not about node restarting, but the detector itself crashing / getting restarted manually

**Comment by grosser** [comment]
also "for custom plugin we have a well-defined way to set conditions back", I'd want for the plugin to not reset on restart if no default condition is given ... but that's blocked by https://github.com/kubernetes/node-problem-detector/issues/306

**Comment by Random-Liu** [comment]
> just to clarify: this is not about node restarting, but the detector itself crashing / getting restarted manually

The problem is that NPD doesn't know whether it is process restart or node reboot. We can probably put some state into the `/run` directory to distinguish that.

**Comment by grosser** [comment]
I think if the "do not set condition when custom plugin does not define condition" would already mostly solve this too :)
https://github.com/kubernetes/node-problem-detector/issues/306
