### ISSUE TITLE
Inconsistent Event Reporting

### ISSUE THREAD

**Issue by honeybadger91** [kubernetes/node-problem-detector#305]
I'm experiencing an odd issue when attempting to utilize the "filelog" plugin. I have a fairly standard plugin config:

`{
	"plugin": "filelog",
	"pluginConfig": {
		"timestamp": "^.{32}",
		"message": "kernel: (.*)",
		"timestampFormat": "2006-01-02T15:04:05.999999+00:00"
	},
	"logPath": "/var/log/kern.log",
	"lookback": "5m",
	"bufferSize": 10,
	"source": "kernel-monitor",`

It seems to work on some nodes, but on others the event never fires. I echo the same string into /var/log/kern.log on two nodes, but only one reports and switches the condition properly.  Here's an example condition I'm looking for.

`		{
			"type": "permanent",
			"condition": "MCEHardwareErrors",
			"reason": "MCEHardwareErrorsFound",
			"pattern": "mce: \\[Hardware Error\\]: Machine check events logged"
		},`

Am I missing something? Logs aren't much help, everything seems fine. Any pointers on how to go about troubleshooting this?

**Comment by xueweiz** [comment]
Could you try running command `sync`  after `echo xx > /var/log/kern.log`? That will ensure the message is actually committed to the block device.
I want to make sure it's not some uncleared buffer issue. Thanks!

**Comment by honeybadger91** [comment]
Went ahead and tried, but same result. 

`echo "2019-06-28T23:02:04.020520+00:00 NODENAME kernel: mce: [Hardware Error]: Machine check events logged" >> /var/log/kern.log && sync `

**Comment by xueweiz** [comment]
Sorry Andrew, I'm not that familiar with the filelog plugin (I never used it).

I wonder if you can re-compile NPD and deploy it to your testing environment?
If you can, I'd suggest you add some print statements around these places:

1. To see whether `github.com/google/cadvisor/utils/tail` correct caught your log. 
https://github.com/kubernetes/node-problem-detector/blob/146dfd70b25090203162b1e9eee305e76b688dff/pkg/systemlogmonitor/logwatchers/filelog/log_watcher.go#L113

2. To see whether the log got reported to `systemlogmonitor`:
https://github.com/kubernetes/node-problem-detector/blob/146dfd70b25090203162b1e9eee305e76b688dff/pkg/systemlogmonitor/logwatchers/filelog/log_watcher.go#L135

3. To see whether the log correctly matched your regex (most likely yes):
https://github.com/kubernetes/node-problem-detector/blob/146dfd70b25090203162b1e9eee305e76b688dff/pkg/systemlogmonitor/log_monitor.go#L121

4. To see whether the `event` object is formed correctly:
https://github.com/kubernetes/node-problem-detector/blob/146dfd70b25090203162b1e9eee305e76b688dff/pkg/systemlogmonitor/log_monitor.go#L139

5. To see whether the k8s client is trying to report the event:
https://github.com/kubernetes/node-problem-detector/blob/146dfd70b25090203162b1e9eee305e76b688dff/pkg/exporters/k8sexporter/k8s_exporter.go#L61

That may help narrow down the problem.

**Comment by honeybadger91** [comment]
Ok, I will do this and get back to you. Thanks for your prompt responses.

**Comment by honeybadger91** [comment]
Due to time constraints, I went ahead and simply utilize the kmsg plugin instead of filelog. It is much more reliable. If I have some time, I will circle back to this and debug. Thanks again.
