### ISSUE TITLE
Custom plugins always show negative reason

### ISSUE THREAD

**Issue by grosser** [kubernetes/node-problem-detector#307]
For example this config:
```json
{
  "plugin": "custom",
  "pluginConfig": {
    "invoke_interval": "5m",
    "timeout": "60s",
    "max_output_length": 80,
    "concurrency": 1
  },
  "conditions": [
    {
      "type": "MyCondition",
      "reason": "PositiveReason",
      "message": "Docker Task count is normal"
    }
  ],
  "rules": [
    {
      "type": "permanent",
      "condition": "MyCondition",
      "reason": "NegativeReason",
      "path": "./config/plugin/my_condition.rb",
      "timeout": "60s"
    }
  ]
}
```

the plugin passes (can see that in the logs), and it shows the correct message, but it always shows the NegativeReason reason ... we were following the example https://github.com/kubernetes/node-problem-detector/blob/master/config/custom-plugin-monitor.json which uses the same positive/negative reason setup, but that does not seem to work.

Same goes for the events

```
  Normal  MyCondition  9m47s  , ip-xxx.ec2.internal            Node condition MyCondition is now: False, reason: NegativeReason
```

**Comment by grosser** [comment]
and if there is not fix, at least update the ntp example so nobody else runs into this problem 🤷‍♂

**Comment by wangzhen127** [comment]
Sounds like duplicated issues as #202, I am closing this one in favor of that.
