### ISSUE TITLE
json logging

### ISSUE THREAD

**Issue by grosser** [kubernetes/node-problem-detector#309]
would you accept a PR to make json logging the default or optional ? (or is there already an option for that ? )

```
31 plugin.go:65] Start to run custom plugins
31 plugin.go:91] Add check result {Rule:0xc00029eb60 ExitStatus:0 Message:Certificate expiration checks passing} for 31 plugin.go:96] Finish running custom plugins
```

->

```
{"severity":"INFO","message":"Start to run custom plugins"}
```

**Comment by Random-Liu** [comment]
@grosser I think an option to enable json logging is fine as long as it doesn't complex the code too much.

**Comment by grosser** [comment]
thx, we'll try to make a PR whenever we next have some play-time with go (if anyone else wants to take it, not problem though ;) )

**Comment by grosser** [comment]
FYI now using https://github.com/grosser/logrecycler that auto-parses the glog format emitted here + custom extraction of important metrics so we can alert on bad exit codes
