### ISSUE TITLE
Cut the v0.6 branch

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/node-problem-detector#310]
The latest NPD version is currently at 0.6.x, but we don't have a v0.6 branch so we should cut it.

Also, there has been several big refactorings and features recently merged into master. We should exclude them from v0.6. So let's create the branch based on https://github.com/kubernetes/node-problem-detector/commit/b454a42dbd15a80cc6e7e9778875077b114ddcba.

/assign @wangzhen127 
/cc @Random-Liu @andyxning

**Comment by wangzhen127** [comment]
Done

You will need to cherry pick you PR to v0.6.

**Comment by xueweiz** [comment]
btw I'd prefer if we can wait for the system-log-monitor and custom-plugin-monitor metrics support in before cutting next release :)
(they should not take too long)

**Comment by wangzhen127** [comment]
@xueweiz, your changes will be v0.7 as it contains major updates. @yguo0905's change will be a patch release of v0.6.

**Comment by xueweiz** [comment]
Thanks for the clarification Zhen!

**Comment by yguo0905** [comment]
@wangzhen127, I just realized that df2bc3df22c174389668e6630a320574dae23052 was already tagged as v0.6.4 (although it includes the OpenCensus and gopsutil dependency update), so we should have created the v0.6 branch based on that commit.

**Comment by yguo0905** [comment]
Sorry for the wrong commit in the description. Let's create the branch based on https://github.com/kubernetes/node-problem-detector/commit/df2bc3df22c174389668e6630a320574dae23052.

**Comment by wangzhen127** [comment]
Fixed
