### ISSUE TITLE
Unify log monitor options into 1

### ISSUE THREAD

**Issue by grosser** [kubernetes/node-problem-detector#311]
There are 3 options (`--config.system-log-monitor`, `--config.custom-plugin-monitor`, `--config.system-stats-monitor`) I have to correctly sort my plugins into, would be great if there was just 1 `--configs config/*.json` and it reads the config type (which it has to do anyway) and then decides how to treat it.

atm we are doing this which is kinda silly
```
custom="config/custom-"
custom_plugins=`ls config/*.json | grep ${custom} | tr '\n' ',' | sed 's/,$//'`
system_plugins=`ls config/*.json | grep -v ${custom} | tr '\n' ',' | sed 's/,$//'`

./bin/node-problem-detector \
    --logtostderr \
    --system-log-monitors=${system_plugins} \
    --custom-plugin-monitors=${custom_plugins}

```

/cc @eatwithforks

**Comment by grosser** [comment]
I guess this stems from gos strict json parsing ... so maybe parse the file with a "plugin field only" parser and then decide what parser to use or so 🤷‍♂

**Comment by xueweiz** [comment]
This is a fun feature request :)
I don't have any opinion against it. But I don't think it's very high priority either.

If we are going to do this, I think I'd add a few more requirements:
1. Does not break the existing command line interface (e.g. `config.system-log-monitor`).
1. Compatible with all existing config files.
1. (optional) The design should not conflict with #344 where we could potentially support yaml-formatted config files.

I'd welcome any PR for this from anyone :) Or if you think this is not that important, feel free to close it.

---
And by the way, if you think `grep` is not reliable enough (for example, the word "custom"  could appear in a system-log-monitor config file as well), you could use `jq`. For example `jq .plugin config/custom-plugin-monitor.json`. That should give you pretty reliable result.

**Comment by wangzhen127** [comment]
It has been several years and we haven't seen much need of this FR. I am closing this issue. Please feel free to reopen if this is still important to you.

/close
