### ISSUE TITLE
allow custom run intervals to improve node boot time and reduce runtime load

### ISSUE THREAD

**Issue by grosser** [kubernetes/node-problem-detector#313]
# Problem
when the node first boots the status conditions change rapidly, so we want to check frequently
when a node is running for a while, the status change rarely, so we want to save overhead

# Solution
`invoke_interval: ["30s", "60s", "60s", "60s", "2m", "2m", "5m"]`

**Comment by Random-Liu** [comment]
Thanks for the proposal!

I think this is a valid request. @xueweiz @wangzhen127 

We can add some kind of backoff mechanism for the interval, something like:
```
initial_invoke_interval: 30s
max_invoke_interval: 5m
backoff_factor: 2.0
```

And the interval should be reset whenever there is a state change:
1) When NPD startup, interval should start from `30s`, and eventually extend to `5m` if no problem is found.
2) When a problem is detected, interval is set back to `30s` to frequently check whether problem is gone, and eventually extend to `5m` if the problem resides.
3) When a problem is gone, interval is set back to `30s` to frequently check whether problem comes back again, and eventually extend to `5m` if the problem never comes back.

**Comment by grosser** [comment]
I like the initial+max, maybe just reuse the current interval to mean max and add "initial_interval" to make migration simple ... backoff_factor can just be a sane default at first, few will need it anyway

**Comment by grosser** [comment]
@Random-Liu can I get a review on https://github.com/kubernetes/node-problem-detector/pull/367 which was my first PR to get going ... but so far nobody showed up :(
