### ISSUE TITLE
v0.7.0 not available on k8s.gcr.io

### ISSUE THREAD

**Issue by ghouscht** [kubernetes/node-problem-detector#316]
Seems to be the same issue like in #230 
A bit confusing, as the [release notes](k8s.gcr.io/node-problem-detector:v0.7.0) clearly state that the docker image can be found @ `k8s.gcr.io/node-problem-detector:v0.7.0` but actually isn't there.

**Comment by frittentheke** [comment]
@Random-Liu ^^

**Comment by Random-Liu** [comment]
Triggered build, should be made available by automation soon. :)
