### ISSUE TITLE
Missing node name from problem metrics

### ISSUE THREAD

**Issue by Pharb** [kubernetes/node-problem-detector#332]
Would it be possible to add the node name as labels to the `problem_counter` metrics?
Currently the `instance` label refers to the IP address of the node-problem-detector pod, which makes it hard to match it up with the actually affected node.

```
problem_counter{endpoint="exporter",instance="172.12.34.56:20257",job="node-problem-detector",namespace="kube-system",pod="node-problem-detector-6k8pb",reason="AUFSUmountHung",service="node-problem-detector"}

problem_gauge{endpoint="exporter",instance="172.12.34.56:20257",job="node-problem-detector",namespace="kube-system",pod="node-problem-detector-6k8pb",reason="AUFSUmountHung",service="node-problem-detector",type="KernelDeadlock"}
```

**Comment by xueweiz** [comment]
Hi @Pharb , I believe `problem_counter` metric comes with only one label: "reason".
The other fields seems to be added by your Prometheus scraping service. Can you let me know what tool are you using to scrape these metrics? I think the best way is to configure that in the scraping service. But I want to learn about your constraints first. Thanks!

I'm mostly familiar with two tools for scraping Prometheus endpoint:
1. [prometheus-to-sd](https://github.com/GoogleCloudPlatform/k8s-stackdriver/tree/master/prometheus-to-sd)
2. [OpenCensus agent](https://opencensus.io/service/components/agent/)

In both cases, I can configure the scraping service, and let them add additional labels.
Also, I'm mostly faimilar with Stackdriver Monitoring as the monitoring backend. They have a concept of [monitored resource](https://cloud.google.com/monitoring/api/resources). And the best way to add such a label, is as a the monitored resource field (e.g. zone, instance id, node name, project id...).)

**Comment by HaveFun83** [comment]
Hi you need to relabel the metric.
If you are using the prometheus-operator concept you can add the following to your nodeproblemdetector servicemonitor:
```
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: nodename
```
this added a nodename label to the metrics

**Comment by Pharb** [comment]
Great, thanks a lot for the quick responses. 
Yes, I am using the Prometheus Operator and didn't think about using relabelings.
