### ISSUE TITLE
Support yaml formatted configs

### ISSUE THREAD

**Issue by xueweiz** [kubernetes/node-problem-detector#344]
Currently all config files are in json format. However @Random-Liu has been complaining about that it's hard to deal with all the character escapings in json, and would prefer a yaml format.

Maybe we can reuse the apimachinery lib at here to support both json and yaml together: https://github.com/kubernetes/apimachinery/blob/461753078381c979582f217a28eb759ebee5295d/pkg/util/yaml/decoder.go#L207

**Comment by grosser** [comment]
yes please, we keep all other configs as yaml so this would be nice!
