### ISSUE TITLE
Running as a daemonset, how to use the script(custom-plugin-monitor) to get the node info in the container

### ISSUE THREAD

**Issue by tianzhuozhuo** [kubernetes/node-problem-detector#351]
The easiest way to install node-problem-detector into our cluster is to use the helm chart. Node-problem-detector will run as deamonset. But, how to use the script(custom-plugin-monitor) to get the node info in the container, such as,  
network_problem.sh 
```
#!/bin/bash
OK=0
NONOK=1
UNKNOWN=2

[ -f /proc/sys/net/ipv4/netfilter/ip_conntrack_max ] || exit $UNKNOWN
[ -f /proc/sys/net/ipv4/netfilter/ip_conntrack_count ] || exit $UNKNOWN

conntrack_max=$(cat /proc/sys/net/ipv4/netfilter/ip_conntrack_max)
conntrack_count=$(cat /proc/sys/net/ipv4/netfilter/ip_conntrack_count)

if (( conntrack_count >= conntrack_max )); then
  echo "Conntrack table full"
  exit $NONOK
fi

echo "Conntrack table available"
exit $OK 
``` 
network-problem-monitor.json 
```
{
  "plugin": "custom",
  "pluginConfig": {
    "invoke_interval": "30s",
    "timeout": "5s",
    "max_output_length": 80,
    "concurrency": 3
  },
  "source": "network-custom-plugin-monitor",
  "metricsReporting": true,
  "conditions": [],
  "rules": [
    {
      "type": "temporary",
      "reason": "ConntrackFull",
      "path": "./config/plugin/network_problem.sh",
      "timeout": "3s"
    }
  ]
} 
```

**Comment by tianzhuozhuo** [comment]
@xueweiz 
“mount host's /proc into the container, probably at /host/proc...”, That is still not the host info. ip_conntrack_count is the non-conventional file or file system.

**Comment by xueweiz** [comment]
> Ip_conntrack_count is the non-conventional file or file system.

Yes, I understand :) It belongs to procfs.

However, "mount" in Docker is not a "conventional mount" as well, it's a "bind mount". It can handle procfs :) You just need to grant the container enough privilege and put it in the right namespace.

I just tried it out, and realized that for this use case, the bind mount and privilege escalation are not actually necessary. You just need the host network namespace.

You can try these commands:
```
docker run -it --net=host bash -c "find /proc | grep conntrack_count"
docker run -it --net=host bash -c "cat /proc/sys/net/ipv4/netfilter/ip_conntrack_count"
```

**Comment by tianzhuozhuo** [comment]
> You just need the host network namespace


Yes,it's true 
If Node problem detector running as deamonset, we shoud use hostNetwork. Although this method is not very secure, we still need it.
