### ISSUE TITLE
detecting host system time clock offset with NTP server?

### ISSUE THREAD

**Issue by cequencer** [kubernetes/node-problem-detector#354]
Currently, I see there is a plugin that checks to see if ntpd service is actively running via this 
/config/plugin/check_ntp_time.sh script.   Are there additional checks that can be considered to detect system clock offset with NTP servers?  Services like ZooKeeper are sensitive to system clock offsets and it can be difficult to debug or troubleshoot distributed applications in virtual environments where computation resources are oversubscribed.  

Here are couple of example of this type of check.
https://www.monitoring-plugins.org/doc/man/check_ntp_time.html
https://nagios-plugins.org/doc/man/check_ntp_peer.html

**Comment by iranzo** [comment]
Also: https://github.com/citellusorg/citellus/blob/master/citellusclient/plugins/core/system/clock-1-ntpd.sh
