### ISSUE TITLE
Remove `go get` instructions from readme since this uses go modules

### ISSUE THREAD

**Issue by grosser** [kubernetes/node-problem-detector#362]
... seems redundant to document both, should work for anyone no matter where they check out

**Comment by vteratipally** [comment]
https://github.com/kubernetes/node-problem-detector/blob/master/CONTRIBUTING.md

**Comment by yordis** [comment]
Is this still a valid issue?

**Comment by grosser** [comment]
yeah https://github.com/kubernetes/node-problem-detector/pull/735

**Comment by grosser** [comment]
thx for following up on these, the bot closes so much stuff 😞
