### ISSUE TITLE
processing of kernel messages seems to be delayed after startup

### ISSUE THREAD

**Issue by bhcleek** [kubernetes/node-problem-detector#386]
#### reproduction
1. deploy node-problem-detector as a daemonset a configuration to monitor kernel logs using the journald driver.
1. identify a node that is running systemd to test on
1. check the logs of the node-problem-detector instance running on the identified node to make sure it's watching the kernel logs
1. run `kubectl get events -w`
1. write a test message to /dev/kmsg (e.g. `sudo sh -c "echo 'kernel: BUG: unable to handle kernel NULL pointer dereference at TESTING' >> /dev/kmsg"`) on the node.
1. wait some period of time (<45 minutes, but that's all I know for sure)
1. write another test message

#### expected behavior
the events watch shows that the both events were created when the respective test message was written

#### actual behavior
the events watch only shows the second event

Is there some kind of delay in processing the kernel logs that could account for the first message not causing an event to be created?

**Comment by xueweiz** [comment]
> Is there some kind of delay in processing the kernel logs that could account for the first message not causing an event to be created?

Nothing I can think of. If you have already checked the logs of NPD to make sure the system-log-monitor has started, I'd have the same expectation as you mentioned.

Now I'm thinking that maybe k8s_exporter hasn't fully setup yet for some reason. Could you try to start NPD with Prometheus Exporter, and try to reproduce the problem?
Basically after your step 5, run "curl localhost:20257" and see if there is any "problem_counter" metrics being updated to 1.
If yes, then you are looking at a bug/race condition in k8s_exporter;
If not, then you are looking at bug at system-log-monitor.

Thanks!

**Comment by bhcleek** [comment]
prometheus exporter is running, and no metrics are problem_counter metrics are reported until the events start coming through, too; it looks like a bug with system-log-monitor.

**Comment by xueweiz** [comment]
Thanks @bhcleek ! :)
This is interesting. I have no idea why is that happening. And I just recently [wrote some tests](https://github.com/kubernetes/node-problem-detector/pull/387) to do similar work, and didn't observe similar failure.
Can you share your system-log-monitor config file as well? I'll try to repro this and take a closer look. Thanks! :)

/assign @xueweiz

**Comment by bhcleek** [comment]
```
    {
        "plugin": "kmsg",
        "logPath": "/dev/kmsg",
        "lookback": "5m",
        "bufferSize": 10,
        "source": "kernel-monitor",
        "conditions": [
            {
                "type": "KernelDeadlock",
                "reason": "KernelHasNoDeadlock",
                "message": "kernel has no deadlock"
            },
            {
                "type": "ReadonlyFilesystem",
                "reason": "FilesystemIsReadOnly",
                "message": "Filesystem is not read-only"
            }
        ],
        "rules": [
            {
                "type": "temporary",
                "reason": "OOMKilling",
                "pattern": "Kill process \\d+ (.+) score \\d+ or sacrifice child\\nKilled process \\d+ (.+) total-vm:\\d+kB, anon-rss:\\d+kB, file-rss:\\d+kB.*"
            },
            {
                "type": "temporary",
                "reason": "TaskHung",
                "pattern": "task \\S+:\\w+ blocked for more than \\w+ seconds\\."
            },
            {
                "type": "temporary",
                "reason": "UnregisterNetDevice",
                "pattern": "unregister_netdevice: waiting for \\w+ to become free. Usage count = \\d+"
            },
            {
                "type": "temporary",
                "reason": "KernelOops",
                "pattern": "BUG: unable to handle kernel NULL pointer dereference at .*"
            },
            {
                "type": "temporary",
                "reason": "KernelOops",
                "pattern": "divide error: 0000 \\[#\\d+\\] SMP"
            },
            {
                "type": "permanent",
                "condition": "KernelDeadlock",
                "reason": "AUFSUmountHung",
                "pattern": "task umount\\.aufs:\\w+ blocked for more than \\w+ seconds\\."
            },
            {
                "type": "permanent",
                "condition": "KernelDeadlock",
                "reason": "DockerHung",
                "pattern": "task docker:\\w+ blocked for more than \\w+ seconds\\."
            },
            {
                "type": "permanent",
                "condition": "ReadonlyFilesystem",
                "reason": "FilesystemIsReadOnly",
                "pattern": "Remounting filesystem read-only"
            },
            {
              "type": "temporary",
              "reason": "ArpCacheOverflow",
              "pattern": "neighbour: arp_cache: neighbor table overflow."
            }
        ]
    }
```
