### ISSUE TITLE
NPD need suport multi-custom plugins

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/node-problem-detector#388]
Why do we need this proposal?
When we use Kubernetes in our project, which contains serveral tech teams, many node problem detector plugins are mainintaining by node hardware team, runtime team, SRE team and so on. Under current architechure, we had to combine them into one plugins. So it will tense our maintaining. To decouple this plugins, we want to make npd support multi custom plugins, if with dynamically config updation, that wll be much more valuable.

**Comment by xueweiz** [comment]
If I recall correctly, you can specify multiple custom-plugin-monitor config files. If you have multiple custom-plugin-monitor configs, and pass them into multiple `--config.custom-plugin-monitor` argument, does that not solve your problem?

e.g. something like:
`./bin/node-problem-detector --logtostderr --config.custom-plugin-monitor=config/custom-plugin-monitor.json --config.custom-plugin-monitor=config/network-problem-monitor.json`

**Comment by zhangxiaoyu-zidif** [comment]
In fact we want to have multi custom-plugin-monitor, not just to deal with various plugins with different .json.

**Comment by xueweiz** [comment]
Could you share the proposal? I want to understand the use case, and to understand what do you mean by "multi custom plugins".

You can see some existing proposals [here](https://docs.google.com/document/d/1jK_5YloSYtboj-DtfjmYKxfNnUxCAvohLnsH5aGCAYQ/edit#) and [here](https://docs.google.com/document/d/1SeaUz6kBavI283Dq8GBpoEUDrHA2a795xtw0OvjM568/edit).

**Comment by zhangxiaoyu-zidif** [comment]
Thanks! I will try to send a proposal following this format.
