### ISSUE TITLE
The documentation sucks

### ISSUE THREAD

**Issue by multi-io** [kubernetes/node-problem-detector#406]
I'm running npd with a custom plugin that sets a node condition. The only thing that resembles a documentation for this seems to be the "Node-Problem-Detector Plugin Interface Proposal" at https://docs.google.com/document/d/1jK_5YloSYtboj-DtfjmYKxfNnUxCAvohLnsH5aGCAYQ/edit#. I got the plugin to work with npd 0.6.3 by essentially trial and error, i.e.tweaking the `--custom-plugin-monitors` config file and seeing how that'll change the node condition at various times during the lifecycle of the npd pod on that node. I've now updated npd to 0.8.0 and my config no longer works, apparently because of https://github.com/kubernetes/node-problem-detector/pull/320, and I don't even understand from that PR and associated ticket how the old behaviour was "wrong" and the new one is "correct", because there's no real spec on what constitutes correctness here. So I find myself repeating the trial and error thing again. There is no chance to come up with a functioning monitoring config file just from reading that interface proposal document or the npd design proposal at https://docs.google.com/document/d/1cs1kqLziG-Ww145yN6vvlKguPbQQ0psrSBnEqpy0pzE/edit#heading=h.xgjl2srtytjt.

What I would need is some simple but complete documentation on how the configuration's `conditions` and `rules` sections as well as the plugin script's exit code and stdout set the node condition's type, reason, message and status fields during the npd pod's lifecycle, i.e. after npd startup and then after the first and every subsequent invocation of the plugin script.

**Comment by f1ames0ff** [comment]
Agree. It sucks ass. It even doesn't describe important address parameter which is used by almost any team working with cloud.
![image](https://user-images.githubusercontent.com/5371279/200658503-ad117599-8c54-4546-9a23-bc15db427eb7.png)
