### ISSUE TITLE
Can NDP set a node in NotReady status ?

### ISSUE THREAD

**Issue by ticapix** [kubernetes/node-problem-detector#409]
Hi,

I wrote a custom [plugin](https://github.com/ticapix/storageos-health-detector/) to monitor StorageOS volume health status during a cluster rolling upgrade.

The plugin seems to work and I can see the event with `kubectl get event -w`

Ex: `5m44s       Warning   VolumeNotHealthy   node/b2-7.1   NODE b2-7.1`

But the node with `kubectl get node` stays in `Ready` status.

Is that the correct beahvior ?

Can I use NDP to set a node in `NotReady` status ?

Thank you,

**Comment by VadimEisenberg** [comment]
I have the same question.

From what I see, if a custom problem is detected, it is reported in events and in conditions, but the node is still in Ready state and new pods are scheduled it.

Should this be configurable?
