### ISSUE TITLE
Nodes cannot be found

### ISSUE THREAD

**Issue by jpmcb** [kubernetes/node-problem-detector#411]
Hello! I'm attempting to get NPD running on a cluster but I continue to run into the following issue:

```
...
E0211 17:10:59.536023       1 manager.go:130] failed to update node conditions: nodes "0cf31fd4-765c-48d8-8b83-2fd6ae841bc6" not found
```
**Background:**
Kubernetes version - v1.15.5
Provisioned through Pivotal Container Service (with bosh) running on GCP
3 nodes, 1 master

There are 3 NPD pods that come up but each of the 3 pods return similar logs; not being able to find the nodes. What's also confusing to me is that the guid given in the log message does not match anything i see when describing the nodes. I may be totally off base here but not sure what else to look into. 

Let me know if I can provide anymore information

**Comment by jpmcb** [comment]
When inspecting the hostname on the pods:
```
$ kubectl exec -n kube-system node-problem-detector-v0.1-abc123 -- hostname
0cf31fd4-765c-48d8-8b83-2fd6ae841bc6
```
Looks like the container is being given a name that does not match the node. Any tips on dynamically overwriting this so it can talk to the nodes?

**Comment by jpmcb** [comment]
Looks like NPD was using the `hostname` on the machine which did not correctly reference the vm-id of that worker. However, using the following in the daemonset worked correctly and we now have conditions and events reporting:

https://github.com/kubernetes/kubernetes/blob/06fad92509dd6d087062ed1edc5d7c7dfd75bbdb/cluster/addons/node-problem-detector/npd.yaml#L64-L68

Could this be better documented? I found no helpful reference in this repo or in the kubernetes.io documentation

**Comment by guanyuding** [comment]
@jpmcb  I think you need this document:  https://github.com/kubernetes/node-problem-detector/blob/master/deployment/node-problem-detector.yaml 
```
     env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```

**Comment by jpmcb** [comment]
Closing this as the document @guanyuding linked solved this for me - much thanks!!
