### ISSUE TITLE
All checks run at the same time causing spiky CPU and throttling

### ISSUE THREAD

**Issue by eatwithforks** [kubernetes/node-problem-detector#412]
all our checks run at the same time and eats up a lot of cpu. it would be nice to have an offset value so the checks can be staggered to run at different times (or some random start time flag)

**Comment by xueweiz** [comment]
This is interesting. I think both `custom plugin monitor` and `system stats monitor` periodically checks node problems. Could you confirm which one is contributing to the CPU spikiness?

You could confirm by checking the period of the `custom plugin monitor` config and the period of the `system stats monitor` config, and then comparing them to the period of the CPU spikiness.

Thanks!
