### ISSUE TITLE
0.8.1 image

### ISSUE THREAD

**Issue by mariusgrigoriu** [kubernetes/node-problem-detector#415]
The image in the release notes `staging-k8s.gcr.io/node-problem-detector:v0.8.1` is not available without auth.  Can a release be published to `k8s.gcr.io/node-problem-detector`?

**Comment by nvtkaszpir** [comment]
Looks like the image was promoted to production, so please try without `staging-` prefix:

```shell
docker pull k8s.gcr.io/node-problem-detector:v0.8.1
````

**Comment by mariusgrigoriu** [comment]
Seems better now, thank you.
