### ISSUE TITLE
stale condition on node after custom plugin is removed

### ISSUE THREAD

**Issue by blackgold** [kubernetes/node-problem-detector#423]
I added a custom plugin to add a condition XYZ.
After a month I realized I don't need the custom plugin and removed it.
Redeployed the node problem detector.
I still see the condition XYZ.
Is it expected to manually delete the condition from all the nodes on the cluster?

**Comment by guanyuding** [comment]
I think you can set a prestop script, and make a  patch to delete condition XYZ for the  node
