### ISSUE TITLE
AWS Scheduled Maintenance / Spot Instance Termination Notifications

### ISSUE THREAD

**Issue by ari-becker** [kubernetes/node-problem-detector#432]
We're interested in using the combination of NPD + Draino + Cluster Autoscaler to set up auto-self-remediation for our cluster. We already run NPD and Cluster Autoscaler.

Our cluster runs in AWS, so we use AWS's [node-termination-handler](https://github.com/aws/aws-node-termination-handler) project to automatically cordon and drain nodes that have been marked by AWS for termination. But reviewing the NPD and Draino combination made me wonder - the NPD project's scope includes "Infrastructure daemon issues" and "Hardware issues". Wouldn't AWS scheduled maintenance events and spot instance termination notifications count? There seems to be significant overlap between AWS's NTH and the NPD / Draino combination.

If NPD supported identifying AWS scheduled maintenance events and spot instance termination notifications, then we could use Draino to cordon and drain the nodes and simplify the infrastructure monitoring stack by getting rid of the superfluous AWS NTH DaemonSet.

**Comment by goatmale** [comment]
/reopen

I would like to see this too.

**Comment by btiernay** [comment]
> If NPD supported identifying AWS scheduled maintenance events and spot instance termination notifications, then we could use Draino to cordon and drain the nodes and simplify the infrastructure monitoring stack by getting rid of the superfluous AWS NTH DaemonSet.

❤️ This is precisely what we are investigating as well. I was exploring both codebases and seems as though this should be feasible using a NPD custom plugin that monitors the the EventBridge bound SQS queue.

**Comment by btiernay** [comment]
> If NPD supported identifying AWS scheduled maintenance events and spot instance termination notifications, then we could use Draino to cordon and drain the nodes and simplify the infrastructure monitoring stack by getting rid of the superfluous AWS NTH DaemonSet.

❤️ This is precisely what we are investigating as well. I was exploring both codebases and seems as though this should be feasible using a NPD custom plugin that monitors the the EventBridge bound SQS queue.

@ari-becker Curious if you were able to work around this limitation by some other means. Thanks!

**Comment by ari-becker** [comment]
> 

Hi @btiernay , I've long since moved onto other projects, so I'm trying to answer you from memory.
If I recall correctly, we just ended up running both the NPD and NTH simultaneously. It's less efficient than only needing NPD, but it worked for our purposes, and wrote down the hypothetical efficiency gains as technical debt.
