### ISSUE TITLE
Security Vulnerabilities in v0.8.2 

### ISSUE THREAD

**Issue by rp592h** [kubernetes/node-problem-detector#436]
Hello, i was trying to use the latest NPD image in my deployment, however found many security vulnerabilities and gaps..

Need help to resolve this.

Attached is the report of issues..

[node-problem-detector-f7a97be-2020-06-23_15-25-40.txt](https://github.com/kubernetes/node-problem-detector/files/4827087/node-problem-detector-f7a97be-2020-06-23_15-25-40.txt)

**Comment by MouseRider** [comment]
+1
