### ISSUE TITLE
There have a bug in nodeProblemClient.GetConditios

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes/node-problem-detector#437]
In function GetConditions, have Implicit memory aliasing of items from a range statement.

```go
	conditions := []*v1.NodeCondition{}
	for _, conditionType := range conditionTypes {
		for _, condition := range node.Status.Conditions {
			if condition.Type == conditionType {
				conditions = append(conditions, &condition)
			}
		}
	}
	return conditions, nil
```
after this loop, we might got several same conditions.

But I realize this Interface never be used, so maybe we can remove this interface?

**Comment by Lion-Wei** [comment]
@wangzhen127 Please take a look, thanks.

**Comment by wangzhen127** [comment]
Do you mean `problemclient.Client.GetConditions()`? Seems like so. We probably had some usage before and later removed during refactor. It does not hurt to keep it for now, in case we need it again later.

**Comment by Lion-Wei** [comment]
Thanks for replaying. 
> We probably had some usage before and later removed during refactor. It does not hurt to keep it for now, in case we need it again later.
Maybe we can fix this GetConditions issue? Currently if we have more than one items for a single condition in `node.Status.Conditions`, we will get several same conditions in conditions after this loop.

**Comment by saintube** [comment]
I also found some of the `conditions` duplicated when using custom monitor plugins. Should we ensure there is no redundancy in `conditions` before they get exported, or merge them in exporters?
