### ISSUE TITLE
Feature Request: Support basic container stats as part of System Stats Monitor

### ISSUE THREAD

**Issue by Sanrag** [kubernetes/node-problem-detector#440]
Assuming one or more container running per node, I'm looking for some basic stats about those containers exported periodically as metrics

- `container/cpu/usage`
- `container/cpu/limit` *
- `container/memory/usage`
- `container/memory/limit` *
- `container/block/io/read_bytes`
- `container/block/io/write_bytes`
- `container/start_timestamp` (or `container/uptime`)
- `container/restart_count`

 `*` = where applicable

Each of these metrics would have `container_name` ( and maybe `container_id`?) as a label.

This is mostly the output of `docker stats`.

**Comment by vteratipally** [comment]
Enabling container metrics on NPD would impact the performance. it is recommended to use the metrics enabled through Prometheus.
