### ISSUE TITLE
v0.8.3 image is not public

### ISSUE THREAD

**Issue by ijl** [kubernetes/node-problem-detector#448]
The image given in the release is not public and cannot be downloaded.

```
docker pull staging-k8s.gcr.io/node-problem-detector:v0.8.3
Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

Note the previous release, which can be downloaded, was at k8s.gcr.io (no staging).

**Comment by ijl** [comment]
@Random-Liu I see you released v0.8.3, could you possibly take a look?

**Comment by naikajah** [comment]
This image needs to be in the public registry. Is this missed?

**Comment by hasssammalik** [comment]
Could you please also upload the v0.8.3 image to public registry (k8s.gcr.io) instead of staging-k8s.gcr.io/node-problem-detector:v0.8.3 @Random-Liu

**Comment by Random-Liu** [comment]
Sorry, the OSS image publish flow changed.

We haven't migrated NPD to the new image publish workflow yet https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io.

**Comment by Random-Liu** [comment]
Should be fixed by https://github.com/kubernetes/k8s.io/pull/1199.

**Comment by Random-Liu** [comment]
Fixed. The new image is k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.3
