### ISSUE TITLE
Node condition status does not return to False in filelog

### ISSUE THREAD

**Issue by superbrothers** [kubernetes/node-problem-detector#449]
Node condition status does not return to False in filelog

As of NPD v0.8.3, the filelog will never return to `False` once the condition status is `True`, except by restarting the NPD.

```go
// monitorLoop is the main loop of log monitor.
func (l *logMonitor) monitorLoop() {
	defer func() {
		close(l.output)
		l.tomb.Done()
	}()
	l.initializeStatus()
	for {
		select {
		case log, ok := <-l.logCh:
			if !ok {
				glog.Errorf("Log channel closed: %s", l.configPath)
				return
			}
			l.parseLog(log)
		case <-l.tomb.Stopping():
			l.watcher.Stop()
			glog.Infof("Log monitor stopped: %s", l.configPath)
			return
		}
	}
}
```

https://github.com/kubernetes/node-problem-detector/blob/v0.8.3/pkg/systemlogmonitor/log_monitor.go#L126-L147

Is this the expected behavior? I would expect the status to be changed back to `False` if it no longer matches the rules.

**Comment by Random-Liu** [comment]
Yeah, this is expected behavior.

For filelog, there is only pattern to trigger the condition, but nothing to set it back.

We thought about supporting a pattern to reset it back, but that is not added.

The custom plugin does support switch between True/False, which you could probably use.

**Comment by superbrothers** [comment]
Thank you for your comment.

> For filelog, there is only pattern to trigger the condition, but nothing to set it back.
> We thought about supporting a pattern to reset it back, but that is not added.

I understand.

> The custom plugin does support switch between True/False, which you could probably use.

log-counter seems to be the same behavivor with the filelog plugin. I'm going to use log-counter as a custom plugin!

**Comment by Shikaz** [comment]
Hi

Is this still the case or now the filelog or any custom plugin will return to False after sometime?
