### ISSUE TITLE
We need a ChangeLog for NPD.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/node-problem-detector#45]
We should add a changelog to make the release more clear and official.

**Comment by jfilak** [comment]
What about http://keepachangelog.com/ ? We've just started using this format in ABRT - https://github.com/abrt/abrt/blob/master/CHANGELOG.md

**Comment by Random-Liu** [comment]
@jfilak Thanks for the suggestion, the format really LGTM.

**Comment by andyxning** [comment]
@jfilak Awesome. 👋
