### ISSUE TITLE
Add option flag to taint node for permanent problems

### ISSUE THREAD

**Issue by adriananeci** [kubernetes/node-problem-detector#457]
Currently, when a permanent problem is triggered, node problem detector(NPD) adjusts the corresponding node condition status and triggers an event.
This can be seen as a limitation when using NPD in conjunction with [descheduler](https://github.com/kubernetes-sigs/descheduler) since the latter is not able to evict pods based on node conditions.
This gap can be closed if NPD can expose an option flag (or even better on a per plugin rule config option) to add also a node taint along with node condition when a permanent problem is triggered. 
A sample config could look like:
```
{
  "plugin": "kmsg",
  "logPath": "/dev/kmsg",
  "lookback": "5m",
  "bufferSize": 10,
  "source": "kernel-monitor",
  "conditions": [
      {
          "type": "ReadonlyFilesystem",
          "reason": "FilesystemIsNotReadOnly",
          "message": "Filesystem is not read-only"
      }
  ],
  "rules": [
      {
          "type": "permanent",
          "condition": "ReadonlyFilesystem",
          "reason": "FilesystemIsReadOnly",
          "pattern": "Remounting filesystem read-only",
          "taintNode": true  ===> will taint the node with ReadonlyFilesystem=:NoSchedule
      }
  ]
}
```

The taint should be removed when/if the permanent problem is recovering.

**Comment by bilalcaliskan** [comment]
any update on that? because of this missing feature, we have to combine node-problem-detector+draino+descheduler(draino is not so stable for draining activity i guess).

**Comment by bilalcaliskan** [comment]
I think we should put taint on the broken node [related to that section](https://github.com/kubernetes-sigs/descheduler#removepodsviolatingnodetaints), remove the taint when node is healthy again.

**Comment by universam1** [comment]
Sorry to say but IMHO without this feature to taints a problematic node, where is the value of this project?

**Comment by wangzhen127** [comment]
There have been several similar requests in the past. But I don't think we should support this feature. The reason is provided in https://github.com/kubernetes/node-problem-detector/pull/565#issuecomment-2093855921

/close
