### ISSUE TITLE
failed to build node-problem-detector

### ISSUE THREAD

**Issue by sandflee** [kubernetes/node-problem-detector#46]
- go version go1.7 darwin/amd64
- godep v74 (darwin/amd64/go1.7)

make failed with output:
```
CGO_ENABLED=0 GOOS=linux godep go build -a -installsuffix cgo -ldflags '-w' -o node-problem-detector
vendor/github.com/coreos/go-systemd/sdjournal/functions.go:19:2: no buildable Go source files in /Users/sandflee/goproject/src/k8s.io/node-problem-detector/vendor/github.com/coreos/pkg/dlopen
godep: go exit status 1
```

**Comment by Random-Liu** [comment]
This is a bug, and should be fixed in https://github.com/kubernetes/node-problem-detector/pull/39.

For temporary workaround, you can set `CGO_ENABLED=1`.

**Comment by sandflee** [comment]
thanks Random-Liu,  still see errors, even using Random-Liu:journald-support
```
CGO_ENABLED=1 GOOS=linux go build -o ./bin/node-problem-detector -a -ldflags '-w' -tags journald
# k8s.io/node-problem-detector/vendor/github.com/coreos/go-systemd/sdjournal
vendor/github.com/coreos/go-systemd/sdjournal/journal.go:27:33: fatal error: systemd/sd-journal.h: No such file or directory
 // #include <systemd/sd-journal.h>
                                 ^
compilation terminated.
```
now I build under linux env, am I miss something?
- go version go1.6 linux/amd64
- godep v74 (linux/amd64/go1.6)

**Comment by Random-Liu** [comment]
You need to install `libsystemd-journal-dev` or `libsystemd-dev` to build it for journald support.

In #39, we'll add an option to enable/disable journald support. After that you won't need the package if you disable the journald support when make.

In fact node problem detector can't work very well until #39 is merged. I'll try to get that PR merged soon.

**Comment by sandflee** [comment]
thanks, it worked for me.

**Comment by jfilak** [comment]
@Random-Liu Perhaps the build process can check if all the dependencies are available:
```make
./bin/node-problem-detector: $(PKG_SOURCES) node_problem_detector.go
	pkg-config libsystemd --exists --print-errors
	CGO_ENABLED=0 GOOS=linux godep go build -a -installsuffix cgo -ldflags '-w' -o node-problem-detector
```

Or maybe node-problem-detector could start using `Autotools` to create the Makefile. Because these checks should be performed just once at `./configure` time.

**Comment by Random-Liu** [comment]
@jfilak Yeah, we should check the dependency. But I'd prefer add the check in the makefile for now, because `autotools` seems to be a little complex and we don't have too much dependency now. :)
