### ISSUE TITLE
Please upload latest releases to the docker registry

### ISSUE THREAD

**Issue by zerkms** [kubernetes/node-problem-detector#460]
The latest available docker image is `k8s.gcr.io/node-problem-detector:v0.8.2`, `v0.8.3` and `v0.8.4` are currently missing.

Could you please upload those.

**Comment by Thoro** [comment]
I believe the releases are now under a subdirectory:

k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.4

**Comment by zerkms** [comment]
Right, then probably https://github.com/kubernetes/node-problem-detector/blob/f42281ee2658900bdb0571e1159a43f6ab712a19/deployment/node-problem-detector.yaml#L23 could be updated

**Comment by Thoro** [comment]
yep, that got me too :) and I got a nice ErrImagePull ...
