### ISSUE TITLE
Feature Request: Windows Support

### ISSUE THREAD

**Issue by jeremyje** [kubernetes/node-problem-detector#461]
Since there's growing support for Windows in Kubernetes and Docker community it'd be nice to get a Windows build for the node-problem-detector. This has been discussed on [sig-windows](https://docs.google.com/document/d/1Tjxzjjuy4SQsFSUVXZbvqVb64hjNAG5CQX8bK7Yda9w/edit#heading=h.itpry7uee9tq) before. I'd like to start a discussion here on what's necessary.

I've been looking on what's necessary to bring multi-arch building to this project and what dependency detanglement is necessary to build Windows binaries. It's possible with a few patches and dependency upgrades to build Windows binaries.

Multi-arch building would also unlock ARM support requested from https://github.com/kubernetes/node-problem-detector/issues/135.

Design Document: https://docs.google.com/document/d/1eiK6KAp_TFR0PgBMu2WCf49fMZcg-HHnBHMc9fALquU/edit

**Comment by jeremyje** [comment]
Design Doc: https://docs.google.com/document/d/1eiK6KAp_TFR0PgBMu2WCf49fMZcg-HHnBHMc9fALquU

**Comment by SergeyKanzhelev** [comment]
/reopen

need to update the readme: https://github.com/kubernetes/node-problem-detector#windows

**Comment by allyford** [comment]
@jeremyje - Is this work planned?

**Comment by SergeyKanzhelev** [comment]
/reopen

need to update the readme: https://github.com/kubernetes/node-problem-detector#windows
