### ISSUE TITLE
flakey npd tests in sig-node ci jobs

### ISSUE THREAD

**Issue by MHBauer** [kubernetes/node-problem-detector#467]
I've documented at k/k repo before realizing this has it's own repo. Maybe you can help me debug?
https://github.com/kubernetes/kubernetes/issues/94493
Are these tests supposed to be running outside of the ci-npd jobs?
Do they need to be ignored?
Is there some special setup that is done?
Should they be marked [serial] or [disruptive]?

**Comment by vteratipally** [comment]
these tests might be added as NPD runs as a default on kubernetes. I will try to debug the issue. I dont think there is any special setup done here.

**Comment by SergeyKanzhelev** [comment]
@vteratipally can you comment on why serial is needed? What tests do that wouldn't run in parellel? Can the un-parallellable resources be named somehow to separate tests?

**Comment by vteratipally** [comment]
Yes can we can try to separate the tests to parallelable resource because I believe that these tests are based on the event logs. I can give it a try

**Comment by SergeyKanzhelev** [comment]
CC: @ForestCold and @vteratipally FYI
