### ISSUE TITLE
Removing legacy conditions on a node

### ISSUE THREAD

**Issue by Uburro** [kubernetes/node-problem-detector#470]
I created several permanent checks on nods. After a certain amount of time, I didn't need it anymore. I deleted it and customised the cofing in the NPD. But they remained in the node condtion status. How can I delete it without removing the node from the cluster?

**Comment by simonostendorf** [comment]
@Uburro did you found a solution?

**Comment by Uburro** [comment]
@simonostendorf I don't remember opening this issue. :) Sorry!
