### ISSUE TITLE
Stable-Repo deprecation - provide new repo / helm chart

### ISSUE THREAD

**Issue by grieshaber** [kubernetes/node-problem-detector#473]
As mentioned in the [deprecation timeline](https://github.com/helm/charts#deprecation-timeline) of the [stable](https://github.com/helm/charts/tree/master/stable) repo, it will be shut down on 13th November 2020. 
All charts within these repos may be garbage collected and no longer available. 

To further install node-problem-detector via helm, it should be made available through a different or own helm repo.

**Comment by kfox1111** [comment]
Interested in this as well.
