### ISSUE TITLE
Configure the namespace where events are pushed

### ISSUE THREAD

**Issue by jonny-wg2** [kubernetes/node-problem-detector#476]
All events are pushed to the default namespace. It would be great if these are pushed to the same namespace where node-problem-detector is deployed or configured via an env or configmap.

**Comment by TinySong** [comment]
NPD already support, can out the event to specified namespace by pass arguments --event-namespace

**Comment by jonny-wg2** [comment]
Thank you so much! I see that version 0.8.2 has the argument we need.
