### ISSUE TITLE
Kernel log message time drift

### ISSUE THREAD

**Issue by MikuGhoul** [kubernetes/node-problem-detector#479]
KernelMonitor Daemon get kernel log message from /dev/kmsg, and then compare message timestamp with node-problem-detector start time, it works pretty well usually, but /dev/kmsg timestamp which provide by linux kernel maybe drift sometimes. See the manpage of [dmesg](https://man7.org/linux/man-pages/man1/dmesg.1.html#OPTIONS) with -T argument:

> Be aware that the timestamp could be inaccurate!  The time source used for the logs is not updated after system SUSPEND/RESUME.  Timestamps are adjusted according to current delta between boottime and monotonic clocks, this works only for messages printed after last resume.

The kernel log message timestamp is clock tick from boot time in kernel ring buffer, `dmesg -T` and `node-problem-detector's kmsgparser` get the human readable timestamp is just add the kernel timestamp offset and boot time, it exclude drift time.

In following environment, kernel log time drift more than 10 hours, so node-problem-detector will reports problems after 10 hours(without config lookback time in `kernel-monitor.json`)
```
[root@xxx ~]# echo test >> /dev/kmsg 
[root@xxx ~]# dmesg -T | tail -1
[Mon Oct 19 07:53:13 2020] test
[root@xxx ~]# date
Mon Oct 19 18:46:46 CST 2020
```
is there any solutions or workaround for this?

**Comment by stek29** [comment]
this is still an issue

**Comment by stek29** [comment]
node problem detector could write a message into kmsg when it starts, and then read it back and check the difference between date when it was written and date calculated by kmsgparser

**Comment by stek29** [comment]
here's an example of how to check this drift in shell:
```shell
echo "DMESGTIMEDRIFTTEST $(awk '{print$1}' /proc/uptime)" >/dev/kmsg; sleep 1; dmesg | grep DMESGTIMEDRIFTTEST | tail -1 | tr -d '[]' | awk '{ if ($3-$1 > 10) print "time drift: "$3-$1 }'
```

**Comment by stek29** [comment]
related issue in kmsg parser: euank/go-kmsg-parser#5
