### ISSUE TITLE
docker healthcheck - systemctl unable to get information

### ISSUE THREAD

**Issue by azman0101** [kubernetes/node-problem-detector#482]
When enabling health-checker for docker. The Unhealthy condition is detected when, in fact docker is healthy

```bash
I1026 18:25:35.879338       1 plugin.go:239] Start logs from plugin {Type:permanent Condition:ContainerRuntimeUnhealthy Reason:DockerUnhealthy Path:/home/kubernetes/bin/health-checker Args:[--component=docker --enable-repair=true --cooldown-time=2m --health-check-timeout=60s] TimeoutString:0xc000284ed0 Timeout:3m0s}
 I1026 18:25:35.876378      46 health_checker.go:166] command &{docker [docker ps] []  <nil>  0xc0000a02d0 [] <nil> <nil> <nil> 0xc00009c300 0xc0000a83c0 false [] [] [] [] <nil> <nil>} failed: exec: "docker": executable file not found in $PATH, []
I1026 18:25:35.878837      46 health_checker.go:166] command &{/bin/systemctl [systemctl show docker --property=InactiveExitTimestamp] []  <nil>  0xc0000a03c0 [] <nil> 0xc000094c90 exit status 1 0xc00009c420 <nil> true [0xc00009a058 0xc00009a070 0xc00009a088] [0xc00009a058 0xc00009a070 0xc00009a088] [0xc00009a068 0xc00009a080] [0x61a150 0x61a150] 0xc00009c6c0 0xc000082180} failed: exit status 1, []
I1026 18:25:35.878866      46 health_checker.go:147] error in getting uptime for docker: exit status 1
I1026 18:25:35.878875      46 health_checker.go:149] docker is unhealthy, component uptime: 0s
I1026 18:25:35.879398       1 plugin.go:240] End logs from plugin {Type:permanent Condition:ContainerRuntimeUnhealthy Reason:DockerUnhealthy Path:/home/kubernetes/bin/health-checker Args:[--component=docker --enable-repair=true --cooldown-time=2m --health-check-timeout=60s] TimeoutString:0xc000284ed0 Timeout:3m0s}
```

I tested the command `systemctl show docker --property=InactiveExitTimestamp` inside a npd container:

```bash
kubectl exec -it -n kube-system node-problem-detector-8z9lj -- /bin/sh

# systemctl show docker --property=InactiveExitTimestamp
System has not been booted with systemd as init system (PID 1). Can't operate.
```

To dig into this issue, I've added hostPID to pod spec.

```bash
kubectl exec -it -n kube-system node-problem-detector-28x7t -- /bin/sh
# systemctl show docker --property=InactiveExitTimestamp
Running in chroot, ignoring request: show
```

Also, the podspec .securityContext.privileged=true

I didn't see how this can work

**Comment by dntosas** [comment]
Having the same problem and Kubelet is always returning `Unknown` status ^^
```
Normal  KubeletIsHealthy         6m8s                   health-checker  Node condition KubeletUnhealthy is now: Unknown, reason: KubeletIsHealthy
```

```
KubeletUnhealthy              Unknown     KubeletIsHealthy                kubelet on the node is functioning properly
```

**Comment by Iamleos** [comment]
> ```shell
> /bin/syst
> ```



> When enabling health-checker for docker. The Unhealthy condition is detected when, I fact docker is healthy
> 
> ```shell
> I1026 18:25:35.879338       1 plugin.go:239] Start logs from plugin {Type:permanent Condition:ContainerRuntimeUnhealthy Reason:DockerUnhealthy Path:/home/kubernetes/bin/health-checker Args:[--component=docker --enable-repair=true --cooldown-time=2m --health-check-timeout=60s] TimeoutString:0xc000284ed0 Timeout:3m0s}
>  I1026 18:25:35.876378      46 health_checker.go:166] command &{docker [docker ps] []  <nil>  0xc0000a02d0 [] <nil> <nil> <nil> 0xc00009c300 0xc0000a83c0 false [] [] [] [] <nil> <nil>} failed: exec: "docker": executable file not found in $PATH, []
> I1026 18:25:35.878837      46 health_checker.go:166] command &{/bin/systemctl [systemctl show docker --property=InactiveExitTimestamp] []  <nil>  0xc0000a03c0 [] <nil> 0xc000094c90 exit status 1 0xc00009c420 <nil> true [0xc00009a058 0xc00009a070 0xc00009a088] [0xc00009a058 0xc00009a070 0xc00009a088] [0xc00009a068 0xc00009a080] [0x61a150 0x61a150] 0xc00009c6c0 0xc000082180} failed: exit status 1, []
> I1026 18:25:35.878866      46 health_checker.go:147] error in getting uptime for docker: exit status 1
> I1026 18:25:35.878875      46 health_checker.go:149] docker is unhealthy, component uptime: 0s
> I1026 18:25:35.879398       1 plugin.go:240] End logs from plugin {Type:permanent Condition:ContainerRuntimeUnhealthy Reason:DockerUnhealthy Path:/home/kubernetes/bin/health-checker Args:[--component=docker --enable-repair=true --cooldown-time=2m --health-check-timeout=60s] TimeoutString:0xc000284ed0 Timeout:3m0s}
> ```
> 
> I tested the command `systemctl show docker --property=InactiveExitTimestamp` inside a npd container:
> 
> ```shell
> kubectl exec -it -n kube-system node-problem-detector-8z9lj -- /bin/sh
> 
> # systemctl show docker --property=InactiveExitTimestamp
> System has not been booted with systemd as init system (PID 1). Can't operate.
> ```
> 
> To dig into this issue, I've added hostPID to pod spec.
> 
> ```shell
> kubectl exec -it -n kube-system node-problem-detector-28x7t -- /bin/sh
> # systemctl show docker --property=InactiveExitTimestamp
> Running in chroot, ignoring request: show
> ```
> 
> Also, the podspec .securityContext.privileged=true
> 
> I didn't see how this can work

I have apply node-problem detector, but it showed errors, like 
"command systemctl show kubelet --property=InactiveExitTimestamp failed: exec: "systemctl": executable file not found in $PATH"
We have the same images, why i got this problem.
