### ISSUE TITLE
Batch merging broken for this repo by use of PULL_NUMBER in scripts

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/node-problem-detector#495]
Prow is churning away running batch test jobs that fail llke this:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/batch/pull-npd-e2e-kubernetes-gce-gci/1328288484888154112
```
+ bash -c './test/build.sh -p $(PULL_NUMBER) pr && source pr.env && /workspace/scenarios/kubernetes_e2e.py --cluster= --extract=ci/latest --provider=gce --gcp-node-image=gci --gcp-zone=us-west1-b --ginkgo-parallel=30 --test_args=--ginkgo.focus=NodeProblemDetector --timeout=60m'
bash: PULL_NUMBER: command not found
```

This is probably part of why PRs don't appear to be merging while many are being tested for merge.
OTOH, it seems like tide / prow should be falling back to serial merges ...

@kubernetes/test-infra-maintainers xref https://github.com/kubernetes/test-infra/issues/13551

**Comment by tosi3k** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/19963.

/close
