### ISSUE TITLE
Change test/build.sh to use build ID

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/node-problem-detector#496]
In https://github.com/kubernetes/test-infra/pull/19963, to fix NPD batch merging, we switched to use BUILD_ID which is a unique ID every build.

With BUILD_ID, the logic tries to get PR number and add unique suffix is not in test/build.sh is not needed any more.

It just needs to accept the BUILD_ID.

The only potential problem is that if we make backward incompatible change in `test/build.sh` in master, the CI for other branches may be broken. We can configure different test jobs in test-infra for old branches and master.

**Comment by wangzhen127** [comment]
I think we only have CI for master branch right now.
