### ISSUE TITLE
Custom plugin monitor always states it timed out, even if cancelled correctly

### ISSUE THREAD

**Issue by nickhs** [kubernetes/node-problem-detector#520]
In https://github.com/kubernetes/node-problem-detector/blob/master/pkg/custompluginmonitor/plugin/plugin.go#L178 there is no check that the context was cancelled (via the `defer cancel()`) and the logs will keep incorrectly stating the plugin timed out.

I think you want to add a call to `Err()` in https://golang.org/pkg/context/#Context to check if the context is `Canceled` or `DeadlineExceeded` and only attempt killing the plugin on the later.

**Comment by nickhs** [comment]
Looks like this is noted in the PR at https://github.com/kubernetes/node-problem-detector/pull/456#discussion_r556493559.

**Comment by Random-Liu** [comment]
@ZYecho can you fix this?

**Comment by ZYecho** [comment]
will fix it.

**Comment by ihgann** [comment]
Just to be clear, is this to address the following error?

```
Feb 01 22:28:22 4229e6fc961d08d92f5d8522fbb73970 node-problem-detector[76420]: E0201 22:28:22.334132   76420 plugin.go:178] Error in running plugin timeout "/root/node-problem-detector/config/plugin/check_ntp.sh"
Feb 01 22:28:22 4229e6fc961d08d92f5d8522fbb73970 node-problem-detector[76420]: E0201 22:28:22.336340   76420 plugin.go:185] Error in kill process 78392, no such process
```

**Comment by ZYecho** [comment]
> Just to be clear, is this to address the following error?
> 
> ```
> Feb 01 22:28:22 4229e6fc961d08d92f5d8522fbb73970 node-problem-detector[76420]: E0201 22:28:22.334132   76420 plugin.go:178] Error in running plugin timeout "/root/node-problem-detector/config/plugin/check_ntp.sh"
> Feb 01 22:28:22 4229e6fc961d08d92f5d8522fbb73970 node-problem-detector[76420]: E0201 22:28:22.336340   76420 plugin.go:185] Error in kill process 78392, no such process
> ```

yep
