### ISSUE TITLE
Limit FileSystem ReadOnly detection to local disks

### ISSUE THREAD

**Issue by srgvg** [kubernetes/node-problem-detector#525]
Would be helpfull to have an option to limit FileSystem ReadOnly detection to local disks.

Using a Storage solution on kubernetes, that mounts PeristentVolumes via e.g.iSCSI on the node the pod that consulmes it,  runs on, resulting in e.g. an extra `/dev/sdb`, the problem detector would also trigger on that volume going ReadOnly. As that volume is really part of a pod (which could move to another node), it doesn't really say something about the node's health. Being able to exclude those disks, or perhaps better, to limit the detection to the initial local disks (only `/dev/sda` in my current situation) would be a good solution here.

If it could automagically by default only look at locally physically  attached harddisks, that would be better, but I'm not sure that is easy to define.

**Comment by Random-Liu** [comment]
The default config is just some recommendation config, it is not supposed to cover all cases.

https://github.com/kubernetes/node-problem-detector/blob/master/config/kernel-monitor.json

You can alter it as needed in your environment.

**Comment by srgvg** [comment]
I understand, thanks for your feedback. 

Probably due to my lack of enough understanding on how to configure this, I'm not sure how I would go about differentiating between the two types of disk, given the type of filters defined in the json you linked. 

What come to mind is adding the line including the specific disks names, hardcoded in the config. I'm not sure it would be easy to differentiate between different nodes and disk configurations, and cases where the reported disk name (e.g. /dev/sda) might not be persistent across reboots.
