### ISSUE TITLE
Node GPU Monitor

### ISSUE THREAD

**Issue by Iamleos** [kubernetes/node-problem-detector#546]
Hi, 
I want to monitor nvidia GPUs in k8s nodes. I have developed a node problem detector plugin by exec nvidia-smi command tools which is provided by NVIDIA. However, I got failure because the detector container has no nvidia-smi tool installed. And, I have a confusion. If I want  to develop my plugin by executing some commands, like "nvidia-smi -L". How should I do in developing plugins

**Comment by vteratipally** [comment]
For the problems which have to detected by running some commands, there are few examples [here](https://github.com/kubernetes/node-problem-detector/tree/master/config/plugin) i.e. by enabling the custom-plugin-monitor through NPD.
