### ISSUE TITLE
health check systemctl show time is not update after kill systemd service

### ISSUE THREAD

**Issue by smileusd** [kubernetes/node-problem-detector#548]
/kind bug

I add health-check in npd and it will restart kubelet if find any unhealthy status.
But when kubelet restart, the `getUptimeFunc`code in health-check still get the old start time.
I exec into the npd container and manually run `systemctl show kubelet --property=InactiveExitTimestamp`. The time was updated, but log in npd still be old.

**Comment by smileusd** [comment]
@Random-Liu PTAL

**Comment by spirosoik** [comment]
I can get this
