### ISSUE TITLE
NPD custom config script cannot be executed - permission denied

### ISSUE THREAD

**Issue by JosephGJ** [kubernetes/node-problem-detector#553]
Hi.

I'm attempting to deploy NPD with some custom config added to the custom config monitor. I'm deploying NPD using the official helm chart and I'm adding the following custom config to the helm chart to then be added to the ConfigMap in the helm chart. 

goss.json:
```
{
  "plugin": "custom",
  "pluginConfig": {
    "invoke_interval": "60s",
    "timeout": "10s",
    "max_output_length": 80,
    "concurrency": 3
  },
  "source": "health-checker",
  "metricsReporting": true,
  "conditions": [
    {
      "type": "GossCheckFailure",
      "reason": "GossCheckFailure",
      "message": "goss checks have failed"
    }
  ],
  "rules": [
    {
      "type": "temporary",
      "reason": "GossCheckIsFailing",
      "path": "./custom-config/goss.sh",
      "timeout": "3s"
    },
    {
      "type": "permanent",
      "condition": "GossCheckFailure",
      "reason": "GossCheckIsFailing",
      "path": "./custom-config/goss.sh",
      "timeout": "3s"
    }
  ]
}
```

goss.sh:
```
#!/bin/bash

readonly OK=0
readonly NONOK=1
readonly UNKNOWN=2

http_code=$(curl -s -I -o /dev/null -w '%{http_code}' localhost:8082/healthz)

if [[ $http_code -eq 200 ]]; then
    exit $OK
fi

exit $NONOK
```

The script in question curls the goss http endpoint to run the goss server checks to see that certain services / configuration is  working on the host (host networking is enabled in the helm chart). 

Unfortunately, the pods don't seem to be able to execute the script due to file permission issues.

Pod logs:
```
I0506 12:25:14.660582       1 custom_plugin_monitor.go:276] New status generated: &{Source:health-checker Events:[{Severity:warn Timestamp:2021-05-06 12:25:14.660562513 +0000 UTC m=+0.024513891 Reason:GossCheckIsFailing Message:Error in starting plugin. Please check the error log}] Conditions:[{Type:GossCheckFailure Status:False Transition:2021-05-06 12:25:14.659796141 +0000 UTC m=+0.023747537 Reason:GossCheckFailure Message:goss checks have failed}]}
E0506 12:25:14.660848       1 plugin.go:168] Error in starting plugin "./custom-config/goss.sh": error - fork/exec ./custom-config/goss.sh: permission denied
```

I've had a look around and it seems as though the file permissions of mounted ConfigMap files can be set through the kube manifest of the daemonset https://kubernetes.io/docs/concepts/configuration/secret/#secret-files-permissions

but this doesn't look to be configured in the helm chart? https://github.com/deliveryhero/helm-charts/blob/master/stable/node-problem-detector/templates/daemonset.yaml#L109 

Is this configuration something that can be added or is there some configuration option I'm missing? If this isn't something to be added, I'll have to look at baking the scripts into a custom NPD image.

**Comment by Lan-ce-lot** [comment]
@JosephGJ Hi, I think `chmod a+x` is all you need.
