### ISSUE TITLE
Support SSL certificates

### ISSUE THREAD

**Issue by yunjing** [kubernetes/node-problem-detector#59]
Our k8s API server is running with a self-signed certificate to enable SSL. I am wondering what's the best way to specify a root CA when running node-problem-detector.

**Comment by andyxning** [comment]
@yunjing with the newly added [`apiserver-override`](https://github.com/kubernetes/node-problem-detector#flags), you can choose to not use SSL when connecting to apiserver. :)

**Comment by Random-Liu** [comment]
@yunjing With the new `apiserver-override`, you can create a kubeconfig file with the certificate, and then run npd with the command:
```
--apiserver-override=https://MASTER_IP:MASTER_PORT?inClusterConfig=false&auth=YOUR_KUBE_CONFIG
```

The kubeconfig format is the same with the ones used by other components like kubelet. 
See https://kubernetes.io/docs/user-guide/kubeconfig-file/

**Comment by andyxning** [comment]
@Random-Liu @yunjing I think this issue can be closed for now. :)
