### ISSUE TITLE
Add RBAC in the example yaml file and document

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/node-problem-detector#61]
Default Kubernetes setup removed ABAC support, and is only using RBAC now.
https://github.com/kubernetes/kubernetes/pull/39092

This is fine for the NPD in kube-system, which has enough permission. However, the NPD setup in the example and Readme.md may not be enough.

We should add documentation and example to demonstrate how to deploy NPD in a RBAC K8s cluster.

**Comment by shyamjvs** [comment]
@Random-Liu I'm going to add node-problem-detector in kubemark using RBAC as we recently moved to RBAC in kubemark as well ([kubernetes/kubernetes/#39349](https://github.com/kubernetes/kubernetes/pull/39349)).
Once I get it working, I'll add a link to the PR here and it would be easier for you to then prepare example/readme.

**Comment by Random-Liu** [comment]
Cool, thanks a lot @shyamjvs

**Comment by shyamjvs** [comment]
@Random-Liu Is this still on? If yes, here's the example for the npd role-binding (the role already exists in bootstrapping, so needn't create) -> https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/resources/manifests/addons/kubemark-rbac-bindings/npd-binding.yaml
And for authenticating npd, here are the 2 things that one needs to do:
1. Create a bearer token (that you get if you create serviceaccount for npd or you can use default serviceaccount) or certificate or put static token in apiserver's token file (like here https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/start-kubemark.sh#L90). Other authentication modes can be neglected.
2. Make npd use kubeconfig with auth token/certificate created in the above step. Like here -> https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/start-kubemark.sh#L250.
