### ISSUE TITLE
Kernel monitor file is wrongly named in node-problem-detector.go

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/node-problem-detector#62]
The default path to the kernel monitor config in [node-problem-detector.go](https://github.com/kubernetes/node-problem-detector/blob/master/node_problem_detector.go#L30) is '/config/kernel_monitor.json'. However, the file in the config/ directory of the repo is named 'kernel-monitor.json' (hyphen at one place and underscore at the other). They need to be named the same.

cc @Random-Liu

**Comment by Random-Liu** [comment]
In fact, we don't really use the default path usually.
We always pass a `--kernel-monitor` flag to specify the kernel monitor config path.
However, we should change the default path to make it more useful, really. Thanks for your PR!
