### ISSUE TITLE
npd yaml failed in centos for journal path:  /run/log/journal not /var/log/journal

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/node-problem-detector#621]
https://github.com/helm/charts/issues/21817#issuecomment-611510731
### Root cause issue
On CentOS log path is /run/log/journal but by default use /var/log/journal
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/node-problem-detector/npd.yaml#L69-L88

/sig cloud-provider
/kind bug

### Fix
add in daemonSet

```
      volumes:
      - hostPath:
          path: /run/log/journal
          type: ""
        name: journal
```
and
```
       volumeMounts:
        - mountPath: /var/log/journal
          name: journal
```

# error messages

> I0926 19:38:38.481196       1 custom_plugin_monitor.go:276] New status generated: &{Source:systemd-monitor Events:[{Severity:info Timestamp:2021-09-26 19:38:38.481139626 +0800 CST m=+0.605519482 Reason:NoFrequentContainerdRestart Message:Node condition FrequentContainerdRestart is now: Unknown, reason: NoFrequentContainerdRestart}] Conditions:[{Type:FrequentKubeletRestart Status:Unknown Transition:2021-09-26 19:38:38.279765139 +0800 CST m=+0.404145014 Reason:NoFrequentKubeletRestart Message:error watching journald: failed to stat the log path "/var/log/journal": stat /v} {Type:FrequentDockerRestart Status:Unknown Transition:2021-09-26 19:38:38.382463904 +0800 CST m=+0.506843870 Reason:NoFrequentDockerRestart Message:error watching journald: failed to stat the log path "/var/log/journal": stat /v} {Type:FrequentContainerdRestart Status:Unknown Transition:2021-09-26 19:38:38.481139626 +0800 CST m=+0.605519482 Reason:NoFrequentContainerdRestart Message:error watching journald: failed to stat the log path "/var/log/journal": stat /v}]}

/cc @Random-Liu @wangzhen127

**Comment by L1ghtman2k** [comment]
adding this to helm is a bit of a hack, but solves my issue:
```
logDir:
  host: /run/log/
  pod: "/var/log/"
```

**Comment by fighterhit** [comment]
How to deal with this issue if some nodes in the cluster have `/var/log/journal` but others have `/run/log/journal`? BTW, the system of all nodes is `Debian GNU/Linux 10 (buster)`.
