### ISSUE TITLE
Account takeover of vendored dependency

### ISSUE THREAD

**Issue by tallclair** [kubernetes/node-problem-detector#626]
The github account @cobaugh no longer exists, and was taken over by a security researcher. Please replace this dependency before a vendor update can accidentally pull in a compromised version.

**Comment by tallclair** [comment]
(Note: this is not a direct vulnerability, since the vendored version is still valid - we just don't want to pull a new version)

**Comment by mx-psi** [comment]
Opened acobaugh/osrelease#2 to give more context about this.

**Comment by tallclair** [comment]
/remove-lifecycle rotten

Waiting for https://github.com/kubernetes/node-problem-detector/pull/628 to merge.
