### ISSUE TITLE
How to solve the problem about x509 k8s-exportor can't get node object when I deploy NPD in binary?

### ISSUE THREAD

**Issue by harryyann** [kubernetes/node-problem-detector#632]
When I deploy the node-problem-detector in binary on one of  the nodes in my cluster，I got this problem that seems like an authentication problem：
```
k8s_exporter.go:111] Can't get node object: Get https://.../api/v1/nodes/...: x509: certificate signed by unknown authority
```
Would anyone not mind to tell me why I got this problem and how to solve it?

**Comment by martinhmuenster** [comment]
If it's a standalone deployment, try including insecure=true to the api-server-override flag:
`--apiserver-override="https://ip:port?inClusterConfig=false&useServiceAccount=true&insecure=true"`
Other thing you could check is that the service account is created and that its token is in the correct folder on the node.
