### ISSUE TITLE
node conditions update correctly but taints never apply to the node

### ISSUE THREAD

**Issue by JSC0DE** [kubernetes/node-problem-detector#640]
Hi, 

Im not finding any answers online to help me with my issue and hope someone here could help me 😉 please.

  I understand that node problem detector is not responsible for applying taints and the feature gate for TaintNodesByCondition must be enabled, In order to allow kubernetes control plane processes to taint node based on reported node conditions. Reading the documention for Kubernetes says TaintNodesByCondition enabled by default from 1.17 [K8S DOC](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#:~:text=1.16-,TaintNodesByCondition,-true)
  
I am working on eks 1.21 and it also say that TaintNodesByCondition is on by default [AWS DOC](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html#:~:text=On%20this%20page-,Kubernetes%20version%201.21,-Kubernetes%20version%201.20)

I have deployed node problem detector to the cluster using the helm chart, and I went to test it with the following command via ssh on a node. 

```sh
sudo sh -c "echo 'kernel: INFO: task docker:20744 blocked for more than 120 seconds.' >> /dev/kmsg"
```
It resulted in 

```sh
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  KernelDeadlock       True    Tue, 01 Feb 2022 23:03:41 +0000   Tue, 01 Feb 2022 23:03:40 +0000   DockerHung                   kernel:  INFO: task docker:20744 blocked for more than 120 seconds.`
```

Which looks perfect🍾, However the node taint remains ```Taints: <none>``` Which now blocks use us from using descheduler.

 Any help would be greatly received as to why or what I have missed to cause taints not to happen.
 
 Anyone got any guidance for node problem detector on aws eks or eks gotchas

**Comment by tdihp** [comment]
The current "TaintNodesByCondition" admission controller in k8s actually doesn't do what the name indicates, it simply add a taint at node creation, [see the comment in code](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/plugin/pkg/admission/nodetaint/admission.go#L79).

The README approach using Descheduler's "RemovePodsViolatingNodeTaints" feature seems to be gapped by not having an actor by adding a taint.

**Comment by rbjorklin** [comment]
I have arrived at the same conclusion. It seems like `TaintNodesByCondition` only applies to a few hard-coded conditions and can not be extended in its current state.

https://github.com/kubernetes/kubernetes/issues/42001

**Comment by rhockenbury** [comment]
Looks like a dup of #457.  There's an (old) related PR #565 to resolve.

**Comment by jhohertz** [comment]
Okay it's not just me then. :sweat:
