### ISSUE TITLE
Replace uses of systemctl/journalctl with the github.com/coreos/go-systemd library

### ISSUE THREAD

**Issue by wjam** [kubernetes/node-problem-detector#648]
This tool appears to be in an odd half-way house where it both uses the `github.com/coreos/go-systemd` library for parsing log messages in the log-counter binary, but then depends on the `systemctl` & `journalctl` binaries to be installed in the health-check binary. This has led to further problems where these binaries aren't baked into the standard image (see #592, #584, #548 et al) causing the health check to fail when attempted to be called [1].

It seems like the uses of the external binaries should be replaced with calls to the library, and the `health-checker-kubelet.json` rule changed to work when inside a pod (so disable `enable-repair`).

[1] Note that even if these binaries were baked into the image, they will still be unlikely to work when the tool is deployed as a DaemonSet because the pods won't have access to the host systemd by default and systemctl will complain that it is being run in a chroot environment.

**Comment by wjam** [comment]
It's also worth using the `k8s.io/cri-api` Go API directly rather than assuming https://github.com/kubernetes-sigs/cri-tools is baked into the image.

Removing these binaries would mean being able to use a Distroless image?

**Comment by btiernay** [comment]
@Random-Liu Curious to get your thoughts on the proposal. Given all the issues with running `systemctrl` in a container, perhaps this is an elegant solution to the current set of missing binaries and poor DaemonSet experiences ([example](https://github.com/kubernetes/node-problem-detector/issues/439)). It also makes it more friendly to other OS's such as Bottlerocket which make it more challenging to run such workloads outside of a container.
