### ISSUE TITLE
when the network interfaces come and go metric cardinality grows unbounded

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/node-problem-detector#659]
Calico creates network interfaces for each pod with the unique name. Collecting net metrics (like `kubernetes.io/internal/node/guest/net/tx_packets`) uses the interface name as a dimension `interface_name`. OpenCensus go library has no bounds for the metric cardinality and doesn't allow to clean up old values. 

Need to find a best way to reset label values for net interfaces that don't exist any longer.

**Comment by mmiranda96** [comment]
For cases such as Calico, do we want to keep metrics for each individual interface? If not, a viable alternative would be to group these interfaces within the same dimension. We can use a config model like this:
```json
"net": { 
  "interfaceGroupings": {
    [
      "name": "calico",
      "groupRegexp": "^cali[0-9a-f]+$"
    ]
  }
}
```

In the implementation, we would aggregate all interfaces that match the regex under the same name. Interfaces that don't match any grouping will be reported independently.

**Comment by SergeyKanzhelev** [comment]
I'm not sure how useful this metric is. If we want to keep it - the best long term solution would be to switch to OpenTelemetry delta metrics and use this exporter: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/tree/main/exporter/metric.

@dashpole do you think OpenTelemetry is in a good state to adopt it here for metrics?

**Comment by dashpole** [comment]
The Metrics SDK is currently being (entirely) rewritten in preparation for the first stable release, so I wouldn't recommend it right now.  That effort is tracked in https://github.com/orgs/open-telemetry/projects/22.  After that is published, we will adapt the GCM exporter and publish a stable release of that as well.

**Comment by mmiranda96** [comment]
This issue has been fixed via https://github.com/kubernetes/node-problem-detector/pull/675. This fix has been released in https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.11.

/remove-lifecycle stale
/close
