### ISSUE TITLE
Is the forcible heartbeat mechanism necessary?

### ISSUE THREAD

**Issue by lianghao208** [kubernetes/node-problem-detector#661]
We found `heartbeatPeriod` will periodically update node conditions even there is no update event of nodes.
```go
// needHeartbeat checks whether a forcible heartbeat is needed.
func (c *conditionManager) needHeartbeat() bool {
	return c.clock.Since(c.latestTry) >= c.heartbeatPeriod
}
```
In a large cluster(over 3000 nodes), this might cause high cpu and network traffic usage on node in every `heartbeatPeriod`
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/14137033/160616250-3b501fda-90d3-48de-bc55-aff97ef7a713.png">

Is this forcible heartbeat mechanism necessary when we already have update mechanism once nodes' status change?

```go
// needUpdates checks whether there are recent updates.
func (c *conditionManager) needUpdates() bool {
	c.Lock()
	defer c.Unlock()
	needUpdate := false
	for t, update := range c.updates {
		if !reflect.DeepEqual(c.conditions[t], update) {
			needUpdate = true
			c.conditions[t] = update
		}
		delete(c.updates, t)
	}
	return needUpdate
}
```

**Comment by Random-Liu** [comment]
>Is this forcible heartbeat mechanism necessary when we already have update mechanism once nodes' status change?

The force heartbeat is to prevent something changes the conditions NPD owns by mistake.

The heartbeat period is configurable.
