### ISSUE TITLE
CustomPluginMonitor should support multiple "permanent" rules for the same node condition.

### ISSUE THREAD

**Issue by jason1028kr** [kubernetes/node-problem-detector#664]
Hello,

This is to reopen plan/discussion around an issue where CustomPluginMonitor behaves in an unexpected way (https://github.com/kubernetes/node-problem-detector/issues/566).

In short, when there are multiple rules for the same condition in configuration, the NPD will generate events for all of them causing the condition to flip-flop.

## Current behavior
Described in https://github.com/kubernetes/node-problem-detector/issues/566

## Suggestions/Ideas
As discussed in the original issue, I believe it would be reasonable for CustomPluginMonitor to behave in this way.
- Produce one event for each condition.
- If different rules for a condition return both `NonOK/True` and `OK/False`, resolve to the "worst" case (condition is `NonOK/True`). 
- If multiple rules evaluate to `NonOK/True`, current condition's reason/rule (`NonOK/True`) takes precedence. If it just so happens that the particular reason/rule returns `OK/False` in current interval, we can take the first rule that evaluates to `NonOK/True`.

**Comment by Random-Liu** [comment]
> In short, when there are multiple rules for the same condition in configuration, the NPD will generate events for all of them causing the condition to flip-flop.

In this case, instead of complicating the NPD logic, why couldn't the user consolidate the 2 plugins with 1 entrypoint, and only configure one rule instead?

**Comment by jason1028kr** [comment]
Hi @Random-Liu! The idea was that for certain set of rule/plugins that are mutually exclusive, user would only observe one node condition/event per interval.

**Comment by jason1028kr** [comment]
If by consolidating you mean having 1 plugin script generating multiple results, I would probably have to expand `result.ExitStatus >= cpmtypes.NonOK`. But not sure how to do that in a generalized way that is not specific to 1 usecase.

**Comment by Random-Liu** [comment]
Hm, after looking at the examples in https://github.com/kubernetes/node-problem-detector/issues/566, it does make sense to me.

The current rule is defined at the condition level, to get the `reason` information, we either need to extend the config, or the plugin interface. Since plugin interface is just exit code + stdout/stderr, it seems better to extend this at the config level.

**Comment by jason1028kr** [comment]
@Random-Liu ah I see, yes there should be some agreed way of consolidating different results.

For your comment `"And for other problems with different Reasons, you can just setup different conditions for them?"`, this is actually our current set up. The only issue is that more than one (condition+reason) pair could resolve to true, and we want some conditions to be mutually exclusive.

If by `'get that from the custom plugin directly'` you mean the plugin script, the output is currently put in the 'message' field of the type 'Result' ```type Result struct {
	Rule       *CustomRule
	ExitStatus Status
	Message    string
}```. 

Wouldn't changing this behavior a bigger design change, since we won't be taking the 'reason' field from the json, but instead from the script output.

**Comment by jason1028kr** [comment]
Also, to support the case for 'multiple rules per condition,'
'systemLogMonitor' currently supports 'multiple rules per condition'. Once condition resolves to true, it will simply flip reason/rule as different logs come in to the channel. The reason it doesn't have the 'flip-flop' problem is b/c the node condition doesn't get reset to false when the rules per condition all resolve to false.

The pr that I have also updates the reason as the result comes into the channel, but supports resetting the condition to false without flipflopping.

**Comment by jason1028kr** [comment]
@Random-Liu Let me know what you think, and if my comments make sense!

**Comment by BusyOppo** [comment]
One rule with one script with multiple exitcode value mapping to different Reason via new Rule setting 
`reasonMapping: {
0: `NTPIsUp`,
1: `NTPIsDown`
2: `NTPIDontCare`
}

**Comment by jason1028kr** [comment]
@BusyOppo I see, make sense. I'll make a pr or supporting the behavior. It'll change cpm behavior abit, but the right way to address the multiple rules issue.

**Comment by jason1028kr** [comment]
@Random-Liu, does enabling the 'reasonMapping' above for multiple(3+) exitcode-reason pairing appropriate? I've wanted to confirm if that is the right direction.
