### ISSUE TITLE
health-checker posting wrong status for kubelet - KubeletUnhealthy

### ISSUE THREAD

**Issue by rotarur** [kubernetes/node-problem-detector#666]
Health-checker is reporting wrong status for kubelet.
```
Type    Reason                   Age   From            Message
  ----    ------                   ----  ----            -------
  Normal  KubeletUnhealthy         12m   health-checker  Node condition KubeletUnhealthy is now: True, reason: KubeletUnhealthy
  Normal  KubeletUnhealthy         103s  health-checker  Node condition KubeletUnhealthy is now: True, reason: KubeletUnhealthy
```

Although the kubelet is running in the node and from the node-problem container I can see the same result:
```
● kubelet.service - Kubernetes Kubelet
     Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubelet-args.conf, 30-kubelet-extra-args.conf
     Active: active (running) since Tue 2022-04-19 07:46:28 UTC; 3min 42s ago
       Docs: https://github.com/kubernetes/kubernetes
    Process: 13834 ExecStartPre=/sbin/iptables -P FORWARD ACCEPT -w 5 (code=exited, status=0/SUCCESS)
   Main PID: 13838
      Tasks: 26
     Memory: 61.8M
     CGroup: /system.slice/kubelet.service
```

If I run manually the script `/home/kubernetes/bin/health-checker` it gives the error that the kubelet is not running.

**Comment by wxuedong** [comment]
> Health-checker is reporting wrong status for kubelet.
> 
> ```
> Type    Reason                   Age   From            Message
>   ----    ------                   ----  ----            -------
>   Normal  KubeletUnhealthy         12m   health-checker  Node condition KubeletUnhealthy is now: True, reason: KubeletUnhealthy
>   Normal  KubeletUnhealthy         103s  health-checker  Node condition KubeletUnhealthy is now: True, reason: KubeletUnhealthy
> ```
> 
> Although the kubelet is running in the node and from the node-problem container I can see the same result:
> 
> ```
> ● kubelet.service - Kubernetes Kubelet
>      Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
>     Drop-In: /etc/systemd/system/kubelet.service.d
>              └─10-kubelet-args.conf, 30-kubelet-extra-args.conf
>      Active: active (running) since Tue 2022-04-19 07:46:28 UTC; 3min 42s ago
>        Docs: https://github.com/kubernetes/kubernetes
>     Process: 13834 ExecStartPre=/sbin/iptables -P FORWARD ACCEPT -w 5 (code=exited, status=0/SUCCESS)
>    Main PID: 13838
>       Tasks: 26
>      Memory: 61.8M
>      CGroup: /system.slice/kubelet.service
> ```
> 
> If I run manually the script `/home/kubernetes/bin/health-checker` it gives the error that the kubelet is not running.

I had the same problem, how did you solve it 😂

**Comment by wxuedong** [comment]
Later versions will fix 
code version commit 51508603febbc7469481fafcb747402718aaa58e

temporary fix:

```
FROM k8s.gcr.io/node-problem-detector/node-problem-detector:v0.8.9

RUN clean-install \
        curl \
        systemd \
        docker.io
```

**Comment by seb-kw** [comment]
Same problem here when installed via helm...
