### ISSUE TITLE
Add --hostname-override flag.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/node-problem-detector#68]
Currently NPD gets hostname override from `NODE_NAME` env. https://github.com/kubernetes/node-problem-detector/blob/master/pkg/problemclient/problem_client.go#L73

This is not friendly for standalone mode.

We should add a `--hostname-override` flag, and set the flag with `NODE_NAME` from downward api in the yaml file. https://github.com/kubernetes/node-problem-detector/blob/master/node-problem-detector.yaml#L21

**Comment by andyxning** [comment]
@Random-Liu I suppose sticking with `NODE_NAME`  for node-problem-detector wherever it is running. This makes the command line consistent when running  node-problem-detector in both situation. :)

We may need to add more clear info about this behavior in README.md instead of only recording it in CHANGELOG.md. 

Today we may use `systemd` or other process manager tools to manager npd daemon. We can simple wrap npd in a shell script where a `NODE_NAME` environment variable should be customized and exported when needed.

**Comment by shyamjvs** [comment]
I agree with @andyxning on this. Adding a --hostname-override flag wouldn't really help much as we would need to provide the value for the flag most probably through an env variable anyway if we do not know the node name statically. For instance a replication controller for a pod in which the npd is a container, so you pretty much don't know the name of a specific replica. An example of this is the kubemark [hollow-node](https://github.com/shyamjvs/kubernetes/blob/25c5430e50384babb83f018836193a1fc8893d69/test/kubemark/resources/hollow-node_template.json#L153).

**Comment by Random-Liu** [comment]
@andyxning @shyamjvs 
For DaemonSet, if we configure the pod to use HostNetwork, we can also let the pod to use os.Hostname.
For Standalone, if kubelet registers the node with --hostname-override, we need to change the hostname NPD using, too.

So in fact, there is no much difference between DaemonSet and Standalone on the hostname setting. That's why I prefer a --hostname-override flag which explicitly overrides the hostname. Environment variable doesn't seem to be a good user interface. :)

**Comment by shyamjvs** [comment]
> I prefer a --hostname-override flag which explicitly overrides the hostname and has clear description when we run help command. Environment variable doesn't seem to be a good user interface to me. :)
sgtm

**Comment by andyxning** [comment]
Sounds reasonable. @Random-Liu I think i can add this functionality and at the same time adding more docs about `--hostname-override` in README by updating #72

**Comment by Random-Liu** [comment]
@andyxning Sure, thanks! Will review it as soon as you finish. :)

**Comment by Random-Liu** [comment]
Close this since https://github.com/kubernetes/node-problem-detector/pull/78 is merged.
