### ISSUE TITLE
Structured logging

### ISSUE THREAD

**Issue by michalschott** [kubernetes/node-problem-detector#680]
Since support for JSON log format is pretty a standard these days, would be nice to have this implemented in here too.

**Comment by william-salt-cko** [comment]
As this uses glog, it will only output to stderr or to a file by default. If you are using something like datadog, or any log processing pipeline, you can do something [like this](https://docs.datadoghq.com/logs/log_configuration/parsing/?tabs=matchers#glog-format) to post process the logs into a structured format. Not ideal, but I don't think k8s are going to change lots of components from glog to something more sane any time soon. 🙂 🙁

**Comment by michalschott** [comment]
Indeed, but maybe switching from glog to something which supports structured logging is an option?
