### ISSUE TITLE
node-problem-detector's version of client-go does not reload client certificates

### ISSUE THREAD

**Issue by chrisayoub** [kubernetes/node-problem-detector#694]
The client-go version used here is too old, so when running node-problem-detector using a kubeconfig which utilizes client certificates, these do not automatically rotate.

This is the PR that adds this functionality in Kubernetes 1.18:
https://github.com/kubernetes/kubernetes/pull/79083

I am requesting the client-go version here (and other required deps) be bumped to pick up this fix from 2020. I attempted to do so myself, but Go dependencies are quite complicated and intertwined.

**Comment by MartinForReal** [comment]
the client-go is bumped to 1.28.1 in https://github.com/kubernetes/node-problem-detector/pull/793.

**Comment by MartinForReal** [comment]
Can I close this issue? @chrisayoub  @PaulFurtado
