### ISSUE TITLE
amd64 binary of v0.8.12 requires glibc 2.32

### ISSUE THREAD

**Issue by aldudko** [kubernetes/node-problem-detector#725]
It looks like the amd64 binary in the v0.8.12 release assets was not built with CGO_ENABLED=0
The binary requires GLIBC_2.32.

Steps to reproduce:
```
➤ wget https://github.com/kubernetes/node-problem-detector/releases/download/v0.8.12/node-problem-detector-v0.8.12-linux_amd64.tar.gz
➤ tar -xzf node-problem-detector-v0.8.12-linux_amd64.tar.gz
➤ ./bin/node-problem-detector
./bin/node-problem-detector: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./bin/node-problem-detector)
```

**Comment by AlisonB319** [comment]
I am experiencing this issue as well in 0.8.13

**Comment by AlisonB319** [comment]
I was able to repro this fix on my own by creating the tar file from an 18.04 ubuntu VM. It would be helpful if an 18.04 release version was available as well.

**Comment by bilalcaliskan** [comment]
is there any update on it? still get the same error after built Docker image.

```
/node-problem-detector: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /node-problem-detector)
/node-problem-detector: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /node-problem-detector)
```

**Comment by waney316** [comment]
> is there any update on it? still get the same error after built Docker image.
> 
> ```
> /node-problem-detector: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /node-problem-detector)
> /node-problem-detector: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /node-problem-detector)
> ```

have you solved it?
