### ISSUE TITLE
Requesting a new latest release of NPD

### ISSUE THREAD

**Issue by bhope** [kubernetes/node-problem-detector#737]
We are looking to update the OS image  of node problem detector. The change is already in current master - https://github.com/kubernetes/node-problem-detector/blob/b586bd9231ee90dc1c9b8afe1e2281b638d5571e/Makefile#L78

We wanted to request for a new latest stable release with Debian as base image.

**Comment by mmiranda96** [comment]
Looks like v0.8.13 already contains the fix: https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.13

Closing this issue now.
/close
