### ISSUE TITLE
The readme suggests that this project can be used with kubernetes/descheduler but that is not possible

### ISSUE THREAD

**Issue by bbatha** [kubernetes/node-problem-detector#741]
The README clearly states:

> Descheduler strategy RemovePodsViolatingNodeTaints evicts pods violating NoSchedule taints on nodes. The k8s scheduler's TaintNodesByCondition feature must be enabled. The Cluster Autoscaler can be used to automatically terminate drained nodes.

However, the `TaintNodesByCondition` [feature only applies to the conditions that are built into kubernetes](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-nodes-by-condition) and not custom ones like the ones set by this project. [Features to add taints based on custom conditions](https://github.com/kubernetes/node-problem-detector/pull/565) on this project have been rejected. Please update the docs to make it clear these projects cannot be used together.

**Comment by btiernay** [comment]
> https://github.com/kubernetes/node-problem-detector/pull/565 on this project have been rejected.

I’m not sure that’s entirely accurate based on my reading. It appears as though it has support and being worked on.

**Comment by bbatha** [comment]
That pr was recently reopened from the thread it seemed the project maintainers disagreed with the direction. 

Regardless this feature does not currently exist. Thus the docs should be updated to reflect the current features of the project or at least note that it is a planned feature and not currently supported.

**Comment by btiernay** [comment]
> That pr was recently reopened from the thread it seemed the project maintainers disagreed with the direction.

I think there may have been earlier on, but it sounds like so long as it is disabled by default and is opt-in, it may be a workable model, at least to some maintainers.

> Regardless this feature does not currently exist. Thus the docs should be updated to reflect the current features of the project or at least note that it is a planned feature and not currently supported.

No argument here. Similar update was done [here on the Descheduler side for the same reason](https://github.com/kubernetes-sigs/descheduler/commit/328c695141b736cf9b222a1b1738f1beea331c69):

**Comment by wangzhen127** [comment]
It looks like the descheduler documentation has been updated. Regarding https://github.com/kubernetes/node-problem-detector/pull/565, I agree with @Random-Liu about it is better for another controller to apply taints as it has application layer impact.

I am closing this issue since it has been clarified that descheduler has a feature to apply taints based on node condition already.

/close
