### ISSUE TITLE
Failed to validate windows-system-stats-monitor.json configuration: ProcPath /proc check failed

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/node-problem-detector#747]
I noticed this issue when I was running NPD on Windows: when trying to run `systemstatsmonitor`, I get the following failure:
```
Failed to validate C:\node-problem-detector\config\windows-system-stats-monitor.json configuration [BIG JSON]: ProcPath /proc check failed: CreateFile /proc: The system cannot find the file specified.
```

After digging for a while, I found that this failure comes from https://github.com/kubernetes/node-problem-detector/blob/6e57ca6e6c0135ff4a73788e28563476ed9c9334/pkg/systemstatsmonitor/types/config.go#L138
It seems that we try to check the proc file on all platforms, and this is a problem because it doesn't apply for Windows.

This change was introduced in https://github.com/kubernetes/node-problem-detector/pull/594.

There are a couple of fixes I can think of:
- Entirely removing the check: simplest fix, could cause an issue if the user provides a wrong directory.
- Disabling the default `/proc` value (https://github.com/kubernetes/node-problem-detector/blob/6e57ca6e6c0135ff4a73788e28563476ed9c9334/pkg/systemstatsmonitor/types/config.go#L111) and skipping the check if it's empty: will fail if user doesn't explicitly provide a directory.
- Defining a specific value to skip validation (something like "undefined"): depending on a magic string is not always a good idea, and this value is kind of arbitrary.
- Splitting validation logic between Windows and Linux: requires splitting logic but is the cleanest option.

**Comment by samuelkarp** [comment]
> Disabling the default /proc value 

We can also conditionally have a default value based on the operating system.  This can be done by a conditional with [`runtime.GOOS`](https://pkg.go.dev/runtime#pkg-constants) or by moving the declaration out to two separate files (a `config_linux.go` and a `config_windows.go`).

```go
if runtime.GOOS == "linux" && ssc.ProcPath == "" {
	ssc.ProcPath = defaultProcPath
}
```
