### ISSUE TITLE
Incorrect parsing of ksmg messages with continuation lines

### ISSUE THREAD

**Issue by stek29** [kubernetes/node-problem-detector#751]
currently expr matching needs to match until end of text:
https://github.com/kubernetes/node-problem-detector/blob/9fd58e318ff6c4e06b4a50094245ab22f4040c77/pkg/systemlogmonitor/log_buffer.go#L65-L67

ksmg log watcher removes ending newline, but doesn't remove newlines in between the message itself.

for example, here are messages I want to match:
```
I0505 00:40:26.905993       1 log_watcher_linux.go:108] got kernel message: {Priority:3 SequenceNumber:114864 Timestamp:2023-05-05 00:40:17.630052342 +0300 MSK m=+395.145047298 Message:mlx5_core 0000:31:00.0 ens2f0: Recovered 1 eqes on EQ 0x3b
 SUBSYSTEM=pci
 DEVICE=+pci:0000:31:00.0
}
```

judging from kernel docs:
https://www.kernel.org/doc/Documentation/ABI/testing/dev-kmsg

> The human readable text string starts directly after the ';'
> and is terminated by a '\n'. Untrusted values derived from
> hardware or other facilities are printed, therefore
> all non-printable characters and '\' itself in the log message
> are escaped by "\x00" C-style hex encoding.
> 
> A line starting with ' ', is a continuation line, adding
> key/value pairs to the log message, which provide the machine
> readable context of the message, for reliable processing in
> userspace.
> 
> Example::
> 
> 	7,160,424069,-;pci_root PNP0A03:00: host bridge window [io  0x0000-0x0cf7] (ignored)
> 	SUBSYSTEM=acpi
> 	DEVICE=+acpi:PNP0A03:00
> 	6,339,5140900,-;NET: Registered protocol family 10
> 	30,340,5690716,-;udevd[80]: starting version 181

so it looks like those parts should be ignored by ksmg parser, but they're not

because of this you have to write kmsg matchers with `[\S\s]*` in the end instead of `.*` -- since regexp is not instantiated with flag `s=true`.

I'm not sure on what should the fix be, but at least:
1) kmsg-parser should be fixed to handle continuation line with kv pairs correctly https://github.com/euank/go-kmsg-parser
2) probably regex should be instantiated with s=true flag

**Comment by stek29** [comment]
this is still an issue afaik

**Comment by stek29** [comment]
this is still an issue

**Comment by Bharadwajshivam28** [comment]
Hey @stek29 If no one is working on this then I can take on this but I need some more details and steps to reproduce issue and get started
