### ISSUE TITLE
Standalone NPD Support

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/node-problem-detector#76]
For better reliability, in Kubernetes 1.6, we plan to add standalone NPD support to run NPD as a system daemon on each node.

To achieve this, we need to:
- [x] Add `apiserver-override` option to make it possible to use customized client config instead of `InClusterConfig`. https://github.com/kubernetes/node-problem-detector/pull/49
- [x] Make NPD wait for: https://github.com/kubernetes/node-problem-detector/pull/79
  * Apiserver to come up. https://github.com/kubernetes/node-problem-detector/issues/19
  * Kubelet to register node.
This is necessary, because in standalone mode, NPD may be deployed before apiserver and kubelet are functioning. It should wait for them to come up.
- [x] NPD should host a simple http server for readiness check and health monitor. #83
  * Requred: Add /health for health monitoring.
  * Optional: Add /pprof for performance debugging.
  * Optional: Add debug endpoint to list internal state.
  * Optional: Add grpc problem report endpoint.
- [x] Resource Limit
  - [x] Get benchmark data about the NPD resource usage https://github.com/kubernetes/node-problem-detector/issues/85
  - [x] ~~~Adjust `NodeAllocatable` according to the resource usage accordingly.~~~
- [x] Add standalone NPD into K8s GCI cloud init script. https://github.com/kubernetes/kubernetes/pull/40206
  - [x] Package NPD binary as tar ball and upload it to google storage. https://github.com/kubernetes/node-problem-detector/pull/71, https://github.com/kubernetes/node-problem-detector/pull/74
  - [x] Download and setup NPD binary in K8s GCI cloud init script.
- [x] NPD should have a specific user account which has necessary permission in K8s cluster. Similar with [`system:kube-proxy`](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-role-bindings.yaml#L90).

**Comment by andyxning** [comment]
@random-liu i may give the third one `NPD should host a simple http server for readiness check and health monitor` a try. :)

I am only familar with [docker distribution's health package](https://github.com/docker/distribution/tree/master/health). It can take item 1 and item 3 with endpoints being `/debug/health`. item 2 can be accomplished by import `net/http/pprof` package. 

I am not familiar with grpc problem report endpoint. Could you please detail it? :)

**Comment by Random-Liu** [comment]
@andyxning Thanks a lot!

> I am only familar with docker distribution's health package. It can take item 1 and item 3 with endpoints being /debug/health.

I think we need 2 endpoints:
* `/health`: Just return 200 to indicate that NPD is still running. We can do more health check in the future, but for now, only return 200 is good enough.
* `/conditions`: List all the current conditions in condition manager https://github.com/kubernetes/node-problem-detector/blob/master/pkg/condition/manager.go.
* `/debug/pprof`: Just import `net/http/pprof`.

> I am not familiar with grpc problem report endpoint. Could you please detail it? :)

We may want to expose a grpc problem report endpoint, which other problem monitoring tool can report problem to. The priority is relatively low, so we can work on the previous 3 first.

**Comment by shyamjvs** [comment]
>  Add apiserver-override option to make it possible to use customized client config instead of InClusterConfig. #49

@Random-Liu I think we should uncheck this item in the checklist until we merge the heapster vendor code and ensure that InClusterConfig is really working properly.

**Comment by Random-Liu** [comment]
@shyamjvs Current implementation is enough for standalone NPD, so for this issue we can check it.

How about we keep on tracking the issue in https://github.com/kubernetes/node-problem-detector/issues/73?

**Comment by Random-Liu** [comment]
All finished, close this issue.

**Comment by shyamjvs** [comment]
Hurray! Congrats :)
