### ISSUE TITLE
Fix or reduce frequency or switch off perma-failing jobs

### ISSUE THREAD

**Issue by dims** [kubernetes/node-problem-detector#762]
Data as of June 3rd, 9:00 PM Eastern. Latest data can be found here:
http://storage.googleapis.com/k8s-metrics/failures-latest.json

Additional Context:
https://github.com/kubernetes/test-infra/issues/18600

| CI Job | Days Failed |
| --- | --- |
| node-problem-detector-push-images |  324 |                                          
| pull-npd-e2e-kubernetes-gce-ubuntu-custom-flags |  45 |                                            
| ci-npd-e2e-kubernetes-gce-ubuntu |   32 |                                            
| ci-npd-e2e-kubernetes-gce-ubuntu-custom-flags |  32                                              
| pull-npd-e2e-kubernetes-gce-ubuntu  |  32  |

**Comment by hakman** [comment]
@dims I don't see npd in the list anymore. Could we close for now?

**Comment by dims** [comment]
/close

thanks @hakman
