### ISSUE TITLE
After installing the npd plugin on the node, the account is not locked after entering the wrong password 5 continually

### ISSUE THREAD

**Issue by wonbin2011** [kubernetes/node-problem-detector#787]
![image](https://github.com/kubernetes/node-problem-detector/assets/7733385/7464671a-2365-43db-a991-f0a5f1e77b78)

**Comment by wonbin2011** [comment]
sudo nsenter --mount=/host/proc/1/task/1/ns/mnt vgs -o vg_name,vg_attr | grep "vg-everest-localvolume-ephemeral" | awk '{print $2}' 
this line caused the problem

**Comment by mmiranda96** [comment]
NPD itself will not change any of the system configuration files, it just runs as another daemon. How are you installing NPD?

It seems that you're using specific cloud provider instructions, I recommend that you check with your cloud provider.

**Comment by wonbin2011** [comment]
> NPD itself will not change any of the system configuration files, it just runs as another daemon. How are you installing NPD?
> 
> It seems that you're using specific cloud provider instructions, I recommend that you check with your cloud provider.

yes, the  npd daemonset  mount host's   /run/  cause the problem.   "sudo" command would  refresh  /var/run/faillock/root  file
