### ISSUE TITLE
Disk and memory percent used

### ISSUE THREAD

**Issue by kasbert** [kubernetes/node-problem-detector#822]
Would you consider adding /disk/percent_used and /memory/percent_used ?
I know you can calculate these from other values, but it would be convenient to have them directly.
I hope they would some day be present in Google COS and you could create metrics and alarms based on them.

**Comment by xiaods** [comment]
PR welcome

**Comment by AndreMiras** [comment]
Addressed in https://github.com/kubernetes/node-problem-detector/pull/825
