### ISSUE TITLE
Intel binary present on the ARM

### ISSUE THREAD

**Issue by Marta-Panfilova-ASL** [kubernetes/node-problem-detector#827]
We are getting following error from NPD in our nodes `/bin/sh: 1: exec: /node-problem-detector: Exec format error`

Crashing because of Intel/AMD 64bit binary present on aarch64/ARM64 docker image. 

`root@:/# file node-problem-detector 
node-problem-detector: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=bd9bd59069612b94e84e1c60d73ebf61d618cd44, for GNU/Linux 3.2.0, with debug_info, not stripped`

`root@:/# unae me -a
Linux 654213c1a942 6.4.16-orbstack-00105-g14094bfeec09 #1 SMP Mon Sep 18 21:45:38 UTC 2023 aarch64 GNU/Linux`

`root@:/# file /bin/bash
/bin/bash: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=96c22dfc3c74ccf4ba77d9cce6fc2c5e635456c1, for GNU/Linux 3.7.0, stripped`

**Comment by autarchprinceps** [comment]
I get the same issue with at the least registry.k8s.io/node-problem-detector/node-problem-detector:v0.8.14
Seems like you guys didn't build the binary on each architecture this time. This used to work, but I couldn't quite say which version it broke at. Maybe it was more a change in your CI system too.

**Comment by runningman84** [comment]
The problem does not exists for older versions like registry.k8s.io/node-problem-detector/node-problem-detector:v0.8.13

**Comment by hakman** [comment]
This was fixed in https://github.com/kubernetes/node-problem-detector/pull/801, just that a new release will be needed.

**Comment by runningman84** [comment]
@hakman do you have any ETA for the release? We use flux to auto apply minor updates and this broke a lot of clusters...

**Comment by hakman** [comment]
There are very few people that can do releases. This is why https://github.com/kubernetes/node-problem-detector/pull/819.

**Comment by disconn3ct** [comment]
Are you saying that releases on hold until that feature ticket is resolved? This fix has been accepted, there shouldn't be much of a process block. Releases happened before somehow, and this is a major breakage.

**Comment by tuxpeople** [comment]
I would suggest thinking about fixing the release process, as a release process not allowing to publish an important fix for a major breakage is undoubtedly broken.

**Comment by disconn3ct** [comment]
Two months without a release. This takes "breaking the deploy and going home" to a whole new level.

**Comment by hakman** [comment]
@vteratipally @Random-Liu Can we do something about a NPD release?

**Comment by hakman** [comment]
NPD v0.8.15 has been released:
```
% crane digest registry.k8s.io/node-problem-detector/node-problem-detector:v0.8.15
sha256:15a8bad79ae26124109e6fdb696fd8536b2043f4ece8ff48f03073157d6a2c2d
```
/close

**Comment by vteratipally** [comment]
@hakman 

Could you please publish the release notes

**Comment by hakman** [comment]
> Could you please publish the release notes

@vteratipally I think only approvers have permission to publish releases.

**Comment by disconn3ct** [comment]
> NPD v0.8.15 has been released:

Is it a release if it is only partially done? Can this be opened until the release is actually complete?
