### ISSUE TITLE
Non Root option

### ISSUE THREAD

**Issue by maurolms** [kubernetes/node-problem-detector#837]
Is it possible to run the Container with a Non Root user? Didn`t see any reference that explicitly defines an user on the Dockerfile, so I was wondering if we could adopt a Non Root approach execution of the container.

**Comment by wangzhen127** [comment]
NPD's goal is to detect infra layer issues. So it needs to read logs in a place where non-privileged containers do not have permission.

/close

**Comment by wangzhen127** [comment]
Dup of https://github.com/kubernetes/node-problem-detector/issues/698
