### ISSUE TITLE
Performance benchmark and optimization

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/node-problem-detector#85]
We've got some data from https://github.com/kubernetes/node-problem-detector/issues/2.

However, after that we've made a lot of changes. We should do benchmark to measure the cpu and memory usage. And optimize the log parsing code of kernel monitor if the resource usage is too high.

An accurate and acceptable number is important for NPD rollout.

/cc @dchen1107

**Comment by Random-Liu** [comment]
Here is the new benchmark result. I still have an optimization in my mind, but the current resource usage already seems reasonable to me.

![screenshot from 2017-02-21 14 27 44](https://cloud.githubusercontent.com/assets/5821883/23188029/f4791fc8-f841-11e6-9578-54d360873f6a.png)

I'm adding 3 tests, will send a PR later:
* Move original npd functionality test from e2e into node e2e.
* Add benchmark e2e test to continuously test npd deployed in the cluster.
* Add e2e test to continuously verify the functionality of npd deployed in the cluster.

@dchen1107

**Comment by dchen1107** [comment]
The benchmark looks find to me.
