### ISSUE TITLE
What is up with the v0.8.15 tag?

### ISSUE THREAD

**Issue by elchenberg** [kubernetes/node-problem-detector#851]
There is a two weeks old [v0.8.15](https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.15) tag. In contrast to all the other (recent) tags it is not a verified commit and it is not a release. Is it safe to use anyway?

**Comment by hakman** [comment]
> Is it safe to use anyway?

Yes. 😄

**Comment by stafot** [comment]
And actually fixes an arm support problem which previous tag has.

**Comment by hakman** [comment]
> And actually fixes an arm support problem which previous tag has.

And many security related issues.

**Comment by hakman** [comment]
Newer base image, newer dependencies, newer Go.
You can try running a container image scanner on .13, .14 and .15.

**Comment by disconn3ct** [comment]
> You can try running a container image scanner on .13, .14 and .15.

Are you suggesting that users need to reverse-engineer your release notes?

**Comment by chotiwat** [comment]
It's missing the `log-counter` binary https://github.com/kubernetes/node-problem-detector/issues/854

**Comment by grzesrap** [comment]
when enable `network-problem-monitor.json` i see error:
`Failed to unmarshal configuration file "/config/network-problem-monitor.json": json: cannot unmarshal number into Go struct field MonitorConfig.pluginConfig of type string`
only /config/kernel-monitor.json and /config/docker-monitor.json works for me
k8s version: 1.21
image: registry.k8s.io/node-problem-detector/node-problem-detector:v0.8.15

**Comment by wangzhen127** [comment]
/close

k/k is using NPD v0.8.16 already and there is a plan to bump to v0.8.18 after code freeze. You can try the new versions. Feel free to file new issues if the new version does not work.
