### ISSUE TITLE
go.mod vulnerabilities fixed in master; when 0.8.16 release

### ISSUE THREAD

**Issue by zees-dev** [kubernetes/node-problem-detector#862]
[trivy](https://github.com/aquasecurity/trivy) has identified vulnerabilities in both `v0.8.14` and `v0.8.15`:

<img width="1241" alt="image" src="https://github.com/kubernetes/node-problem-detector/assets/63374656/ac1277de-1479-49ff-b107-ada0ab9b87b1">

- running `trivy fs --scanners vuln ./` in `v0.8.15`

The vulnerabilities appear to be fixed in master (probably from a dependency update?):

<img width="561" alt="image" src="https://github.com/kubernetes/node-problem-detector/assets/63374656/95cabb98-4f90-414d-9410-ddaa84e99a1c">

Wondering about the timeline for the next release; or wanting to know about any blockers which need to be remediated before the next release?

**Comment by JohnRusk** [comment]
@vteratipally I see you made the most recent release. Will you be making the next?  If so, what do you think about timing of 0.8.16 - given that it 0.8.15 contains these unpatched vulnerabilites?

**Comment by nick-rager** [comment]
@vteratipally 
@JohnRusk
Do we have any updates on this issue or timelines to share?

**Comment by vteratipally** [comment]
There is a new release 0.8.17. Could you please check.

**Comment by JohnRusk** [comment]
Yes, it's good. @zees-dev let's close this.
