### ISSUE TITLE
v1.8.13 restart count is 1 in gce-master-scale-performance 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/node-problem-detector#866]
v0.8.13 may has another problem(I may open another issue if it is not related)

Another case is the https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance flakes with error like
```
[measurement call TestMetrics - TestMetrics error: [action gather failed for SystemPodMetrics measurement: restart counts violation: RestartCount(node-problem-detector-gsg92, node-problem-detector)=1, want <= 0]]
```

It is tracked in https://github.com/kubernetes/kubernetes/issues/123328.

**Comment by pacoxu** [comment]
> I0225 17:35:11.161300 20814 ooms_tracker.go:284] OOM detected: &Event{ObjectMeta:{gce-scale-cluster-minion-heapster.17b72a4a62c4a7d8 default d60b06ff-11d1-4cb8-be1f-7264e084769b 85768 0 2024-02-25 17:11:22 +0000 UTC map[] map[] [] [] [{node-problem-detector Update v1 2024-02-25 17:11:22 +0000 UTC FieldsV1 {"f:count":{},"f:firstTimestamp":{},"f:involvedObject":{},"f:lastTimestamp":{},"f:message":{},"f:reason":{},"f:source":{"f:component":{},"f:host":{}},"f:type":{}} }]},InvolvedObject:ObjectReference{Kind:Node,Namespace:,Name:gce-scale-cluster-minion-heapster,UID:gce-scale-cluster-minion-heapster,APIVersion:,ResourceVersion:,FieldPath:,},Reason:OOMKilling,Message:Memory cgroup out of memory: Killed process 4550 (metrics-server) total-vm:834776kB, anon-rss:100100kB, file-rss:33900kB, shmem-rss:0kB, UID:65534 pgtables:400kB oom_score_adj:999,Source:EventSource{Component:kernel-monitor,Host:gce-scale-cluster-minion-heapster,},FirstTimestamp:2024-02-25 17:11:22 +0000 UTC,LastTimestamp:2024-02-25 17:11:22 +0000 UTC,Count:1,Type:Warning,EventTime:0001-01-01 00:00:00 +0000 UTC,Series:nil,Action:,Related:nil,ReportingController:,ReportingInstance:,}

```
        resources:
          limits:
            cpu: "200m"
-            memory: "100Mi"
+            memory: "150Mi"
          requests:
            cpu: "20m"
            memory: "20Mi"
```
The original memory limit for NPD pod is 100Mi. It hit the OOM.

It may indict larger memory usage with v0.8.13.
- we update it in k/k from 0.8.9 to v0.8.13 in https://github.com/kubernetes/kubernetes/pull/121382/ v1.29.

**Comment by pacoxu** [comment]
Do we have a benchmark about NPD memory usage?

**Comment by pacoxu** [comment]
/close

The log indicated that `metric-server` is restarted and NPD just detected it. 

It is not a NPD issue.

**Comment by pacoxu** [comment]
/reopen

The CI still showed the NPD is restarted.

https://kubernetes.slack.com/archives/C0BP8PW9G/p1708936782848279?thread_ts=1708933477.475099&cid=C0BP8PW9G
![image](https://github.com/kubernetes/node-problem-detector/assets/2010320/e1647f79-914c-4476-901e-b4c088f4e56f)

https://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=SystemPodMetrics&metricname=Load_SystemPodMetrics&RestartCount=RestartCount

**Comment by wangzhen127** [comment]
/close

Looks like https://github.com/kubernetes/kubernetes/issues/123328 has resolved already. Feel free to reopen if the issue stays.
