### ISSUE TITLE
Include automatic CVE scanning in build process

### ISSUE THREAD

**Issue by JohnRusk** [kubernetes/node-problem-detector#872]
Eg. with Trivy. Or similar. 

Goal would be to avoid undetected CVEs in
(a) the Go code and
(b) other elements of the docker image (as may be the case in #871)

**Comment by MartinForReal** [comment]
related https://github.com/kubernetes/node-problem-detector/pull/811

**Comment by wangzhen127** [comment]
/close

We are updating dependencies weekly now.
/cc @hakman
