### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by wangzhen127** [kubernetes/node-problem-detector#874]
Currently the release process is very manual. And only @Random-Liu can run `make push`. We should simplify the release process.

CC @Random-Liu @vteratipally @hakman

**Comment by wangzhen127** [comment]
Discussed with @BenTheElder offline. The main pain point of pushing and pulling from gs://kubernetes-release can be removed by just using the github.com file hosting in release notes. Since we already upload tar files in release notes, this would be a simple change.

See https://github.com/kubernetes/kubernetes/pull/123741

**Comment by hakman** [comment]
@wangzhen127 We can also promote binaries, like we do for kOps to the bucket (via k8s.io repo) and just link them in release notes.

**Comment by wangzhen127** [comment]
That's also fine. But using the github hosting file is the simplest way for now.

Does your organization set up NPD as system daemon of daemonset? So far, `cluster/gce/gci/configure.sh` is the only place setting it up as system daemon as far as I know. Given kube-up.sh will switch to kops in the future, and kops decides to treat NPD as addons, it may not worth the effort to set up pipelines to promote binaries.

**Comment by hakman** [comment]
I am fine with images at the moment.
kOps already has NPD as an addon 😄 . See https://github.com/kubernetes/kops/pull/11381.
We should update the NPD tests to run via kOps in the near future.

**Comment by wangzhen127** [comment]
Just realized a few things
- NPD releases tar files to `gs://kubernetes-release/node-problem-detector/` historically. No one has permission to push files to it now. We only have tar files up to `v0.8.10` in the GCS bucket.
- Currently k/k's default NPD version is:
  - k/k 1.28 uses NPD [v0.8.9](https://github.com/kubernetes/kubernetes/blob/v1.28.7/cluster/gce/gci/configure.sh#L29)
  - k/k 1.29 uses NPD [v0.8.13](https://github.com/kubernetes/kubernetes/blob/v1.29.2/cluster/gce/gci/configure.sh#L29)
  - k/k 1.30 uses NPD [v0.8.13](https://github.com/kubernetes/kubernetes/blob/v1.30.0-alpha.3/cluster/gce/gci/configure.sh)
- NPD's standalone mode configuration in k/k depends on the tar files in the above GCS bucket. Given none of k/k's release blocking tests fail, we already lost the test coverage for about half a year (for both k/k 1.29 and 1.30). I filed https://github.com/kubernetes/node-problem-detector/issues/878 for tracking separately.

For the release process, we should stop pushing tar files to `gs://kubernetes-release/node-problem-detector/`. We lost push permission for a long time already. Relying on github file hosting should be fine for k/k.

**Comment by wangzhen127** [comment]
I have removed the need of pushing tar files to gs://kubernetes-release during release. So any approvers should be able to make the release now. It is still a manual process. But given the low frequency of NPD releases. I can live with it for now. We can revisit if situations change.
