### ISSUE TITLE
Missing test coverage for standalone mode configuration

### ISSUE THREAD

**Issue by wangzhen127** [kubernetes/node-problem-detector#878]
NPD can be configured to run in either `standalone` or `daemonset` mode. In k/k, the NPD `standalone` mode can be configured and tested by [configure.sh#688](https://github.com/kubernetes/kubernetes/blob/d3d06c3c7e07c7c79ff46c0fc3b9f081ce6b0226/cluster/gce/gci/configure.sh#L688).  However, as part of the kops support, the default mode has been switched from `standalone` mode to `daemonset` mode in PR https://github.com/kubernetes/kubernetes/pull/121007. The PR also bumped NPD version from `v0.8.9` to `v0.8.13`.

On the other hand, NPD `standalone` mode test has always been relying on tar files in `gs://kubernetes-release/node-problem-detector/` historically (See [configure.sh#L29](https://github.com/kubernetes/kubernetes/blob/d3d06c3c7e07c7c79ff46c0fc3b9f081ce6b0226/cluster/gce/gci/configure.sh#L299)). And we only have NPD version up to `v0.8.10` in the GCS bucket, due to historical release problems. This means we do not even have `v0.8.13` tar files in the GCS. Given none of the k/k's release blocking tests fail, we lost the test coverage for standalone mode configuration already.

The release problem is being tracked by https://github.com/kubernetes/node-problem-detector/issues/874. We were trying to switch from using `gs://kubernetes-release/` to github's own file hosting (PR https://github.com/kubernetes/kubernetes/pull/123741) and realized the missing test coverage.

CC @upodroid @SergeyKanzhelev @Random-Liu @BenTheElder

**Comment by wangzhen127** [comment]
The missing test coverage is for k/k 1.29 and 1.30, which uses NPD `v0.8.13`. k/k 1.28 still uses NPD `v0.8.9`.

**Comment by wangzhen127** [comment]
CC @hakman @vteratipally

**Comment by wangzhen127** [comment]
CC @ndixita

**Comment by upodroid** [comment]
Potential solutions:
1. Change the node e2e test harness to install NPD as a systemd unit file and make the NPD test part of the node e2e tests instead of Kubernetes e2e tests.
2. NPD is installed as a daemonset by kOps which is the project's 1st party distribution and preferred cluster e2e provisioner. NPD is installed the same way with CAPI as well.
3. The Kubernetes e2e test assumes NPD is installed via daemonset which is reasonable.

**Comment by wangzhen127** [comment]
Thanks for the suggestions!

I looked into the existing NPD tests and realized that we are using standalone mode already. https://github.com/kubernetes/node-problem-detector/blob/master/test/build.sh#L79C8-L79C41

And we have several test jobs using it, including https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-kubernetes-gce-gci.

So we are good here already.
