### ISSUE TITLE
Migrate to Community CI By August 1st

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/node-problem-detector#920]
Node problem detector CI still needs migrating, per https://groups.google.com/a/kubernetes.io/g/dev/c/p6PAML90ZOU

You can find node problem detector jobs listed in:

https://github.com/kubernetes/test-infra/blob/master/docs/job-migration-todo.md

(see e.g. jobs with name containing "npd")

**Comment by wangzhen127** [comment]
The following tests still need migration:
- [CI](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/node-problem-detector/node-problem-detector-ci.yaml): ci-npd-build
- [presubmit](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/node-problem-detector/node-problem-detector-presubmits.yaml): pull-npd-e2e-node, pull-npd-e2e-kubernetes-gce-gci, pull-npd-e2e-kubernetes-gce-gci-custom-flags, pull-npd-e2e-kubernetes-gce-ubuntu, pull-npd-e2e-kubernetes-gce-ubuntu-custom-flags

https://github.com/kubernetes/kubernetes/issues/119211 tracked the issues we encountered previously.

**Comment by wangzhen127** [comment]
I will work with @digitalveer to look into this.

**Comment by wangzhen127** [comment]
There is also similar work tracked in https://github.com/kubernetes/test-infra/issues/31794

**Comment by BenTheElder** [comment]
Yeah, https://github.com/kubernetes/test-infra/issues/31794 was tracking the community migrating it, raised here for visibility that the deadline is approaching.

I spoke with @wangzhen127 and another colleague about this, we'll get this pushing to a community bucket and migrate over.

/assign

https://github.com/kubernetes/node-problem-detector/pull/925 will make the problem a bit simpler.

**Comment by BenTheElder** [comment]
OK so after #925, I spoke to my fellow SIG K8s Infra TLs.

There is a `gs://k8s-staging-npd` already created for NPD in k8s infra, since we're not using it for publishing binaries (thank you!) we can add IAM permission to prow to upload there from the community cluster and switch the scripts over.

That, plus no longer pushing to GCR from CI, should fix everything.


The IAM is managed in https://github.com/kubernetes/k8s.io, can take a look at this later and then we can see about switching buckets.

**Comment by BenTheElder** [comment]
Filed https://github.com/kubernetes/k8s.io/pull/7007 to allow k8s-infra-prow-build jobs to push to k8s-staging-npd

**Comment by BenTheElder** [comment]
I believe this is done now following:
- https://github.com/kubernetes/k8s.io/pull/7007
- https://github.com/kubernetes/node-problem-detector/pull/928
- https://github.com/kubernetes/test-infra/pull/33015
We can see CI jobs and presubmits are green now https://prow.k8s.io/?job=*npd*

**Comment by wangzhen127** [comment]
Thanks a lot for the work!
