### ISSUE TITLE
Unable to Install node-problem-detector version v0.8.19 on Rocky Linux version 8.10

### ISSUE THREAD

**Issue by sudheernv** [kubernetes/node-problem-detector#930]
Hi! 

Installation of node-problem-detector-v0.8.19-linux_amd64.tar.gz (https://github.com/kubernetes/node-problem-detector/releases/download/v0.8.19/node-problem-detector-v0.8.19-linux_amd64.tar.gz) on rocky linux OS gives below error. 

**Installation Error:**
libc.so.6(GLIBC_2.32)(64bit) is needed by node-problem-detector-0.8.19
libc.so.6(GLIBC_2.34)(64bit) is needed by node-problem-detector-0.8.19

**GCC Version Installed On Host:**
$ ldd --version
ldd (GNU libc) 2.28

Since upgrading gcc version on host is not an option, should I build the project with CGO_ENABLED:=0?  If yes, could you pls provide the necessary flags to set for the build.

**Comment by AnishShah** [comment]
We need cgo to build `log-counter` binary. You could disable it by running `ENABLE_JOURNALD=0 make build-tar`: https://github.com/kubernetes/node-problem-detector/blob/369020d878d03fffcb35d40482c3d400448ce1a4/Makefile#L97

**Comment by AnishShah** [comment]
/close

Please reopen if the above comment doesn't help.
