### ISSUE TITLE
[Question] Who will update the NodeCondition to "False" after the problem recovery

### ISSUE THREAD

**Issue by Congrool** [kubernetes/node-problem-detector#936]
Hi, I'm using the system-log-monitor to detect the node problem and update the respective NodeCondition, which can match logs in `/dev/kmsg` of specific pattern.

I noticed that the NPD updates the NodeCondtion Status to **True** when it gets the target log. But after digging into the code of systemlogmonitor, I didn't find anything which will reset the NodeCondition to **False** after recovery.

I want to know who will take the responsibility to update the NodeCondtion to **False** after recovery in the best practice. Is it the job of remedy system?

**Comment by googs1025** [comment]
IIUC, this needs to be done manually. We currently use a custom script to implement this internally. npd is a patrol system that is responsible for reporting problems but not for recovery. Recovery requires manual recovery and manual recovery of the status.
