### ISSUE TITLE
github action failed to create PR

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/node-problem-detector#947]
Recently we made changes in .github/workflow to add go version update flow, but now the bot failed to create PRs. See all the failed actions  https://github.com/kubernetes/node-problem-detector/actions

It has the following errors

```
Create or update the pull request
  Attempting creation of pull request
  Error: GitHub Actions is not permitted to create or approve pull requests.
  ```
  
  Not sure what cause the problem here, anyone could help look into this?

**Comment by wangzhen127** [comment]
@hakman Do you know what went wrong here?

**Comment by hakman** [comment]
@wangzhen127 I was just notified this week that GitHub actions are not permitted to create PRs anymore due to security reasons.

I think it's time to merge https://github.com/kubernetes/node-problem-detector/pull/912. @sozercan did an amazing job there. Could you take a look?
